// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: internal/api/activities.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码 可选 @gotags: query:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" query:"page"`
	// 页大小 可选 @gotags: query:"pageSize"
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize"`
	// 状态筛选 可选 @gotags: query:"status"
	Status        int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status" query:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityListRequest) Reset() {
	*x = ActivityListRequest{}
	mi := &file_internal_api_activities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityListRequest) ProtoMessage() {}

func (x *ActivityListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityListRequest.ProtoReflect.Descriptor instead.
func (*ActivityListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ActivityListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ActivityListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ActivityListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	List          []*ActivityItem        `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityListResponse) Reset() {
	*x = ActivityListResponse{}
	mi := &file_internal_api_activities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityListResponse) ProtoMessage() {}

func (x *ActivityListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityListResponse.ProtoReflect.Descriptor instead.
func (*ActivityListResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ActivityListResponse) GetList() []*ActivityItem {
	if x != nil {
		return x.List
	}
	return nil
}

type ActivityItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 活动标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	// 活动描述
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	// 封面图URL
	CoverUrl string `protobuf:"bytes,4,opt,name=coverUrl,proto3" json:"coverUrl"`
	// 开始时间
	StartTime string `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime"`
	// 结束时间
	EndTime string `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime"`
	// 地点名称
	Location string `protobuf:"bytes,7,opt,name=location,proto3" json:"location"`
	// 预估工时
	Duration float64 `protobuf:"fixed64,8,opt,name=duration,proto3" json:"duration"`
	// 最大招募人数
	MaxPeople int32 `protobuf:"varint,9,opt,name=maxPeople,proto3" json:"maxPeople"`
	// 当前已报名人数
	CurrentPeople int32 `protobuf:"varint,10,opt,name=currentPeople,proto3" json:"currentPeople"`
	// 状态: 1-报名中, 2-已结束, 3-已取消
	Status int32 `protobuf:"varint,11,opt,name=status,proto3" json:"status"`
	// 是否已报名 (当前用户)
	IsRegistered bool `protobuf:"varint,12,opt,name=isRegistered,proto3" json:"isRegistered"`
	// 是否已满员
	IsFull        bool `protobuf:"varint,13,opt,name=isFull,proto3" json:"isFull"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityItem) Reset() {
	*x = ActivityItem{}
	mi := &file_internal_api_activities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityItem) ProtoMessage() {}

func (x *ActivityItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityItem.ProtoReflect.Descriptor instead.
func (*ActivityItem) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActivityItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivityItem) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *ActivityItem) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ActivityItem) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ActivityItem) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ActivityItem) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ActivityItem) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

func (x *ActivityItem) GetCurrentPeople() int32 {
	if x != nil {
		return x.CurrentPeople
	}
	return 0
}

func (x *ActivityItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityItem) GetIsRegistered() bool {
	if x != nil {
		return x.IsRegistered
	}
	return false
}

func (x *ActivityItem) GetIsFull() bool {
	if x != nil {
		return x.IsFull
	}
	return false
}

type ActivitySignupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动ID 必填 @gotags: json:"activityId,required"
	ActivityId    int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivitySignupRequest) Reset() {
	*x = ActivitySignupRequest{}
	mi := &file_internal_api_activities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivitySignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivitySignupRequest) ProtoMessage() {}

func (x *ActivitySignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivitySignupRequest.ProtoReflect.Descriptor instead.
func (*ActivitySignupRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{3}
}

func (x *ActivitySignupRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type ActivitySignupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 报名成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivitySignupResponse) Reset() {
	*x = ActivitySignupResponse{}
	mi := &file_internal_api_activities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivitySignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivitySignupResponse) ProtoMessage() {}

func (x *ActivitySignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivitySignupResponse.ProtoReflect.Descriptor instead.
func (*ActivitySignupResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{4}
}

func (x *ActivitySignupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ActivityCancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动ID 必填 @gotags: json:"activityId,required"
	ActivityId    int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityCancelRequest) Reset() {
	*x = ActivityCancelRequest{}
	mi := &file_internal_api_activities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityCancelRequest) ProtoMessage() {}

func (x *ActivityCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityCancelRequest.ProtoReflect.Descriptor instead.
func (*ActivityCancelRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{5}
}

func (x *ActivityCancelRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type ActivityCancelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 取消成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityCancelResponse) Reset() {
	*x = ActivityCancelResponse{}
	mi := &file_internal_api_activities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityCancelResponse) ProtoMessage() {}

func (x *ActivityCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityCancelResponse.ProtoReflect.Descriptor instead.
func (*ActivityCancelResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{6}
}

func (x *ActivityCancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ActivityDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动ID 必填 @gotags: path:"id,required"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityDetailRequest) Reset() {
	*x = ActivityDetailRequest{}
	mi := &file_internal_api_activities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityDetailRequest) ProtoMessage() {}

func (x *ActivityDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityDetailRequest.ProtoReflect.Descriptor instead.
func (*ActivityDetailRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{7}
}

func (x *ActivityDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ActivityDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *ActivityInfo          `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityDetailResponse) Reset() {
	*x = ActivityDetailResponse{}
	mi := &file_internal_api_activities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityDetailResponse) ProtoMessage() {}

func (x *ActivityDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityDetailResponse.ProtoReflect.Descriptor instead.
func (*ActivityDetailResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{8}
}

func (x *ActivityDetailResponse) GetActivity() *ActivityInfo {
	if x != nil {
		return x.Activity
	}
	return nil
}

type ActivityInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 组织ID
	OrgId int64 `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId"`
	// 组织名称
	OrgName string `protobuf:"bytes,3,opt,name=orgName,proto3" json:"orgName"`
	// 活动标题
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title"`
	// 活动描述
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`
	// 封面图URL
	CoverUrl string `protobuf:"bytes,6,opt,name=coverUrl,proto3" json:"coverUrl"`
	// 开始时间
	StartTime string `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime"`
	// 结束时间
	EndTime string `protobuf:"bytes,8,opt,name=endTime,proto3" json:"endTime"`
	// 地点名称
	Location string `protobuf:"bytes,9,opt,name=location,proto3" json:"location"`
	// 详细地址
	Address string `protobuf:"bytes,10,opt,name=address,proto3" json:"address"`
	// 预估工时
	Duration float64 `protobuf:"fixed64,11,opt,name=duration,proto3" json:"duration"`
	// 最大招募人数
	MaxPeople int32 `protobuf:"varint,12,opt,name=maxPeople,proto3" json:"maxPeople"`
	// 当前已报名人数
	CurrentPeople int32 `protobuf:"varint,13,opt,name=currentPeople,proto3" json:"currentPeople"`
	// 状态: 1-报名中, 2-已结束, 3-已取消
	Status int32 `protobuf:"varint,14,opt,name=status,proto3" json:"status"`
	// 是否已报名 (当前用户)
	IsRegistered bool `protobuf:"varint,15,opt,name=isRegistered,proto3" json:"isRegistered"`
	// 创建时间
	CreatedAt     string `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityInfo) Reset() {
	*x = ActivityInfo{}
	mi := &file_internal_api_activities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInfo) ProtoMessage() {}

func (x *ActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInfo.ProtoReflect.Descriptor instead.
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{9}
}

func (x *ActivityInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityInfo) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *ActivityInfo) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *ActivityInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActivityInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivityInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *ActivityInfo) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ActivityInfo) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ActivityInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ActivityInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ActivityInfo) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ActivityInfo) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

func (x *ActivityInfo) GetCurrentPeople() int32 {
	if x != nil {
		return x.CurrentPeople
	}
	return 0
}

func (x *ActivityInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityInfo) GetIsRegistered() bool {
	if x != nil {
		return x.IsRegistered
	}
	return false
}

func (x *ActivityInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MyActivitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码 可选 @gotags: query:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" query:"page"`
	// 页大小 可选 @gotags: query:"pageSize"
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize"`
	// 状态筛选 可选 @gotags: query:"status"
	// 1-报名中, 2-已结束, 3-已取消
	Status        int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status" query:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyActivitiesRequest) Reset() {
	*x = MyActivitiesRequest{}
	mi := &file_internal_api_activities_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyActivitiesRequest) ProtoMessage() {}

func (x *MyActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyActivitiesRequest.ProtoReflect.Descriptor instead.
func (*MyActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{10}
}

func (x *MyActivitiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MyActivitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *MyActivitiesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MyActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	List          []*MyActivityItem      `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyActivitiesResponse) Reset() {
	*x = MyActivitiesResponse{}
	mi := &file_internal_api_activities_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyActivitiesResponse) ProtoMessage() {}

func (x *MyActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyActivitiesResponse.ProtoReflect.Descriptor instead.
func (*MyActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{11}
}

func (x *MyActivitiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MyActivitiesResponse) GetList() []*MyActivityItem {
	if x != nil {
		return x.List
	}
	return nil
}

type MyActivityItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 组织ID
	OrgId int64 `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId"`
	// 组织名称
	OrgName string `protobuf:"bytes,3,opt,name=orgName,proto3" json:"orgName"`
	// 活动标题
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title"`
	// 活动描述
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`
	// 封面图URL
	CoverUrl string `protobuf:"bytes,6,opt,name=coverUrl,proto3" json:"coverUrl"`
	// 开始时间
	StartTime string `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime"`
	// 结束时间
	EndTime string `protobuf:"bytes,8,opt,name=endTime,proto3" json:"endTime"`
	// 地点名称
	Location string `protobuf:"bytes,9,opt,name=location,proto3" json:"location"`
	// 预估工时
	Duration float64 `protobuf:"fixed64,10,opt,name=duration,proto3" json:"duration"`
	// 最大招募人数
	MaxPeople int32 `protobuf:"varint,11,opt,name=maxPeople,proto3" json:"maxPeople"`
	// 当前已报名人数
	CurrentPeople int32 `protobuf:"varint,12,opt,name=currentPeople,proto3" json:"currentPeople"`
	// 状态: 1-报名中, 2-已结束, 3-已取消
	Status int32 `protobuf:"varint,13,opt,name=status,proto3" json:"status"`
	// 报名时间
	SignupTime string `protobuf:"bytes,14,opt,name=signupTime,proto3" json:"signupTime"`
	// 签到状态: 0-未签到, 1-已签到
	CheckInStatus int32 `protobuf:"varint,15,opt,name=checkInStatus,proto3" json:"checkInStatus"`
	// 签到时间
	CheckInTime   string `protobuf:"bytes,16,opt,name=checkInTime,proto3" json:"checkInTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyActivityItem) Reset() {
	*x = MyActivityItem{}
	mi := &file_internal_api_activities_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyActivityItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyActivityItem) ProtoMessage() {}

func (x *MyActivityItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyActivityItem.ProtoReflect.Descriptor instead.
func (*MyActivityItem) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{12}
}

func (x *MyActivityItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MyActivityItem) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *MyActivityItem) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *MyActivityItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MyActivityItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MyActivityItem) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *MyActivityItem) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MyActivityItem) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *MyActivityItem) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *MyActivityItem) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MyActivityItem) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

func (x *MyActivityItem) GetCurrentPeople() int32 {
	if x != nil {
		return x.CurrentPeople
	}
	return 0
}

func (x *MyActivityItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MyActivityItem) GetSignupTime() string {
	if x != nil {
		return x.SignupTime
	}
	return ""
}

func (x *MyActivityItem) GetCheckInStatus() int32 {
	if x != nil {
		return x.CheckInStatus
	}
	return 0
}

func (x *MyActivityItem) GetCheckInTime() string {
	if x != nil {
		return x.CheckInTime
	}
	return ""
}

// CreateActivityRequest 创建活动请求
type CreateActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织ID 必填 @gotags: json:"orgId,required"
	OrgId int64 `protobuf:"varint,1,opt,name=orgId,proto3" json:"orgId,required"`
	// 活动标题 必填 @gotags: json:"title,required"
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,required"`
	// 活动描述 可选 @gotags: json:"description"
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	// 封面图URL 可选 @gotags: json:"coverUrl"
	CoverUrl string `protobuf:"bytes,4,opt,name=coverUrl,proto3" json:"coverUrl"`
	// 开始时间 必填 @gotags: json:"startTime,required"
	StartTime string `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,required"`
	// 结束时间 必填 @gotags: json:"endTime,required"
	EndTime string `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime,required"`
	// 地点名称 必填 @gotags: json:"location,required"
	Location string `protobuf:"bytes,7,opt,name=location,proto3" json:"location,required"`
	// 详细地址 可选 @gotags: json:"address"
	Address string `protobuf:"bytes,8,opt,name=address,proto3" json:"address"`
	// 预估工时（小时） 必填 @gotags: json:"duration,required"
	Duration float64 `protobuf:"fixed64,9,opt,name=duration,proto3" json:"duration,required"`
	// 最大招募人数（0表示不限） 必填 @gotags: json:"maxPeople,required"
	MaxPeople     int32 `protobuf:"varint,10,opt,name=maxPeople,proto3" json:"maxPeople,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_internal_api_activities_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{13}
}

func (x *CreateActivityRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *CreateActivityRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateActivityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateActivityRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *CreateActivityRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateActivityRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateActivityRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateActivityRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateActivityRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateActivityRequest) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

// CreateActivityResponse 创建活动响应
type CreateActivityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 消息
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityResponse) Reset() {
	*x = CreateActivityResponse{}
	mi := &file_internal_api_activities_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityResponse) ProtoMessage() {}

func (x *CreateActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityResponse.ProtoReflect.Descriptor instead.
func (*CreateActivityResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{14}
}

func (x *CreateActivityResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateActivityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateActivityRequest 更新活动请求
type UpdateActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动ID 必填 @gotags: path:"id,required"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	// 活动标题 可选 @gotags: json:"title"
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	// 活动描述 可选 @gotags: json:"description"
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	// 封面图URL 可选 @gotags: json:"coverUrl"
	CoverUrl string `protobuf:"bytes,4,opt,name=coverUrl,proto3" json:"coverUrl"`
	// 开始时间 可选 @gotags: json:"startTime"
	StartTime string `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime"`
	// 结束时间 可选 @gotags: json:"endTime"
	EndTime string `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime"`
	// 地点名称 可选 @gotags: json:"location"
	Location string `protobuf:"bytes,7,opt,name=location,proto3" json:"location"`
	// 详细地址 可选 @gotags: json:"address"
	Address string `protobuf:"bytes,8,opt,name=address,proto3" json:"address"`
	// 预估工时（小时） 可选 @gotags: json:"duration"
	Duration float64 `protobuf:"fixed64,9,opt,name=duration,proto3" json:"duration"`
	// 最大招募人数（0表示不限） 可选 @gotags: json:"maxPeople"
	MaxPeople     int32 `protobuf:"varint,10,opt,name=maxPeople,proto3" json:"maxPeople"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActivityRequest) Reset() {
	*x = UpdateActivityRequest{}
	mi := &file_internal_api_activities_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityRequest) ProtoMessage() {}

func (x *UpdateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityRequest.ProtoReflect.Descriptor instead.
func (*UpdateActivityRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateActivityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateActivityRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateActivityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateActivityRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *UpdateActivityRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateActivityRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateActivityRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateActivityRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateActivityRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UpdateActivityRequest) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

// UpdateActivityResponse 更新活动响应
type UpdateActivityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActivityResponse) Reset() {
	*x = UpdateActivityResponse{}
	mi := &file_internal_api_activities_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityResponse) ProtoMessage() {}

func (x *UpdateActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityResponse.ProtoReflect.Descriptor instead.
func (*UpdateActivityResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateActivityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteActivityRequest 删除活动请求
type DeleteActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动ID 必填 @gotags: path:"id,required"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActivityRequest) Reset() {
	*x = DeleteActivityRequest{}
	mi := &file_internal_api_activities_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActivityRequest) ProtoMessage() {}

func (x *DeleteActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActivityRequest.ProtoReflect.Descriptor instead.
func (*DeleteActivityRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteActivityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteActivityResponse 删除活动响应
type DeleteActivityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActivityResponse) Reset() {
	*x = DeleteActivityResponse{}
	mi := &file_internal_api_activities_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActivityResponse) ProtoMessage() {}

func (x *DeleteActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActivityResponse.ProtoReflect.Descriptor instead.
func (*DeleteActivityResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteActivityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CancelActivityRequest 取消活动请求
type CancelActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动ID 必填 @gotags: path:"id,required"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	// 取消原因 可选 @gotags: json:"reason"
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelActivityRequest) Reset() {
	*x = CancelActivityRequest{}
	mi := &file_internal_api_activities_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelActivityRequest) ProtoMessage() {}

func (x *CancelActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelActivityRequest.ProtoReflect.Descriptor instead.
func (*CancelActivityRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{19}
}

func (x *CancelActivityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CancelActivityRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CancelActivityResponse 取消活动响应
type CancelActivityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelActivityResponse) Reset() {
	*x = CancelActivityResponse{}
	mi := &file_internal_api_activities_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelActivityResponse) ProtoMessage() {}

func (x *CancelActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_activities_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelActivityResponse.ProtoReflect.Descriptor instead.
func (*CancelActivityResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_activities_proto_rawDescGZIP(), []int{20}
}

func (x *CancelActivityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_api_activities_proto protoreflect.FileDescriptor

const file_internal_api_activities_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/api/activities.proto\x12\bactivity\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"]\n" +
	"\x13ActivityListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"X\n" +
	"\x14ActivityListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.activity.ActivityItemR\x04list\"\xfa\x02\n" +
	"\fActivityItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcoverUrl\x18\x04 \x01(\tR\bcoverUrl\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x06 \x01(\tR\aendTime\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1a\n" +
	"\bduration\x18\b \x01(\x01R\bduration\x12\x1c\n" +
	"\tmaxPeople\x18\t \x01(\x05R\tmaxPeople\x12$\n" +
	"\rcurrentPeople\x18\n" +
	" \x01(\x05R\rcurrentPeople\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\"\n" +
	"\fisRegistered\x18\f \x01(\bR\fisRegistered\x12\x16\n" +
	"\x06isFull\x18\r \x01(\bR\x06isFull\"7\n" +
	"\x15ActivitySignupRequest\x12\x1e\n" +
	"\n" +
	"activityId\x18\x01 \x01(\x03R\n" +
	"activityId\"2\n" +
	"\x16ActivitySignupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x15ActivityCancelRequest\x12\x1e\n" +
	"\n" +
	"activityId\x18\x01 \x01(\x03R\n" +
	"activityId\"2\n" +
	"\x16ActivityCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x15ActivityDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\x16ActivityDetailResponse\x122\n" +
	"\bactivity\x18\x01 \x01(\v2\x16.activity.ActivityInfoR\bactivity\"\xca\x03\n" +
	"\fActivityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05orgId\x18\x02 \x01(\x03R\x05orgId\x12\x18\n" +
	"\aorgName\x18\x03 \x01(\tR\aorgName\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcoverUrl\x18\x06 \x01(\tR\bcoverUrl\x12\x1c\n" +
	"\tstartTime\x18\a \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\b \x01(\tR\aendTime\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x1a\n" +
	"\bduration\x18\v \x01(\x01R\bduration\x12\x1c\n" +
	"\tmaxPeople\x18\f \x01(\x05R\tmaxPeople\x12$\n" +
	"\rcurrentPeople\x18\r \x01(\x05R\rcurrentPeople\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x05R\x06status\x12\"\n" +
	"\fisRegistered\x18\x0f \x01(\bR\fisRegistered\x12\x1c\n" +
	"\tcreatedAt\x18\x10 \x01(\tR\tcreatedAt\"]\n" +
	"\x13MyActivitiesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"Z\n" +
	"\x14MyActivitiesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12,\n" +
	"\x04list\x18\x02 \x03(\v2\x18.activity.MyActivityItemR\x04list\"\xd8\x03\n" +
	"\x0eMyActivityItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05orgId\x18\x02 \x01(\x03R\x05orgId\x12\x18\n" +
	"\aorgName\x18\x03 \x01(\tR\aorgName\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcoverUrl\x18\x06 \x01(\tR\bcoverUrl\x12\x1c\n" +
	"\tstartTime\x18\a \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\b \x01(\tR\aendTime\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x01R\bduration\x12\x1c\n" +
	"\tmaxPeople\x18\v \x01(\x05R\tmaxPeople\x12$\n" +
	"\rcurrentPeople\x18\f \x01(\x05R\rcurrentPeople\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"signupTime\x18\x0e \x01(\tR\n" +
	"signupTime\x12$\n" +
	"\rcheckInStatus\x18\x0f \x01(\x05R\rcheckInStatus\x12 \n" +
	"\vcheckInTime\x18\x10 \x01(\tR\vcheckInTime\"\xa9\x02\n" +
	"\x15CreateActivityRequest\x12\x14\n" +
	"\x05orgId\x18\x01 \x01(\x03R\x05orgId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcoverUrl\x18\x04 \x01(\tR\bcoverUrl\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x06 \x01(\tR\aendTime\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bduration\x18\t \x01(\x01R\bduration\x12\x1c\n" +
	"\tmaxPeople\x18\n" +
	" \x01(\x05R\tmaxPeople\"B\n" +
	"\x16CreateActivityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa3\x02\n" +
	"\x15UpdateActivityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcoverUrl\x18\x04 \x01(\tR\bcoverUrl\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x06 \x01(\tR\aendTime\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bduration\x18\t \x01(\x01R\bduration\x12\x1c\n" +
	"\tmaxPeople\x18\n" +
	" \x01(\x05R\tmaxPeople\"2\n" +
	"\x16UpdateActivityResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\x15DeleteActivityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x16DeleteActivityResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"?\n" +
	"\x15CancelActivityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"2\n" +
	"\x16CancelActivityResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb4\b\n" +
	"\x0fActivityService\x12f\n" +
	"\fActivityList\x12\x1d.activity.ActivityListRequest\x1a\x1e.activity.ActivityListResponse\"\x17\x82\xd3\xe4\x93\x02\x11\"\x0f/api/activities\x12v\n" +
	"\x0eActivitySignup\x12\x1f.activity.ActivitySignupRequest\x1a .activity.ActivitySignupResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/activities/signup\x12v\n" +
	"\x0eActivityCancel\x12\x1f.activity.ActivityCancelRequest\x1a .activity.ActivityCancelResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/activities/cancel\x12p\n" +
	"\x0eActivityDetail\x12\x1f.activity.ActivityDetailRequest\x1a .activity.ActivityDetailResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/activities/:id\x12i\n" +
	"\fMyActivities\x12\x1d.activity.MyActivitiesRequest\x1a\x1e.activity.MyActivitiesResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x12/api/activities/my\x12v\n" +
	"\x0eCreateActivity\x12\x1f.activity.CreateActivityRequest\x1a .activity.CreateActivityResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/activities/create\x12s\n" +
	"\x0eUpdateActivity\x12\x1f.activity.UpdateActivityRequest\x1a .activity.UpdateActivityResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/activities/:id\x12q\n" +
	"\x0eDeleteActivity\x12\x1f.activity.DeleteActivityRequest\x1a .activity.DeleteActivityResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/activities/{id}\x12{\n" +
	"\x0eCancelActivity\x12\x1f.activity.CancelActivityRequest\x1a .activity.CancelActivityResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/activities/{id}/cancel\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_activities_proto_rawDescOnce sync.Once
	file_internal_api_activities_proto_rawDescData []byte
)

func file_internal_api_activities_proto_rawDescGZIP() []byte {
	file_internal_api_activities_proto_rawDescOnce.Do(func() {
		file_internal_api_activities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_activities_proto_rawDesc), len(file_internal_api_activities_proto_rawDesc)))
	})
	return file_internal_api_activities_proto_rawDescData
}

var file_internal_api_activities_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_internal_api_activities_proto_goTypes = []any{
	(*ActivityListRequest)(nil),    // 0: activity.ActivityListRequest
	(*ActivityListResponse)(nil),   // 1: activity.ActivityListResponse
	(*ActivityItem)(nil),           // 2: activity.ActivityItem
	(*ActivitySignupRequest)(nil),  // 3: activity.ActivitySignupRequest
	(*ActivitySignupResponse)(nil), // 4: activity.ActivitySignupResponse
	(*ActivityCancelRequest)(nil),  // 5: activity.ActivityCancelRequest
	(*ActivityCancelResponse)(nil), // 6: activity.ActivityCancelResponse
	(*ActivityDetailRequest)(nil),  // 7: activity.ActivityDetailRequest
	(*ActivityDetailResponse)(nil), // 8: activity.ActivityDetailResponse
	(*ActivityInfo)(nil),           // 9: activity.ActivityInfo
	(*MyActivitiesRequest)(nil),    // 10: activity.MyActivitiesRequest
	(*MyActivitiesResponse)(nil),   // 11: activity.MyActivitiesResponse
	(*MyActivityItem)(nil),         // 12: activity.MyActivityItem
	(*CreateActivityRequest)(nil),  // 13: activity.CreateActivityRequest
	(*CreateActivityResponse)(nil), // 14: activity.CreateActivityResponse
	(*UpdateActivityRequest)(nil),  // 15: activity.UpdateActivityRequest
	(*UpdateActivityResponse)(nil), // 16: activity.UpdateActivityResponse
	(*DeleteActivityRequest)(nil),  // 17: activity.DeleteActivityRequest
	(*DeleteActivityResponse)(nil), // 18: activity.DeleteActivityResponse
	(*CancelActivityRequest)(nil),  // 19: activity.CancelActivityRequest
	(*CancelActivityResponse)(nil), // 20: activity.CancelActivityResponse
}
var file_internal_api_activities_proto_depIdxs = []int32{
	2,  // 0: activity.ActivityListResponse.list:type_name -> activity.ActivityItem
	9,  // 1: activity.ActivityDetailResponse.activity:type_name -> activity.ActivityInfo
	12, // 2: activity.MyActivitiesResponse.list:type_name -> activity.MyActivityItem
	0,  // 3: activity.ActivityService.ActivityList:input_type -> activity.ActivityListRequest
	3,  // 4: activity.ActivityService.ActivitySignup:input_type -> activity.ActivitySignupRequest
	5,  // 5: activity.ActivityService.ActivityCancel:input_type -> activity.ActivityCancelRequest
	7,  // 6: activity.ActivityService.ActivityDetail:input_type -> activity.ActivityDetailRequest
	10, // 7: activity.ActivityService.MyActivities:input_type -> activity.MyActivitiesRequest
	13, // 8: activity.ActivityService.CreateActivity:input_type -> activity.CreateActivityRequest
	15, // 9: activity.ActivityService.UpdateActivity:input_type -> activity.UpdateActivityRequest
	17, // 10: activity.ActivityService.DeleteActivity:input_type -> activity.DeleteActivityRequest
	19, // 11: activity.ActivityService.CancelActivity:input_type -> activity.CancelActivityRequest
	1,  // 12: activity.ActivityService.ActivityList:output_type -> activity.ActivityListResponse
	4,  // 13: activity.ActivityService.ActivitySignup:output_type -> activity.ActivitySignupResponse
	6,  // 14: activity.ActivityService.ActivityCancel:output_type -> activity.ActivityCancelResponse
	8,  // 15: activity.ActivityService.ActivityDetail:output_type -> activity.ActivityDetailResponse
	11, // 16: activity.ActivityService.MyActivities:output_type -> activity.MyActivitiesResponse
	14, // 17: activity.ActivityService.CreateActivity:output_type -> activity.CreateActivityResponse
	16, // 18: activity.ActivityService.UpdateActivity:output_type -> activity.UpdateActivityResponse
	18, // 19: activity.ActivityService.DeleteActivity:output_type -> activity.DeleteActivityResponse
	20, // 20: activity.ActivityService.CancelActivity:output_type -> activity.CancelActivityResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_api_activities_proto_init() }
func file_internal_api_activities_proto_init() {
	if File_internal_api_activities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_activities_proto_rawDesc), len(file_internal_api_activities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_activities_proto_goTypes,
		DependencyIndexes: file_internal_api_activities_proto_depIdxs,
		MessageInfos:      file_internal_api_activities_proto_msgTypes,
	}.Build()
	File_internal_api_activities_proto = out.File
	file_internal_api_activities_proto_goTypes = nil
	file_internal_api_activities_proto_depIdxs = nil
}
