// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.0
// source: internal/api/analytics.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrgFunnelSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织ID 必填 @gotags: query:"orgId,required"
	OrgId int64 `protobuf:"varint,1,opt,name=orgId,proto3" json:"orgId" query:"orgId,required"`
	// 起始时间 可选 @gotags: query:"start"
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start" query:"start"`
	// 结束时间 可选 @gotags: query:"end"
	End           string `protobuf:"bytes,3,opt,name=end,proto3" json:"end" query:"end"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgFunnelSummaryRequest) Reset() {
	*x = OrgFunnelSummaryRequest{}
	mi := &file_internal_api_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgFunnelSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgFunnelSummaryRequest) ProtoMessage() {}

func (x *OrgFunnelSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgFunnelSummaryRequest.ProtoReflect.Descriptor instead.
func (*OrgFunnelSummaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *OrgFunnelSummaryRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *OrgFunnelSummaryRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *OrgFunnelSummaryRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type OrgFunnelSummaryResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	RegistrationCount            int64                  `protobuf:"varint,1,opt,name=registrationCount,proto3" json:"registrationCount"`
	MembershipCount              int64                  `protobuf:"varint,2,opt,name=membershipCount,proto3" json:"membershipCount"`
	SignupCount                  int64                  `protobuf:"varint,3,opt,name=signupCount,proto3" json:"signupCount"`
	AttendanceCount              int64                  `protobuf:"varint,4,opt,name=attendanceCount,proto3" json:"attendanceCount"`
	WorkhourCount                int64                  `protobuf:"varint,5,opt,name=workhourCount,proto3" json:"workhourCount"`
	RegistrationToMembershipRate float64                `protobuf:"fixed64,6,opt,name=registrationToMembershipRate,proto3" json:"registrationToMembershipRate"`
	MembershipToSignupRate       float64                `protobuf:"fixed64,7,opt,name=membershipToSignupRate,proto3" json:"membershipToSignupRate"`
	SignupToAttendanceRate       float64                `protobuf:"fixed64,8,opt,name=signupToAttendanceRate,proto3" json:"signupToAttendanceRate"`
	AttendanceToWorkhourRate     float64                `protobuf:"fixed64,9,opt,name=attendanceToWorkhourRate,proto3" json:"attendanceToWorkhourRate"`
	Start                        string                 `protobuf:"bytes,10,opt,name=start,proto3" json:"start"`
	End                          string                 `protobuf:"bytes,11,opt,name=end,proto3" json:"end"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *OrgFunnelSummaryResponse) Reset() {
	*x = OrgFunnelSummaryResponse{}
	mi := &file_internal_api_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgFunnelSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgFunnelSummaryResponse) ProtoMessage() {}

func (x *OrgFunnelSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgFunnelSummaryResponse.ProtoReflect.Descriptor instead.
func (*OrgFunnelSummaryResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *OrgFunnelSummaryResponse) GetRegistrationCount() int64 {
	if x != nil {
		return x.RegistrationCount
	}
	return 0
}

func (x *OrgFunnelSummaryResponse) GetMembershipCount() int64 {
	if x != nil {
		return x.MembershipCount
	}
	return 0
}

func (x *OrgFunnelSummaryResponse) GetSignupCount() int64 {
	if x != nil {
		return x.SignupCount
	}
	return 0
}

func (x *OrgFunnelSummaryResponse) GetAttendanceCount() int64 {
	if x != nil {
		return x.AttendanceCount
	}
	return 0
}

func (x *OrgFunnelSummaryResponse) GetWorkhourCount() int64 {
	if x != nil {
		return x.WorkhourCount
	}
	return 0
}

func (x *OrgFunnelSummaryResponse) GetRegistrationToMembershipRate() float64 {
	if x != nil {
		return x.RegistrationToMembershipRate
	}
	return 0
}

func (x *OrgFunnelSummaryResponse) GetMembershipToSignupRate() float64 {
	if x != nil {
		return x.MembershipToSignupRate
	}
	return 0
}

func (x *OrgFunnelSummaryResponse) GetSignupToAttendanceRate() float64 {
	if x != nil {
		return x.SignupToAttendanceRate
	}
	return 0
}

func (x *OrgFunnelSummaryResponse) GetAttendanceToWorkhourRate() float64 {
	if x != nil {
		return x.AttendanceToWorkhourRate
	}
	return 0
}

func (x *OrgFunnelSummaryResponse) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *OrgFunnelSummaryResponse) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

var File_internal_api_analytics_proto protoreflect.FileDescriptor

const file_internal_api_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/api/analytics.proto\x12\tanalytics\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"W\n" +
	"\x17OrgFunnelSummaryRequest\x12\x14\n" +
	"\x05orgId\x18\x01 \x01(\x03R\x05orgId\x12\x14\n" +
	"\x05start\x18\x02 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\"\xfc\x03\n" +
	"\x18OrgFunnelSummaryResponse\x12,\n" +
	"\x11registrationCount\x18\x01 \x01(\x03R\x11registrationCount\x12(\n" +
	"\x0fmembershipCount\x18\x02 \x01(\x03R\x0fmembershipCount\x12 \n" +
	"\vsignupCount\x18\x03 \x01(\x03R\vsignupCount\x12(\n" +
	"\x0fattendanceCount\x18\x04 \x01(\x03R\x0fattendanceCount\x12$\n" +
	"\rworkhourCount\x18\x05 \x01(\x03R\rworkhourCount\x12B\n" +
	"\x1cregistrationToMembershipRate\x18\x06 \x01(\x01R\x1cregistrationToMembershipRate\x126\n" +
	"\x16membershipToSignupRate\x18\a \x01(\x01R\x16membershipToSignupRate\x126\n" +
	"\x16signupToAttendanceRate\x18\b \x01(\x01R\x16signupToAttendanceRate\x12:\n" +
	"\x18attendanceToWorkhourRate\x18\t \x01(\x01R\x18attendanceToWorkhourRate\x12\x14\n" +
	"\x05start\x18\n" +
	" \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\v \x01(\tR\x03end2\xa3\x01\n" +
	"\x10AnalyticsService\x12~\n" +
	"\x10OrgFunnelSummary\x12\".analytics.OrgFunnelSummaryRequest\x1a#.analytics.OrgFunnelSummaryResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/analytics/org/funnel\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_analytics_proto_rawDescOnce sync.Once
	file_internal_api_analytics_proto_rawDescData []byte
)

func file_internal_api_analytics_proto_rawDescGZIP() []byte {
	file_internal_api_analytics_proto_rawDescOnce.Do(func() {
		file_internal_api_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_analytics_proto_rawDesc), len(file_internal_api_analytics_proto_rawDesc)))
	})
	return file_internal_api_analytics_proto_rawDescData
}

var file_internal_api_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_analytics_proto_goTypes = []any{
	(*OrgFunnelSummaryRequest)(nil),  // 0: analytics.OrgFunnelSummaryRequest
	(*OrgFunnelSummaryResponse)(nil), // 1: analytics.OrgFunnelSummaryResponse
}
var file_internal_api_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.OrgFunnelSummary:input_type -> analytics.OrgFunnelSummaryRequest
	1, // 1: analytics.AnalyticsService.OrgFunnelSummary:output_type -> analytics.OrgFunnelSummaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_analytics_proto_init() }
func file_internal_api_analytics_proto_init() {
	if File_internal_api_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_analytics_proto_rawDesc), len(file_internal_api_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_analytics_proto_goTypes,
		DependencyIndexes: file_internal_api_analytics_proto_depIdxs,
		MessageInfos:      file_internal_api_analytics_proto_msgTypes,
	}.Build()
	File_internal_api_analytics_proto = out.File
	file_internal_api_analytics_proto_goTypes = nil
	file_internal_api_analytics_proto_depIdxs = nil
}
