// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.0
// source: internal/api/assistant.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建会话请求
type AssistantCreateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 场景：general/activity_draft/ops_advisor 必填 @gotags: json:"scene,required"
	Scene string `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,required"`
	// 会话标题 可选 @gotags: json:"title"
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantCreateSessionRequest) Reset() {
	*x = AssistantCreateSessionRequest{}
	mi := &file_internal_api_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantCreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantCreateSessionRequest) ProtoMessage() {}

func (x *AssistantCreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantCreateSessionRequest.ProtoReflect.Descriptor instead.
func (*AssistantCreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *AssistantCreateSessionRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *AssistantCreateSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// 创建会话响应
type AssistantCreateSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID @gotags: json:"session_id"
	SessionId     int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantCreateSessionResponse) Reset() {
	*x = AssistantCreateSessionResponse{}
	mi := &file_internal_api_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantCreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantCreateSessionResponse) ProtoMessage() {}

func (x *AssistantCreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantCreateSessionResponse.ProtoReflect.Descriptor instead.
func (*AssistantCreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *AssistantCreateSessionResponse) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// 对话请求
type AssistantChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID 必填 @gotags: json:"session_id,required"
	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,required"`
	// 用户消息 必填 @gotags: json:"message,required"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,required"`
	// 是否流式（当前仅占位） @gotags: json:"stream"
	Stream        bool `protobuf:"varint,3,opt,name=stream,proto3" json:"stream"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantChatRequest) Reset() {
	*x = AssistantChatRequest{}
	mi := &file_internal_api_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantChatRequest) ProtoMessage() {}

func (x *AssistantChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantChatRequest.ProtoReflect.Descriptor instead.
func (*AssistantChatRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{2}
}

func (x *AssistantChatRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *AssistantChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AssistantChatRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

// 工具调用结果
type AssistantToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 工具名称 @gotags: json:"tool_name"
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name"`
	// 是否成功 @gotags: json:"success"
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success"`
	// 错误码 @gotags: json:"error_code"
	ErrorCode string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code"`
	// 错误信息 @gotags: json:"error_msg"
	ErrorMsg string `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg"`
	// 耗时毫秒 @gotags: json:"latency_ms"
	LatencyMs int32 `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms"`
	// 入参 JSON @gotags: json:"input"
	Input string `protobuf:"bytes,6,opt,name=input,proto3" json:"input"`
	// 出参 JSON @gotags: json:"output"
	Output        string `protobuf:"bytes,7,opt,name=output,proto3" json:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantToolCall) Reset() {
	*x = AssistantToolCall{}
	mi := &file_internal_api_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantToolCall) ProtoMessage() {}

func (x *AssistantToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantToolCall.ProtoReflect.Descriptor instead.
func (*AssistantToolCall) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{3}
}

func (x *AssistantToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *AssistantToolCall) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssistantToolCall) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AssistantToolCall) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *AssistantToolCall) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AssistantToolCall) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *AssistantToolCall) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// Token 用量
type AssistantUsage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 模型名 @gotags: json:"model"
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model"`
	// 输入 token @gotags: json:"token_in"
	TokenIn int32 `protobuf:"varint,2,opt,name=token_in,json=tokenIn,proto3" json:"token_in"`
	// 输出 token @gotags: json:"token_out"
	TokenOut int32 `protobuf:"varint,3,opt,name=token_out,json=tokenOut,proto3" json:"token_out"`
	// 耗时毫秒 @gotags: json:"latency_ms"
	LatencyMs     int32 `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantUsage) Reset() {
	*x = AssistantUsage{}
	mi := &file_internal_api_assistant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantUsage) ProtoMessage() {}

func (x *AssistantUsage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantUsage.ProtoReflect.Descriptor instead.
func (*AssistantUsage) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{4}
}

func (x *AssistantUsage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AssistantUsage) GetTokenIn() int32 {
	if x != nil {
		return x.TokenIn
	}
	return 0
}

func (x *AssistantUsage) GetTokenOut() int32 {
	if x != nil {
		return x.TokenOut
	}
	return 0
}

func (x *AssistantUsage) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// 对话响应
type AssistantChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 回复 @gotags: json:"reply"
	Reply string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply"`
	// 工具调用列表 @gotags: json:"tool_calls"
	ToolCalls []*AssistantToolCall `protobuf:"bytes,2,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls"`
	// 用量信息 @gotags: json:"usage"
	Usage         *AssistantUsage `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantChatResponse) Reset() {
	*x = AssistantChatResponse{}
	mi := &file_internal_api_assistant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantChatResponse) ProtoMessage() {}

func (x *AssistantChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantChatResponse.ProtoReflect.Descriptor instead.
func (*AssistantChatResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{5}
}

func (x *AssistantChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *AssistantChatResponse) GetToolCalls() []*AssistantToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *AssistantChatResponse) GetUsage() *AssistantUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// 会话历史请求
type AssistantSessionMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID 必填 @gotags: path:"id,required" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantSessionMessagesRequest) Reset() {
	*x = AssistantSessionMessagesRequest{}
	mi := &file_internal_api_assistant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantSessionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantSessionMessagesRequest) ProtoMessage() {}

func (x *AssistantSessionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantSessionMessagesRequest.ProtoReflect.Descriptor instead.
func (*AssistantSessionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{6}
}

func (x *AssistantSessionMessagesRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 历史消息
type AssistantMessageItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息ID @gotags: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 会话ID @gotags: json:"session_id"
	SessionId int64 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id"`
	// 序号 @gotags: json:"seq_no"
	SeqNo int32 `protobuf:"varint,3,opt,name=seq_no,json=seqNo,proto3" json:"seq_no"`
	// 角色：1-system，2-user，3-assistant，4-tool @gotags: json:"role"
	Role int32 `protobuf:"varint,4,opt,name=role,proto3" json:"role"`
	// 内容 @gotags: json:"content"
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content"`
	// 模型 @gotags: json:"model"
	Model string `protobuf:"bytes,6,opt,name=model,proto3" json:"model"`
	// 结束原因 @gotags: json:"finish_reason"
	FinishReason int32 `protobuf:"varint,7,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason"`
	// 输入 token @gotags: json:"token_in"
	TokenIn int32 `protobuf:"varint,8,opt,name=token_in,json=tokenIn,proto3" json:"token_in"`
	// 输出 token @gotags: json:"token_out"
	TokenOut int32 `protobuf:"varint,9,opt,name=token_out,json=tokenOut,proto3" json:"token_out"`
	// 延迟毫秒 @gotags: json:"latency_ms"
	LatencyMs int32 `protobuf:"varint,10,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms"`
	// 请求ID @gotags: json:"request_id"
	RequestId string `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	// 创建时间 @gotags: json:"created_at"
	CreatedAt     string `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantMessageItem) Reset() {
	*x = AssistantMessageItem{}
	mi := &file_internal_api_assistant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantMessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantMessageItem) ProtoMessage() {}

func (x *AssistantMessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantMessageItem.ProtoReflect.Descriptor instead.
func (*AssistantMessageItem) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{7}
}

func (x *AssistantMessageItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssistantMessageItem) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *AssistantMessageItem) GetSeqNo() int32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *AssistantMessageItem) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *AssistantMessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AssistantMessageItem) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AssistantMessageItem) GetFinishReason() int32 {
	if x != nil {
		return x.FinishReason
	}
	return 0
}

func (x *AssistantMessageItem) GetTokenIn() int32 {
	if x != nil {
		return x.TokenIn
	}
	return 0
}

func (x *AssistantMessageItem) GetTokenOut() int32 {
	if x != nil {
		return x.TokenOut
	}
	return 0
}

func (x *AssistantMessageItem) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AssistantMessageItem) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AssistantMessageItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 会话历史响应
type AssistantSessionMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 历史消息列表 @gotags: json:"list"
	List          []*AssistantMessageItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantSessionMessagesResponse) Reset() {
	*x = AssistantSessionMessagesResponse{}
	mi := &file_internal_api_assistant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantSessionMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantSessionMessagesResponse) ProtoMessage() {}

func (x *AssistantSessionMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantSessionMessagesResponse.ProtoReflect.Descriptor instead.
func (*AssistantSessionMessagesResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{8}
}

func (x *AssistantSessionMessagesResponse) GetList() []*AssistantMessageItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 活动草案快捷入口请求
type AssistantActivityDraftActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可选会话ID @gotags: json:"session_id"
	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id"`
	// 活动主题 必填 @gotags: json:"topic,required"
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,required"`
	// 目标人群 @gotags: json:"target_people"
	TargetPeople string `protobuf:"bytes,3,opt,name=target_people,json=targetPeople,proto3" json:"target_people"`
	// 地点 @gotags: json:"location"
	Location      string `protobuf:"bytes,4,opt,name=location,proto3" json:"location"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantActivityDraftActionRequest) Reset() {
	*x = AssistantActivityDraftActionRequest{}
	mi := &file_internal_api_assistant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantActivityDraftActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantActivityDraftActionRequest) ProtoMessage() {}

func (x *AssistantActivityDraftActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantActivityDraftActionRequest.ProtoReflect.Descriptor instead.
func (*AssistantActivityDraftActionRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{9}
}

func (x *AssistantActivityDraftActionRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *AssistantActivityDraftActionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AssistantActivityDraftActionRequest) GetTargetPeople() string {
	if x != nil {
		return x.TargetPeople
	}
	return ""
}

func (x *AssistantActivityDraftActionRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// 活动草案快捷入口响应
type AssistantActivityDraftActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID @gotags: json:"session_id"
	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id"`
	// 执行结果 @gotags: json:"result"
	Result        *AssistantChatResponse `protobuf:"bytes,2,opt,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantActivityDraftActionResponse) Reset() {
	*x = AssistantActivityDraftActionResponse{}
	mi := &file_internal_api_assistant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantActivityDraftActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantActivityDraftActionResponse) ProtoMessage() {}

func (x *AssistantActivityDraftActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_assistant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantActivityDraftActionResponse.ProtoReflect.Descriptor instead.
func (*AssistantActivityDraftActionResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_assistant_proto_rawDescGZIP(), []int{10}
}

func (x *AssistantActivityDraftActionResponse) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *AssistantActivityDraftActionResponse) GetResult() *AssistantChatResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_internal_api_assistant_proto protoreflect.FileDescriptor

const file_internal_api_assistant_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/api/assistant.proto\x12\tassistant\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"K\n" +
	"\x1dAssistantCreateSessionRequest\x12\x14\n" +
	"\x05scene\x18\x01 \x01(\tR\x05scene\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"?\n" +
	"\x1eAssistantCreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"g\n" +
	"\x14AssistantChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\bR\x06stream\"\xd3\x01\n" +
	"\x11AssistantToolCall\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x05R\tlatencyMs\x12\x14\n" +
	"\x05input\x18\x06 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\a \x01(\tR\x06output\"}\n" +
	"\x0eAssistantUsage\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x19\n" +
	"\btoken_in\x18\x02 \x01(\x05R\atokenIn\x12\x1b\n" +
	"\ttoken_out\x18\x03 \x01(\x05R\btokenOut\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x05R\tlatencyMs\"\x9b\x01\n" +
	"\x15AssistantChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12;\n" +
	"\n" +
	"tool_calls\x18\x02 \x03(\v2\x1c.assistant.AssistantToolCallR\ttoolCalls\x12/\n" +
	"\x05usage\x18\x03 \x01(\v2\x19.assistant.AssistantUsageR\x05usage\"1\n" +
	"\x1fAssistantSessionMessagesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xda\x02\n" +
	"\x14AssistantMessageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x15\n" +
	"\x06seq_no\x18\x03 \x01(\x05R\x05seqNo\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12#\n" +
	"\rfinish_reason\x18\a \x01(\x05R\ffinishReason\x12\x19\n" +
	"\btoken_in\x18\b \x01(\x05R\atokenIn\x12\x1b\n" +
	"\ttoken_out\x18\t \x01(\x05R\btokenOut\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\n" +
	" \x01(\x05R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"W\n" +
	" AssistantSessionMessagesResponse\x123\n" +
	"\x04list\x18\x01 \x03(\v2\x1f.assistant.AssistantMessageItemR\x04list\"\x9b\x01\n" +
	"#AssistantActivityDraftActionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12#\n" +
	"\rtarget_people\x18\x03 \x01(\tR\ftargetPeople\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\"\x7f\n" +
	"$AssistantActivityDraftActionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x128\n" +
	"\x06result\x18\x02 \x01(\v2 .assistant.AssistantChatResponseR\x06result2\xd7\x05\n" +
	"\x10AssistantService\x12\x88\x01\n" +
	"\rCreateSession\x12(.assistant.AssistantCreateSessionRequest\x1a).assistant.AssistantCreateSessionResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/assistant/sessions\x12i\n" +
	"\x04Chat\x12\x1f.assistant.AssistantChatRequest\x1a .assistant.AssistantChatResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/assistant/chat\x12v\n" +
	"\n" +
	"ChatStream\x12\x1f.assistant.AssistantChatRequest\x1a .assistant.AssistantChatResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/assistant/chat/stream\x12\x98\x01\n" +
	"\x0fSessionMessages\x12*.assistant.AssistantSessionMessagesRequest\x1a+.assistant.AssistantSessionMessagesResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/assistant/sessions/:id/messages\x12\xa8\x01\n" +
	"\x13ActivityDraftAction\x12..assistant.AssistantActivityDraftActionRequest\x1a/.assistant.AssistantActivityDraftActionResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/assistant/actions/activity-draft\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_assistant_proto_rawDescOnce sync.Once
	file_internal_api_assistant_proto_rawDescData []byte
)

func file_internal_api_assistant_proto_rawDescGZIP() []byte {
	file_internal_api_assistant_proto_rawDescOnce.Do(func() {
		file_internal_api_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_assistant_proto_rawDesc), len(file_internal_api_assistant_proto_rawDesc)))
	})
	return file_internal_api_assistant_proto_rawDescData
}

var file_internal_api_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_api_assistant_proto_goTypes = []any{
	(*AssistantCreateSessionRequest)(nil),        // 0: assistant.AssistantCreateSessionRequest
	(*AssistantCreateSessionResponse)(nil),       // 1: assistant.AssistantCreateSessionResponse
	(*AssistantChatRequest)(nil),                 // 2: assistant.AssistantChatRequest
	(*AssistantToolCall)(nil),                    // 3: assistant.AssistantToolCall
	(*AssistantUsage)(nil),                       // 4: assistant.AssistantUsage
	(*AssistantChatResponse)(nil),                // 5: assistant.AssistantChatResponse
	(*AssistantSessionMessagesRequest)(nil),      // 6: assistant.AssistantSessionMessagesRequest
	(*AssistantMessageItem)(nil),                 // 7: assistant.AssistantMessageItem
	(*AssistantSessionMessagesResponse)(nil),     // 8: assistant.AssistantSessionMessagesResponse
	(*AssistantActivityDraftActionRequest)(nil),  // 9: assistant.AssistantActivityDraftActionRequest
	(*AssistantActivityDraftActionResponse)(nil), // 10: assistant.AssistantActivityDraftActionResponse
}
var file_internal_api_assistant_proto_depIdxs = []int32{
	3,  // 0: assistant.AssistantChatResponse.tool_calls:type_name -> assistant.AssistantToolCall
	4,  // 1: assistant.AssistantChatResponse.usage:type_name -> assistant.AssistantUsage
	7,  // 2: assistant.AssistantSessionMessagesResponse.list:type_name -> assistant.AssistantMessageItem
	5,  // 3: assistant.AssistantActivityDraftActionResponse.result:type_name -> assistant.AssistantChatResponse
	0,  // 4: assistant.AssistantService.CreateSession:input_type -> assistant.AssistantCreateSessionRequest
	2,  // 5: assistant.AssistantService.Chat:input_type -> assistant.AssistantChatRequest
	2,  // 6: assistant.AssistantService.ChatStream:input_type -> assistant.AssistantChatRequest
	6,  // 7: assistant.AssistantService.SessionMessages:input_type -> assistant.AssistantSessionMessagesRequest
	9,  // 8: assistant.AssistantService.ActivityDraftAction:input_type -> assistant.AssistantActivityDraftActionRequest
	1,  // 9: assistant.AssistantService.CreateSession:output_type -> assistant.AssistantCreateSessionResponse
	5,  // 10: assistant.AssistantService.Chat:output_type -> assistant.AssistantChatResponse
	5,  // 11: assistant.AssistantService.ChatStream:output_type -> assistant.AssistantChatResponse
	8,  // 12: assistant.AssistantService.SessionMessages:output_type -> assistant.AssistantSessionMessagesResponse
	10, // 13: assistant.AssistantService.ActivityDraftAction:output_type -> assistant.AssistantActivityDraftActionResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_api_assistant_proto_init() }
func file_internal_api_assistant_proto_init() {
	if File_internal_api_assistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_assistant_proto_rawDesc), len(file_internal_api_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_assistant_proto_goTypes,
		DependencyIndexes: file_internal_api_assistant_proto_depIdxs,
		MessageInfos:      file_internal_api_assistant_proto_msgTypes,
	}.Build()
	File_internal_api_assistant_proto = out.File
	file_internal_api_assistant_proto_goTypes = nil
	file_internal_api_assistant_proto_depIdxs = nil
}
