// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.0
// source: internal/api/audit.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 志愿者加入组织待审核列表查询参数
type PendingVolunteerJoinOrgAuditListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 标题/副标题关键词 @gotags: query:"keyword"
	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword" query:"keyword"`
	// 页码（从 1 开始） @gotags: query:"page"
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page" query:"page"`
	// 每页条数 @gotags: query:"pageSize"
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize"`
	// 审核状态 @gotags: query:"status"
	Status        []int32 `protobuf:"varint,4,rep,packed,name=status,proto3" json:"status" query:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingVolunteerJoinOrgAuditListRequest) Reset() {
	*x = PendingVolunteerJoinOrgAuditListRequest{}
	mi := &file_internal_api_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingVolunteerJoinOrgAuditListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingVolunteerJoinOrgAuditListRequest) ProtoMessage() {}

func (x *PendingVolunteerJoinOrgAuditListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingVolunteerJoinOrgAuditListRequest.ProtoReflect.Descriptor instead.
func (*PendingVolunteerJoinOrgAuditListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{0}
}

func (x *PendingVolunteerJoinOrgAuditListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *PendingVolunteerJoinOrgAuditListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PendingVolunteerJoinOrgAuditListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PendingVolunteerJoinOrgAuditListRequest) GetStatus() []int32 {
	if x != nil {
		return x.Status
	}
	return nil
}

// 志愿者加入组织待审核列表查询结果
type PendingVolunteerJoinOrgAuditListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总记录数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	// 当前页数据
	List          []*PendingVolunteerJoinOrgAuditItem `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingVolunteerJoinOrgAuditListResponse) Reset() {
	*x = PendingVolunteerJoinOrgAuditListResponse{}
	mi := &file_internal_api_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingVolunteerJoinOrgAuditListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingVolunteerJoinOrgAuditListResponse) ProtoMessage() {}

func (x *PendingVolunteerJoinOrgAuditListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingVolunteerJoinOrgAuditListResponse.ProtoReflect.Descriptor instead.
func (*PendingVolunteerJoinOrgAuditListResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{1}
}

func (x *PendingVolunteerJoinOrgAuditListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PendingVolunteerJoinOrgAuditListResponse) GetList() []*PendingVolunteerJoinOrgAuditItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 志愿者加入组织待审核对象摘要信息
type PendingVolunteerJoinOrgAuditItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 审核目标 ID（org_members.id）
	TargetId int64 `protobuf:"varint,1,opt,name=targetId,proto3" json:"targetId"`
	// 当前审核状态（业务侧约定枚举值）
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status"`
	// 主标题
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title"`
	// 副标题
	SubTitle string `protobuf:"bytes,4,opt,name=subTitle,proto3" json:"subTitle"`
	// 创建时间（字符串时间格式由服务端统一约定）
	CreatedAt     string `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingVolunteerJoinOrgAuditItem) Reset() {
	*x = PendingVolunteerJoinOrgAuditItem{}
	mi := &file_internal_api_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingVolunteerJoinOrgAuditItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingVolunteerJoinOrgAuditItem) ProtoMessage() {}

func (x *PendingVolunteerJoinOrgAuditItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingVolunteerJoinOrgAuditItem.ProtoReflect.Descriptor instead.
func (*PendingVolunteerJoinOrgAuditItem) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{2}
}

func (x *PendingVolunteerJoinOrgAuditItem) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *PendingVolunteerJoinOrgAuditItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PendingVolunteerJoinOrgAuditItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PendingVolunteerJoinOrgAuditItem) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *PendingVolunteerJoinOrgAuditItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 执行审核请求参数
type AuditApprovalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 审核记录id @gotags: json:"id,required"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,required"`
	// 原因 @gotags: json:"reason"
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditApprovalRequest) Reset() {
	*x = AuditApprovalRequest{}
	mi := &file_internal_api_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditApprovalRequest) ProtoMessage() {}

func (x *AuditApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditApprovalRequest.ProtoReflect.Descriptor instead.
func (*AuditApprovalRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{3}
}

func (x *AuditApprovalRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditApprovalRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 执行审核返回结果
type AuditApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditApprovalResponse) Reset() {
	*x = AuditApprovalResponse{}
	mi := &file_internal_api_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditApprovalResponse) ProtoMessage() {}

func (x *AuditApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditApprovalResponse.ProtoReflect.Descriptor instead.
func (*AuditApprovalResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{4}
}

// 执行审核驳回请求参数
type AuditRejectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 审核记录id @gotags: json:"id,required"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,required"`
	// 原因 @gotags: json:"reason"
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRejectionRequest) Reset() {
	*x = AuditRejectionRequest{}
	mi := &file_internal_api_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRejectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRejectionRequest) ProtoMessage() {}

func (x *AuditRejectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRejectionRequest.ProtoReflect.Descriptor instead.
func (*AuditRejectionRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{5}
}

func (x *AuditRejectionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditRejectionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 执行审核驳回返回结果
type AuditRejectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRejectionResponse) Reset() {
	*x = AuditRejectionResponse{}
	mi := &file_internal_api_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRejectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRejectionResponse) ProtoMessage() {}

func (x *AuditRejectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRejectionResponse.ProtoReflect.Descriptor instead.
func (*AuditRejectionResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{6}
}

// 审核记录详情查询参数
type AuditRecordDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 审核记录 ID @gotags: path:"id,required"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecordDetailRequest) Reset() {
	*x = AuditRecordDetailRequest{}
	mi := &file_internal_api_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecordDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecordDetailRequest) ProtoMessage() {}

func (x *AuditRecordDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecordDetailRequest.ProtoReflect.Descriptor instead.
func (*AuditRecordDetailRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{7}
}

func (x *AuditRecordDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 审核记录详情查询结果
type AuditRecordDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 审核记录详情
	Record        *AuditRecordDetail `protobuf:"bytes,1,opt,name=record,proto3" json:"record"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecordDetailResponse) Reset() {
	*x = AuditRecordDetailResponse{}
	mi := &file_internal_api_audit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecordDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecordDetailResponse) ProtoMessage() {}

func (x *AuditRecordDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecordDetailResponse.ProtoReflect.Descriptor instead.
func (*AuditRecordDetailResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{8}
}

func (x *AuditRecordDetailResponse) GetRecord() *AuditRecordDetail {
	if x != nil {
		return x.Record
	}
	return nil
}

// 审核记录详情
type AuditRecordDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 审核记录 ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 审核目标类型
	TargetType int32 `protobuf:"varint,2,opt,name=targetType,proto3" json:"targetType"`
	// 审核目标 ID
	TargetId int64 `protobuf:"varint,3,opt,name=targetId,proto3" json:"targetId"`
	// 审核人 ID
	AuditorId int64 `protobuf:"varint,4,opt,name=auditorId,proto3" json:"auditorId"`
	// 审核状态
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	// 审核前内容快照
	OldContent string `protobuf:"bytes,6,opt,name=oldContent,proto3" json:"oldContent"`
	// 审核后内容快照
	NewContent string `protobuf:"bytes,7,opt,name=newContent,proto3" json:"newContent"`
	// 审核结果
	AuditResult int32 `protobuf:"varint,8,opt,name=auditResult,proto3" json:"auditResult"`
	// 驳回原因
	RejectReason string `protobuf:"bytes,9,opt,name=rejectReason,proto3" json:"rejectReason"`
	// 审核时间
	AuditTime string `protobuf:"bytes,10,opt,name=auditTime,proto3" json:"auditTime"`
	// 记录创建时间
	CreatedAt     string `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecordDetail) Reset() {
	*x = AuditRecordDetail{}
	mi := &file_internal_api_audit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecordDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecordDetail) ProtoMessage() {}

func (x *AuditRecordDetail) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_audit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecordDetail.ProtoReflect.Descriptor instead.
func (*AuditRecordDetail) Descriptor() ([]byte, []int) {
	return file_internal_api_audit_proto_rawDescGZIP(), []int{9}
}

func (x *AuditRecordDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditRecordDetail) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *AuditRecordDetail) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *AuditRecordDetail) GetAuditorId() int64 {
	if x != nil {
		return x.AuditorId
	}
	return 0
}

func (x *AuditRecordDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuditRecordDetail) GetOldContent() string {
	if x != nil {
		return x.OldContent
	}
	return ""
}

func (x *AuditRecordDetail) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

func (x *AuditRecordDetail) GetAuditResult() int32 {
	if x != nil {
		return x.AuditResult
	}
	return 0
}

func (x *AuditRecordDetail) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *AuditRecordDetail) GetAuditTime() string {
	if x != nil {
		return x.AuditTime
	}
	return ""
}

func (x *AuditRecordDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_internal_api_audit_proto protoreflect.FileDescriptor

const file_internal_api_audit_proto_rawDesc = "" +
	"\n" +
	"\x18internal/api/audit.proto\x12\x05audit\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"\x8b\x01\n" +
	"'PendingVolunteerJoinOrgAuditListRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x04 \x03(\x05R\x06status\"}\n" +
	"(PendingVolunteerJoinOrgAuditListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12;\n" +
	"\x04list\x18\x02 \x03(\v2'.audit.PendingVolunteerJoinOrgAuditItemR\x04list\"\xa6\x01\n" +
	" PendingVolunteerJoinOrgAuditItem\x12\x1a\n" +
	"\btargetId\x18\x01 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubTitle\x18\x04 \x01(\tR\bsubTitle\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\">\n" +
	"\x14AuditApprovalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x17\n" +
	"\x15AuditApprovalResponse\"?\n" +
	"\x15AuditRejectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x18\n" +
	"\x16AuditRejectionResponse\"*\n" +
	"\x18AuditRecordDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"M\n" +
	"\x19AuditRecordDetailResponse\x120\n" +
	"\x06record\x18\x01 \x01(\v2\x18.audit.AuditRecordDetailR\x06record\"\xd7\x02\n" +
	"\x11AuditRecordDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"targetType\x18\x02 \x01(\x05R\n" +
	"targetType\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\x03R\btargetId\x12\x1c\n" +
	"\tauditorId\x18\x04 \x01(\x03R\tauditorId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"oldContent\x18\x06 \x01(\tR\n" +
	"oldContent\x12\x1e\n" +
	"\n" +
	"newContent\x18\a \x01(\tR\n" +
	"newContent\x12 \n" +
	"\vauditResult\x18\b \x01(\x05R\vauditResult\x12\"\n" +
	"\frejectReason\x18\t \x01(\tR\frejectReason\x12\x1c\n" +
	"\tauditTime\x18\n" +
	" \x01(\tR\tauditTime\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt2\xac\x04\n" +
	"\fAuditService\x12\xb3\x01\n" +
	" PendingVolunteerJoinOrgAuditList\x12..audit.PendingVolunteerJoinOrgAuditListRequest\x1a/.audit.PendingVolunteerJoinOrgAuditListResponse\".\x82\xd3\xe4\x93\x02(\"&/api/audits/volunteer-join-org/pending\x12k\n" +
	"\rAuditApproval\x12\x1b.audit.AuditApprovalRequest\x1a\x1c.audit.AuditApprovalResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/audits/approval\x12o\n" +
	"\x0eAuditRejection\x12\x1c.audit.AuditRejectionRequest\x1a\x1d.audit.AuditRejectionResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/audits/rejection\x12w\n" +
	"\x11AuditRecordDetail\x12\x1f.audit.AuditRecordDetailRequest\x1a .audit.AuditRecordDetailResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/audits/records/:id\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_audit_proto_rawDescOnce sync.Once
	file_internal_api_audit_proto_rawDescData []byte
)

func file_internal_api_audit_proto_rawDescGZIP() []byte {
	file_internal_api_audit_proto_rawDescOnce.Do(func() {
		file_internal_api_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_audit_proto_rawDesc), len(file_internal_api_audit_proto_rawDesc)))
	})
	return file_internal_api_audit_proto_rawDescData
}

var file_internal_api_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_api_audit_proto_goTypes = []any{
	(*PendingVolunteerJoinOrgAuditListRequest)(nil),  // 0: audit.PendingVolunteerJoinOrgAuditListRequest
	(*PendingVolunteerJoinOrgAuditListResponse)(nil), // 1: audit.PendingVolunteerJoinOrgAuditListResponse
	(*PendingVolunteerJoinOrgAuditItem)(nil),         // 2: audit.PendingVolunteerJoinOrgAuditItem
	(*AuditApprovalRequest)(nil),                     // 3: audit.AuditApprovalRequest
	(*AuditApprovalResponse)(nil),                    // 4: audit.AuditApprovalResponse
	(*AuditRejectionRequest)(nil),                    // 5: audit.AuditRejectionRequest
	(*AuditRejectionResponse)(nil),                   // 6: audit.AuditRejectionResponse
	(*AuditRecordDetailRequest)(nil),                 // 7: audit.AuditRecordDetailRequest
	(*AuditRecordDetailResponse)(nil),                // 8: audit.AuditRecordDetailResponse
	(*AuditRecordDetail)(nil),                        // 9: audit.AuditRecordDetail
}
var file_internal_api_audit_proto_depIdxs = []int32{
	2, // 0: audit.PendingVolunteerJoinOrgAuditListResponse.list:type_name -> audit.PendingVolunteerJoinOrgAuditItem
	9, // 1: audit.AuditRecordDetailResponse.record:type_name -> audit.AuditRecordDetail
	0, // 2: audit.AuditService.PendingVolunteerJoinOrgAuditList:input_type -> audit.PendingVolunteerJoinOrgAuditListRequest
	3, // 3: audit.AuditService.AuditApproval:input_type -> audit.AuditApprovalRequest
	5, // 4: audit.AuditService.AuditRejection:input_type -> audit.AuditRejectionRequest
	7, // 5: audit.AuditService.AuditRecordDetail:input_type -> audit.AuditRecordDetailRequest
	1, // 6: audit.AuditService.PendingVolunteerJoinOrgAuditList:output_type -> audit.PendingVolunteerJoinOrgAuditListResponse
	4, // 7: audit.AuditService.AuditApproval:output_type -> audit.AuditApprovalResponse
	6, // 8: audit.AuditService.AuditRejection:output_type -> audit.AuditRejectionResponse
	8, // 9: audit.AuditService.AuditRecordDetail:output_type -> audit.AuditRecordDetailResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_api_audit_proto_init() }
func file_internal_api_audit_proto_init() {
	if File_internal_api_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_audit_proto_rawDesc), len(file_internal_api_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_audit_proto_goTypes,
		DependencyIndexes: file_internal_api_audit_proto_depIdxs,
		MessageInfos:      file_internal_api_audit_proto_msgTypes,
	}.Build()
	File_internal_api_audit_proto = out.File
	file_internal_api_audit_proto_goTypes = nil
	file_internal_api_audit_proto_depIdxs = nil
}
