// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.0
// source: internal/api/authz.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	RoleCode      string                 `protobuf:"bytes,2,opt,name=roleCode,proto3" json:"roleCode"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=roleName,proto3" json:"roleName"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_internal_api_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{0}
}

func (x *RoleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RoleInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RoleListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色关键字（role_code/role_name） @gotags: query:"keyword"
	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword" query:"keyword"`
	// 是否包含禁用角色 @gotags: query:"includeDisabled"
	IncludeDisabled bool `protobuf:"varint,2,opt,name=includeDisabled,proto3" json:"includeDisabled" query:"includeDisabled"`
	// 页码 @gotags: query:"page"
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page" query:"page"`
	// 每页条数 @gotags: query:"pageSize"
	PageSize      int32 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListRequest) Reset() {
	*x = RoleListRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListRequest) ProtoMessage() {}

func (x *RoleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListRequest.ProtoReflect.Descriptor instead.
func (*RoleListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{1}
}

func (x *RoleListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *RoleListRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

func (x *RoleListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RoleListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RoleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	List          []*RoleInfo            `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListResponse) Reset() {
	*x = RoleListResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListResponse) ProtoMessage() {}

func (x *RoleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListResponse.ProtoReflect.Descriptor instead.
func (*RoleListResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{2}
}

func (x *RoleListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RoleListResponse) GetList() []*RoleInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type RoleCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleCode      string                 `protobuf:"bytes,1,opt,name=roleCode,proto3" json:"roleCode"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleCreateRequest) Reset() {
	*x = RoleCreateRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCreateRequest) ProtoMessage() {}

func (x *RoleCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCreateRequest.ProtoReflect.Descriptor instead.
func (*RoleCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{3}
}

func (x *RoleCreateRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RoleCreateRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RoleCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleCreateResponse) Reset() {
	*x = RoleCreateResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCreateResponse) ProtoMessage() {}

func (x *RoleCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCreateResponse.ProtoReflect.Descriptor instead.
func (*RoleCreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{4}
}

func (x *RoleCreateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoleUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID @gotags: path:"id,required"
	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	RoleName      string `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleUpdateRequest) Reset() {
	*x = RoleUpdateRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUpdateRequest) ProtoMessage() {}

func (x *RoleUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUpdateRequest.ProtoReflect.Descriptor instead.
func (*RoleUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{5}
}

func (x *RoleUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleUpdateRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RoleUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleUpdateResponse) Reset() {
	*x = RoleUpdateResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUpdateResponse) ProtoMessage() {}

func (x *RoleUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUpdateResponse.ProtoReflect.Descriptor instead.
func (*RoleUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{6}
}

func (x *RoleUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoleStatusUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID @gotags: path:"id,required"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	Status        int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleStatusUpdateRequest) Reset() {
	*x = RoleStatusUpdateRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleStatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleStatusUpdateRequest) ProtoMessage() {}

func (x *RoleStatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleStatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*RoleStatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{7}
}

func (x *RoleStatusUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleStatusUpdateRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RoleStatusUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleStatusUpdateResponse) Reset() {
	*x = RoleStatusUpdateResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleStatusUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleStatusUpdateResponse) ProtoMessage() {}

func (x *RoleStatusUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleStatusUpdateResponse.ProtoReflect.Descriptor instead.
func (*RoleStatusUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{8}
}

func (x *RoleStatusUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PermissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionInfo) Reset() {
	*x = PermissionInfo{}
	mi := &file_internal_api_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionInfo) ProtoMessage() {}

func (x *PermissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionInfo.ProtoReflect.Descriptor instead.
func (*PermissionInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{9}
}

func (x *PermissionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionInfo) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PermissionInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PermissionListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限关键字（resource/action/description） @gotags: query:"keyword"
	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword" query:"keyword"`
	// 仅返回启用权限 @gotags: query:"onlyEnabled"
	OnlyEnabled   bool `protobuf:"varint,2,opt,name=onlyEnabled,proto3" json:"onlyEnabled" query:"onlyEnabled"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionListRequest) Reset() {
	*x = PermissionListRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionListRequest) ProtoMessage() {}

func (x *PermissionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionListRequest.ProtoReflect.Descriptor instead.
func (*PermissionListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{10}
}

func (x *PermissionListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *PermissionListRequest) GetOnlyEnabled() bool {
	if x != nil {
		return x.OnlyEnabled
	}
	return false
}

type PermissionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PermissionInfo      `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionListResponse) Reset() {
	*x = PermissionListResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionListResponse) ProtoMessage() {}

func (x *PermissionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionListResponse.ProtoReflect.Descriptor instead.
func (*PermissionListResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{11}
}

func (x *PermissionListResponse) GetList() []*PermissionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type RolePermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID @gotags: path:"roleId,required"
	RoleId        int64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId" path:"roleId,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionsRequest) Reset() {
	*x = RolePermissionsRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionsRequest) ProtoMessage() {}

func (x *RolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*RolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{12}
}

func (x *RolePermissionsRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RolePermissionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  int64                  `protobuf:"varint,1,opt,name=permissionId,proto3" json:"permissionId"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionItem) Reset() {
	*x = RolePermissionItem{}
	mi := &file_internal_api_authz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionItem) ProtoMessage() {}

func (x *RolePermissionItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionItem.ProtoReflect.Descriptor instead.
func (*RolePermissionItem) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{13}
}

func (x *RolePermissionItem) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *RolePermissionItem) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *RolePermissionItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RolePermissionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RolePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId"`
	Permissions   []*RolePermissionItem  `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionsResponse) Reset() {
	*x = RolePermissionsResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionsResponse) ProtoMessage() {}

func (x *RolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*RolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{14}
}

func (x *RolePermissionsResponse) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RolePermissionsResponse) GetPermissions() []*RolePermissionItem {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type RolePermissionsSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID @gotags: path:"roleId,required"
	RoleId        int64   `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId" path:"roleId,required"`
	PermissionIds []int64 `protobuf:"varint,2,rep,packed,name=permissionIds,proto3" json:"permissionIds"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionsSetRequest) Reset() {
	*x = RolePermissionsSetRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionsSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionsSetRequest) ProtoMessage() {}

func (x *RolePermissionsSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionsSetRequest.ProtoReflect.Descriptor instead.
func (*RolePermissionsSetRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{15}
}

func (x *RolePermissionsSetRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RolePermissionsSetRequest) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

type RolePermissionsSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionsSetResponse) Reset() {
	*x = RolePermissionsSetResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionsSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionsSetResponse) ProtoMessage() {}

func (x *RolePermissionsSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionsSetResponse.ProtoReflect.Descriptor instead.
func (*RolePermissionsSetResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{16}
}

func (x *RolePermissionsSetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AccountRoleGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId"`
	ScopeType     string                 `protobuf:"bytes,3,opt,name=scopeType,proto3" json:"scopeType"`
	ScopeId       int64                  `protobuf:"varint,4,opt,name=scopeId,proto3" json:"scopeId"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expiresAt,proto3" json:"expiresAt"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRoleGrantRequest) Reset() {
	*x = AccountRoleGrantRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRoleGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRoleGrantRequest) ProtoMessage() {}

func (x *AccountRoleGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRoleGrantRequest.ProtoReflect.Descriptor instead.
func (*AccountRoleGrantRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{17}
}

func (x *AccountRoleGrantRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountRoleGrantRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AccountRoleGrantRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *AccountRoleGrantRequest) GetScopeId() int64 {
	if x != nil {
		return x.ScopeId
	}
	return 0
}

func (x *AccountRoleGrantRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AccountRoleGrantRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type AccountRoleGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRoleGrantResponse) Reset() {
	*x = AccountRoleGrantResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRoleGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRoleGrantResponse) ProtoMessage() {}

func (x *AccountRoleGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRoleGrantResponse.ProtoReflect.Descriptor instead.
func (*AccountRoleGrantResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{18}
}

func (x *AccountRoleGrantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AccountRoleRevokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 授权绑定ID @gotags: path:"bindingId,required"
	BindingId     int64  `protobuf:"varint,1,opt,name=bindingId,proto3" json:"bindingId" path:"bindingId,required"`
	Remark        string `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRoleRevokeRequest) Reset() {
	*x = AccountRoleRevokeRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRoleRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRoleRevokeRequest) ProtoMessage() {}

func (x *AccountRoleRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRoleRevokeRequest.ProtoReflect.Descriptor instead.
func (*AccountRoleRevokeRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{19}
}

func (x *AccountRoleRevokeRequest) GetBindingId() int64 {
	if x != nil {
		return x.BindingId
	}
	return 0
}

func (x *AccountRoleRevokeRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type AccountRoleRevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRoleRevokeResponse) Reset() {
	*x = AccountRoleRevokeResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRoleRevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRoleRevokeResponse) ProtoMessage() {}

func (x *AccountRoleRevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRoleRevokeResponse.ProtoReflect.Descriptor instead.
func (*AccountRoleRevokeResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{20}
}

func (x *AccountRoleRevokeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AccountRoleBindingListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 账号ID @gotags: query:"accountId"
	AccountId int64 `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId" query:"accountId"`
	// 作用域类型 @gotags: query:"scopeType"
	ScopeType string `protobuf:"bytes,2,opt,name=scopeType,proto3" json:"scopeType" query:"scopeType"`
	// 作用域ID @gotags: query:"scopeId"
	ScopeId int64 `protobuf:"varint,3,opt,name=scopeId,proto3" json:"scopeId" query:"scopeId"`
	// 是否仅激活授权 @gotags: query:"onlyActive"
	OnlyActive bool `protobuf:"varint,4,opt,name=onlyActive,proto3" json:"onlyActive" query:"onlyActive"`
	// 页码 @gotags: query:"page"
	Page int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page" query:"page"`
	// 每页条数 @gotags: query:"pageSize"
	PageSize      int32 `protobuf:"varint,6,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRoleBindingListRequest) Reset() {
	*x = AccountRoleBindingListRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRoleBindingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRoleBindingListRequest) ProtoMessage() {}

func (x *AccountRoleBindingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRoleBindingListRequest.ProtoReflect.Descriptor instead.
func (*AccountRoleBindingListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{21}
}

func (x *AccountRoleBindingListRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountRoleBindingListRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *AccountRoleBindingListRequest) GetScopeId() int64 {
	if x != nil {
		return x.ScopeId
	}
	return 0
}

func (x *AccountRoleBindingListRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

func (x *AccountRoleBindingListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AccountRoleBindingListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AccountRoleBindingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BindingId     int64                  `protobuf:"varint,1,opt,name=bindingId,proto3" json:"bindingId"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId"`
	RoleId        int64                  `protobuf:"varint,3,opt,name=roleId,proto3" json:"roleId"`
	RoleCode      string                 `protobuf:"bytes,4,opt,name=roleCode,proto3" json:"roleCode"`
	RoleName      string                 `protobuf:"bytes,5,opt,name=roleName,proto3" json:"roleName"`
	ScopeType     string                 `protobuf:"bytes,6,opt,name=scopeType,proto3" json:"scopeType"`
	ScopeId       int64                  `protobuf:"varint,7,opt,name=scopeId,proto3" json:"scopeId"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status"`
	GrantedBy     int64                  `protobuf:"varint,9,opt,name=grantedBy,proto3" json:"grantedBy"`
	ExpiresAt     string                 `protobuf:"bytes,10,opt,name=expiresAt,proto3" json:"expiresAt"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRoleBindingInfo) Reset() {
	*x = AccountRoleBindingInfo{}
	mi := &file_internal_api_authz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRoleBindingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRoleBindingInfo) ProtoMessage() {}

func (x *AccountRoleBindingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRoleBindingInfo.ProtoReflect.Descriptor instead.
func (*AccountRoleBindingInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{22}
}

func (x *AccountRoleBindingInfo) GetBindingId() int64 {
	if x != nil {
		return x.BindingId
	}
	return 0
}

func (x *AccountRoleBindingInfo) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountRoleBindingInfo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AccountRoleBindingInfo) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *AccountRoleBindingInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *AccountRoleBindingInfo) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *AccountRoleBindingInfo) GetScopeId() int64 {
	if x != nil {
		return x.ScopeId
	}
	return 0
}

func (x *AccountRoleBindingInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AccountRoleBindingInfo) GetGrantedBy() int64 {
	if x != nil {
		return x.GrantedBy
	}
	return 0
}

func (x *AccountRoleBindingInfo) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AccountRoleBindingInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccountRoleBindingInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AccountRoleBindingListResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Total         int32                     `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	List          []*AccountRoleBindingInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRoleBindingListResponse) Reset() {
	*x = AccountRoleBindingListResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRoleBindingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRoleBindingListResponse) ProtoMessage() {}

func (x *AccountRoleBindingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRoleBindingListResponse.ProtoReflect.Descriptor instead.
func (*AccountRoleBindingListResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{23}
}

func (x *AccountRoleBindingListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AccountRoleBindingListResponse) GetList() []*AccountRoleBindingInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type MyAuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyAuthorizationRequest) Reset() {
	*x = MyAuthorizationRequest{}
	mi := &file_internal_api_authz_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyAuthorizationRequest) ProtoMessage() {}

func (x *MyAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*MyAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{24}
}

type MyPermissionScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action"`
	ScopeType     string                 `protobuf:"bytes,3,opt,name=scopeType,proto3" json:"scopeType"`
	ScopeId       int64                  `protobuf:"varint,4,opt,name=scopeId,proto3" json:"scopeId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyPermissionScope) Reset() {
	*x = MyPermissionScope{}
	mi := &file_internal_api_authz_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyPermissionScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyPermissionScope) ProtoMessage() {}

func (x *MyPermissionScope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyPermissionScope.ProtoReflect.Descriptor instead.
func (*MyPermissionScope) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{25}
}

func (x *MyPermissionScope) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *MyPermissionScope) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MyPermissionScope) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *MyPermissionScope) GetScopeId() int64 {
	if x != nil {
		return x.ScopeId
	}
	return 0
}

type MyAuthorizationResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	AccountId     int64                     `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId"`
	Roles         []*AccountRoleBindingInfo `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles"`
	Permissions   []*MyPermissionScope      `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyAuthorizationResponse) Reset() {
	*x = MyAuthorizationResponse{}
	mi := &file_internal_api_authz_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyAuthorizationResponse) ProtoMessage() {}

func (x *MyAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_authz_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*MyAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_authz_proto_rawDescGZIP(), []int{26}
}

func (x *MyAuthorizationResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *MyAuthorizationResponse) GetRoles() []*AccountRoleBindingInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *MyAuthorizationResponse) GetPermissions() []*MyPermissionScope {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_internal_api_authz_proto protoreflect.FileDescriptor

const file_internal_api_authz_proto_rawDesc = "" +
	"\n" +
	"\x18internal/api/authz.proto\x12\x05authz\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"\xc8\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\broleCode\x18\x02 \x01(\tR\broleCode\x12\x1a\n" +
	"\broleName\x18\x03 \x01(\tR\broleName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\tR\tupdatedAt\"\x85\x01\n" +
	"\x0fRoleListRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12(\n" +
	"\x0fincludeDisabled\x18\x02 \x01(\bR\x0fincludeDisabled\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\"M\n" +
	"\x10RoleListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12#\n" +
	"\x04list\x18\x02 \x03(\v2\x0f.authz.RoleInfoR\x04list\"m\n" +
	"\x11RoleCreateRequest\x12\x1a\n" +
	"\broleCode\x18\x01 \x01(\tR\broleCode\x12\x1a\n" +
	"\broleName\x18\x02 \x01(\tR\broleName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"$\n" +
	"\x12RoleCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"a\n" +
	"\x11RoleUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\broleName\x18\x02 \x01(\tR\broleName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\".\n" +
	"\x12RoleUpdateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"A\n" +
	"\x17RoleStatusUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"4\n" +
	"\x18RoleStatusUpdateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8e\x01\n" +
	"\x0ePermissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"S\n" +
	"\x15PermissionListRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12 \n" +
	"\vonlyEnabled\x18\x02 \x01(\bR\vonlyEnabled\"C\n" +
	"\x16PermissionListResponse\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.authz.PermissionInfoR\x04list\"0\n" +
	"\x16RolePermissionsRequest\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\"\x8e\x01\n" +
	"\x12RolePermissionItem\x12\"\n" +
	"\fpermissionId\x18\x01 \x01(\x03R\fpermissionId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"n\n" +
	"\x17RolePermissionsResponse\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\x12;\n" +
	"\vpermissions\x18\x02 \x03(\v2\x19.authz.RolePermissionItemR\vpermissions\"Y\n" +
	"\x19RolePermissionsSetRequest\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\x12$\n" +
	"\rpermissionIds\x18\x02 \x03(\x03R\rpermissionIds\"6\n" +
	"\x1aRolePermissionsSetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xbd\x01\n" +
	"\x17AccountRoleGrantRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\x16\n" +
	"\x06roleId\x18\x02 \x01(\x03R\x06roleId\x12\x1c\n" +
	"\tscopeType\x18\x03 \x01(\tR\tscopeType\x12\x18\n" +
	"\ascopeId\x18\x04 \x01(\x03R\ascopeId\x12\x1c\n" +
	"\texpiresAt\x18\x05 \x01(\tR\texpiresAt\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"4\n" +
	"\x18AccountRoleGrantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"P\n" +
	"\x18AccountRoleRevokeRequest\x12\x1c\n" +
	"\tbindingId\x18\x01 \x01(\x03R\tbindingId\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\"5\n" +
	"\x19AccountRoleRevokeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc5\x01\n" +
	"\x1dAccountRoleBindingListRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\x1c\n" +
	"\tscopeType\x18\x02 \x01(\tR\tscopeType\x12\x18\n" +
	"\ascopeId\x18\x03 \x01(\x03R\ascopeId\x12\x1e\n" +
	"\n" +
	"onlyActive\x18\x04 \x01(\bR\n" +
	"onlyActive\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x06 \x01(\x05R\bpageSize\"\xec\x02\n" +
	"\x16AccountRoleBindingInfo\x12\x1c\n" +
	"\tbindingId\x18\x01 \x01(\x03R\tbindingId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x16\n" +
	"\x06roleId\x18\x03 \x01(\x03R\x06roleId\x12\x1a\n" +
	"\broleCode\x18\x04 \x01(\tR\broleCode\x12\x1a\n" +
	"\broleName\x18\x05 \x01(\tR\broleName\x12\x1c\n" +
	"\tscopeType\x18\x06 \x01(\tR\tscopeType\x12\x18\n" +
	"\ascopeId\x18\a \x01(\x03R\ascopeId\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1c\n" +
	"\tgrantedBy\x18\t \x01(\x03R\tgrantedBy\x12\x1c\n" +
	"\texpiresAt\x18\n" +
	" \x01(\tR\texpiresAt\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\tR\tupdatedAt\"i\n" +
	"\x1eAccountRoleBindingListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x121\n" +
	"\x04list\x18\x02 \x03(\v2\x1d.authz.AccountRoleBindingInfoR\x04list\"\x18\n" +
	"\x16MyAuthorizationRequest\"\x7f\n" +
	"\x11MyPermissionScope\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1c\n" +
	"\tscopeType\x18\x03 \x01(\tR\tscopeType\x12\x18\n" +
	"\ascopeId\x18\x04 \x01(\x03R\ascopeId\"\xa8\x01\n" +
	"\x17MyAuthorizationResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x123\n" +
	"\x05roles\x18\x02 \x03(\v2\x1d.authz.AccountRoleBindingInfoR\x05roles\x12:\n" +
	"\vpermissions\x18\x03 \x03(\v2\x18.authz.MyPermissionScopeR\vpermissions2\x9d\n" +
	"\n" +
	"\fAuthzService\x12V\n" +
	"\tListRoles\x12\x16.authz.RoleListRequest\x1a\x17.authz.RoleListResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/authz/roles\x12^\n" +
	"\n" +
	"CreateRole\x12\x18.authz.RoleCreateRequest\x1a\x19.authz.RoleCreateResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/authz/roles\x12c\n" +
	"\n" +
	"UpdateRole\x12\x18.authz.RoleUpdateRequest\x1a\x19.authz.RoleUpdateResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/authz/roles/{id}\x12|\n" +
	"\x10UpdateRoleStatus\x12\x1e.authz.RoleStatusUpdateRequest\x1a\x1f.authz.RoleStatusUpdateResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/authz/roles/{id}/status\x12n\n" +
	"\x0fListPermissions\x12\x1c.authz.PermissionListRequest\x1a\x1d.authz.PermissionListResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/authz/permissions\x12\x82\x01\n" +
	"\x12GetRolePermissions\x12\x1d.authz.RolePermissionsRequest\x1a\x1e.authz.RolePermissionsResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/authz/roles/{roleId}/permissions\x12\x8f\x01\n" +
	"\x12SetRolePermissions\x12 .authz.RolePermissionsSetRequest\x1a!.authz.RolePermissionsSetResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/authz/roles/{roleId}/permissions/set\x12j\n" +
	"\tGrantRole\x12\x1e.authz.AccountRoleGrantRequest\x1a\x1f.authz.AccountRoleGrantResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/authz/grants\x12\x80\x01\n" +
	"\n" +
	"RevokeRole\x12\x1f.authz.AccountRoleRevokeRequest\x1a .authz.AccountRoleRevokeResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/authz/grants/{bindingId}/revoke\x12\x81\x01\n" +
	"\x17ListAccountRoleBindings\x12$.authz.AccountRoleBindingListRequest\x1a%.authz.AccountRoleBindingListResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/authz/grants\x12g\n" +
	"\x0fMyAuthorization\x12\x1d.authz.MyAuthorizationRequest\x1a\x1e.authz.MyAuthorizationResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/authz/me\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_authz_proto_rawDescOnce sync.Once
	file_internal_api_authz_proto_rawDescData []byte
)

func file_internal_api_authz_proto_rawDescGZIP() []byte {
	file_internal_api_authz_proto_rawDescOnce.Do(func() {
		file_internal_api_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_authz_proto_rawDesc), len(file_internal_api_authz_proto_rawDesc)))
	})
	return file_internal_api_authz_proto_rawDescData
}

var file_internal_api_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_internal_api_authz_proto_goTypes = []any{
	(*RoleInfo)(nil),                       // 0: authz.RoleInfo
	(*RoleListRequest)(nil),                // 1: authz.RoleListRequest
	(*RoleListResponse)(nil),               // 2: authz.RoleListResponse
	(*RoleCreateRequest)(nil),              // 3: authz.RoleCreateRequest
	(*RoleCreateResponse)(nil),             // 4: authz.RoleCreateResponse
	(*RoleUpdateRequest)(nil),              // 5: authz.RoleUpdateRequest
	(*RoleUpdateResponse)(nil),             // 6: authz.RoleUpdateResponse
	(*RoleStatusUpdateRequest)(nil),        // 7: authz.RoleStatusUpdateRequest
	(*RoleStatusUpdateResponse)(nil),       // 8: authz.RoleStatusUpdateResponse
	(*PermissionInfo)(nil),                 // 9: authz.PermissionInfo
	(*PermissionListRequest)(nil),          // 10: authz.PermissionListRequest
	(*PermissionListResponse)(nil),         // 11: authz.PermissionListResponse
	(*RolePermissionsRequest)(nil),         // 12: authz.RolePermissionsRequest
	(*RolePermissionItem)(nil),             // 13: authz.RolePermissionItem
	(*RolePermissionsResponse)(nil),        // 14: authz.RolePermissionsResponse
	(*RolePermissionsSetRequest)(nil),      // 15: authz.RolePermissionsSetRequest
	(*RolePermissionsSetResponse)(nil),     // 16: authz.RolePermissionsSetResponse
	(*AccountRoleGrantRequest)(nil),        // 17: authz.AccountRoleGrantRequest
	(*AccountRoleGrantResponse)(nil),       // 18: authz.AccountRoleGrantResponse
	(*AccountRoleRevokeRequest)(nil),       // 19: authz.AccountRoleRevokeRequest
	(*AccountRoleRevokeResponse)(nil),      // 20: authz.AccountRoleRevokeResponse
	(*AccountRoleBindingListRequest)(nil),  // 21: authz.AccountRoleBindingListRequest
	(*AccountRoleBindingInfo)(nil),         // 22: authz.AccountRoleBindingInfo
	(*AccountRoleBindingListResponse)(nil), // 23: authz.AccountRoleBindingListResponse
	(*MyAuthorizationRequest)(nil),         // 24: authz.MyAuthorizationRequest
	(*MyPermissionScope)(nil),              // 25: authz.MyPermissionScope
	(*MyAuthorizationResponse)(nil),        // 26: authz.MyAuthorizationResponse
}
var file_internal_api_authz_proto_depIdxs = []int32{
	0,  // 0: authz.RoleListResponse.list:type_name -> authz.RoleInfo
	9,  // 1: authz.PermissionListResponse.list:type_name -> authz.PermissionInfo
	13, // 2: authz.RolePermissionsResponse.permissions:type_name -> authz.RolePermissionItem
	22, // 3: authz.AccountRoleBindingListResponse.list:type_name -> authz.AccountRoleBindingInfo
	22, // 4: authz.MyAuthorizationResponse.roles:type_name -> authz.AccountRoleBindingInfo
	25, // 5: authz.MyAuthorizationResponse.permissions:type_name -> authz.MyPermissionScope
	1,  // 6: authz.AuthzService.ListRoles:input_type -> authz.RoleListRequest
	3,  // 7: authz.AuthzService.CreateRole:input_type -> authz.RoleCreateRequest
	5,  // 8: authz.AuthzService.UpdateRole:input_type -> authz.RoleUpdateRequest
	7,  // 9: authz.AuthzService.UpdateRoleStatus:input_type -> authz.RoleStatusUpdateRequest
	10, // 10: authz.AuthzService.ListPermissions:input_type -> authz.PermissionListRequest
	12, // 11: authz.AuthzService.GetRolePermissions:input_type -> authz.RolePermissionsRequest
	15, // 12: authz.AuthzService.SetRolePermissions:input_type -> authz.RolePermissionsSetRequest
	17, // 13: authz.AuthzService.GrantRole:input_type -> authz.AccountRoleGrantRequest
	19, // 14: authz.AuthzService.RevokeRole:input_type -> authz.AccountRoleRevokeRequest
	21, // 15: authz.AuthzService.ListAccountRoleBindings:input_type -> authz.AccountRoleBindingListRequest
	24, // 16: authz.AuthzService.MyAuthorization:input_type -> authz.MyAuthorizationRequest
	2,  // 17: authz.AuthzService.ListRoles:output_type -> authz.RoleListResponse
	4,  // 18: authz.AuthzService.CreateRole:output_type -> authz.RoleCreateResponse
	6,  // 19: authz.AuthzService.UpdateRole:output_type -> authz.RoleUpdateResponse
	8,  // 20: authz.AuthzService.UpdateRoleStatus:output_type -> authz.RoleStatusUpdateResponse
	11, // 21: authz.AuthzService.ListPermissions:output_type -> authz.PermissionListResponse
	14, // 22: authz.AuthzService.GetRolePermissions:output_type -> authz.RolePermissionsResponse
	16, // 23: authz.AuthzService.SetRolePermissions:output_type -> authz.RolePermissionsSetResponse
	18, // 24: authz.AuthzService.GrantRole:output_type -> authz.AccountRoleGrantResponse
	20, // 25: authz.AuthzService.RevokeRole:output_type -> authz.AccountRoleRevokeResponse
	23, // 26: authz.AuthzService.ListAccountRoleBindings:output_type -> authz.AccountRoleBindingListResponse
	26, // 27: authz.AuthzService.MyAuthorization:output_type -> authz.MyAuthorizationResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_api_authz_proto_init() }
func file_internal_api_authz_proto_init() {
	if File_internal_api_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_authz_proto_rawDesc), len(file_internal_api_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_authz_proto_goTypes,
		DependencyIndexes: file_internal_api_authz_proto_depIdxs,
		MessageInfos:      file_internal_api_authz_proto_msgTypes,
	}.Build()
	File_internal_api_authz_proto = out.File
	file_internal_api_authz_proto_goTypes = nil
	file_internal_api_authz_proto_depIdxs = nil
}
