// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.0
// source: internal/api/membership.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VolunteerJoinRequest 志愿者加入组织请求
type VolunteerJoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 志愿者ID 必填 @gotags: json:"volunteerId,required"
	VolunteerId int64 `protobuf:"varint,1,opt,name=volunteerId,proto3" json:"volunteerId,required"`
	// 组织ID 必填 @gotags: json:"organizationId,required"
	OrganizationId int64 `protobuf:"varint,2,opt,name=organizationId,proto3" json:"organizationId,required"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VolunteerJoinRequest) Reset() {
	*x = VolunteerJoinRequest{}
	mi := &file_internal_api_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerJoinRequest) ProtoMessage() {}

func (x *VolunteerJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerJoinRequest.ProtoReflect.Descriptor instead.
func (*VolunteerJoinRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{0}
}

func (x *VolunteerJoinRequest) GetVolunteerId() int64 {
	if x != nil {
		return x.VolunteerId
	}
	return 0
}

func (x *VolunteerJoinRequest) GetOrganizationId() int64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

// VolunteerJoinResponse 志愿者加入组织响应
type VolunteerJoinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成员关系ID
	MembershipId int64 `protobuf:"varint,1,opt,name=membershipId,proto3" json:"membershipId"`
	// 状态
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status"`
	// 消息
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerJoinResponse) Reset() {
	*x = VolunteerJoinResponse{}
	mi := &file_internal_api_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerJoinResponse) ProtoMessage() {}

func (x *VolunteerJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerJoinResponse.ProtoReflect.Descriptor instead.
func (*VolunteerJoinResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{1}
}

func (x *VolunteerJoinResponse) GetMembershipId() int64 {
	if x != nil {
		return x.MembershipId
	}
	return 0
}

func (x *VolunteerJoinResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VolunteerJoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// VolunteerLeaveRequest 志愿者退出组织请求
type VolunteerLeaveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成员关系ID 必填 @gotags: json:"membershipId,required"
	MembershipId int64 `protobuf:"varint,1,opt,name=membershipId,proto3" json:"membershipId,required"`
	// 退出原因 可选 @gotags: json:"reason"
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerLeaveRequest) Reset() {
	*x = VolunteerLeaveRequest{}
	mi := &file_internal_api_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerLeaveRequest) ProtoMessage() {}

func (x *VolunteerLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerLeaveRequest.ProtoReflect.Descriptor instead.
func (*VolunteerLeaveRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{2}
}

func (x *VolunteerLeaveRequest) GetMembershipId() int64 {
	if x != nil {
		return x.MembershipId
	}
	return 0
}

func (x *VolunteerLeaveRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// VolunteerLeaveResponse 志愿者退出组织响应
type VolunteerLeaveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerLeaveResponse) Reset() {
	*x = VolunteerLeaveResponse{}
	mi := &file_internal_api_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerLeaveResponse) ProtoMessage() {}

func (x *VolunteerLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerLeaveResponse.ProtoReflect.Descriptor instead.
func (*VolunteerLeaveResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{3}
}

func (x *VolunteerLeaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// OrganizationMembersRequest 获取组织成员请求
type OrganizationMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织ID 必填 @gotags: path:"organizationId,required"
	OrganizationId int64 `protobuf:"varint,1,opt,name=organizationId,proto3" json:"organizationId" path:"organizationId,required"`
	// 状态筛选 可选 @gotags: query:"status"
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status" query:"status"`
	// 角色筛选 可选 @gotags: query:"role"
	Role int32 `protobuf:"varint,3,opt,name=role,proto3" json:"role" query:"role"`
	// 搜索关键字 可选 @gotags: query:"keyword"
	Keyword string `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword" query:"keyword"`
	// 页码 必填 @gotags: query:"page,required"
	Page int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page" query:"page,required"`
	// 页大小 必填 @gotags: query:"pageSize,required"
	PageSize      int32 `protobuf:"varint,6,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMembersRequest) Reset() {
	*x = OrganizationMembersRequest{}
	mi := &file_internal_api_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMembersRequest) ProtoMessage() {}

func (x *OrganizationMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMembersRequest.ProtoReflect.Descriptor instead.
func (*OrganizationMembersRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{4}
}

func (x *OrganizationMembersRequest) GetOrganizationId() int64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *OrganizationMembersRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrganizationMembersRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *OrganizationMembersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *OrganizationMembersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrganizationMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// OrganizationMembersResponse 获取组织成员响应
type OrganizationMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	List          []*MemberInfo          `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMembersResponse) Reset() {
	*x = OrganizationMembersResponse{}
	mi := &file_internal_api_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMembersResponse) ProtoMessage() {}

func (x *OrganizationMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMembersResponse.ProtoReflect.Descriptor instead.
func (*OrganizationMembersResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{5}
}

func (x *OrganizationMembersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrganizationMembersResponse) GetList() []*MemberInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// VolunteerOrganizationsRequest 查询志愿者加入的组织请求
type VolunteerOrganizationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 志愿者ID 必填 @gotags: path:"volunteerId,required"
	VolunteerId int64 `protobuf:"varint,1,opt,name=volunteerId,proto3" json:"volunteerId" path:"volunteerId,required"`
	// 状态筛选 可选 @gotags: query:"status"
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status" query:"status"`
	// 页码 必填 @gotags: query:"page,required"
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page" query:"page,required"`
	// 页大小 必填 @gotags: query:"pageSize,required"
	PageSize      int32 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerOrganizationsRequest) Reset() {
	*x = VolunteerOrganizationsRequest{}
	mi := &file_internal_api_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerOrganizationsRequest) ProtoMessage() {}

func (x *VolunteerOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*VolunteerOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{6}
}

func (x *VolunteerOrganizationsRequest) GetVolunteerId() int64 {
	if x != nil {
		return x.VolunteerId
	}
	return 0
}

func (x *VolunteerOrganizationsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VolunteerOrganizationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *VolunteerOrganizationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// VolunteerOrganizationsResponse 查询志愿者加入的组织响应
type VolunteerOrganizationsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Total         int32                     `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	List          []*OrganizationMemberInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerOrganizationsResponse) Reset() {
	*x = VolunteerOrganizationsResponse{}
	mi := &file_internal_api_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerOrganizationsResponse) ProtoMessage() {}

func (x *VolunteerOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*VolunteerOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{7}
}

func (x *VolunteerOrganizationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *VolunteerOrganizationsResponse) GetList() []*OrganizationMemberInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// MemberStatusUpdateRequest 更新成员状态请求
type MemberStatusUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织管理者ID 必填 @gotags: json:"accountId,required"
	AccountId int64 `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,required"`
	// 成员关系ID 必填 @gotags: json:"membershipId,required"
	MembershipId int64 `protobuf:"varint,2,opt,name=membershipId,proto3" json:"membershipId,required"`
	// 成员状态 必填 @gotags: json:"status,required"
	Status int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,required"`
	// 审核意见 可选 @gotags: json:"reviewComment"
	ReviewComment string `protobuf:"bytes,4,opt,name=reviewComment,proto3" json:"reviewComment"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberStatusUpdateRequest) Reset() {
	*x = MemberStatusUpdateRequest{}
	mi := &file_internal_api_membership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberStatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberStatusUpdateRequest) ProtoMessage() {}

func (x *MemberStatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberStatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*MemberStatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{8}
}

func (x *MemberStatusUpdateRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *MemberStatusUpdateRequest) GetMembershipId() int64 {
	if x != nil {
		return x.MembershipId
	}
	return 0
}

func (x *MemberStatusUpdateRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MemberStatusUpdateRequest) GetReviewComment() string {
	if x != nil {
		return x.ReviewComment
	}
	return ""
}

// MemberStatusUpdateResponse 更新成员状态响应
type MemberStatusUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberStatusUpdateResponse) Reset() {
	*x = MemberStatusUpdateResponse{}
	mi := &file_internal_api_membership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberStatusUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberStatusUpdateResponse) ProtoMessage() {}

func (x *MemberStatusUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberStatusUpdateResponse.ProtoReflect.Descriptor instead.
func (*MemberStatusUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{9}
}

func (x *MemberStatusUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MembershipStatsRequest 成员统计请求
type MembershipStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织ID 可选 @gotags: query:"organizationId"
	OrganizationId int64 `protobuf:"varint,1,opt,name=organizationId,proto3" json:"organizationId" query:"organizationId"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MembershipStatsRequest) Reset() {
	*x = MembershipStatsRequest{}
	mi := &file_internal_api_membership_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipStatsRequest) ProtoMessage() {}

func (x *MembershipStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipStatsRequest.ProtoReflect.Descriptor instead.
func (*MembershipStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{10}
}

func (x *MembershipStatsRequest) GetOrganizationId() int64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

// MembershipStatsResponse 成员统计响应
type MembershipStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 待审核成员数量
	PendingCount int64 `protobuf:"varint,1,opt,name=pendingCount,proto3" json:"pendingCount"`
	// 活跃成员数量
	ActiveCount int64 `protobuf:"varint,2,opt,name=activeCount,proto3" json:"activeCount"`
	// 非活跃成员数量
	InactiveCount int64 `protobuf:"varint,3,opt,name=inactiveCount,proto3" json:"inactiveCount"`
	// 暂停成员数量
	SuspendedCount int64 `protobuf:"varint,4,opt,name=suspendedCount,proto3" json:"suspendedCount"`
	// 总成员数量
	TotalCount    int64 `protobuf:"varint,5,opt,name=totalCount,proto3" json:"totalCount"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipStatsResponse) Reset() {
	*x = MembershipStatsResponse{}
	mi := &file_internal_api_membership_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipStatsResponse) ProtoMessage() {}

func (x *MembershipStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipStatsResponse.ProtoReflect.Descriptor instead.
func (*MembershipStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{11}
}

func (x *MembershipStatsResponse) GetPendingCount() int64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *MembershipStatsResponse) GetActiveCount() int64 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

func (x *MembershipStatsResponse) GetInactiveCount() int64 {
	if x != nil {
		return x.InactiveCount
	}
	return 0
}

func (x *MembershipStatsResponse) GetSuspendedCount() int64 {
	if x != nil {
		return x.SuspendedCount
	}
	return 0
}

func (x *MembershipStatsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// MemberInfo 成员信息
type MemberInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成员关系ID
	MembershipId int64 `protobuf:"varint,1,opt,name=membershipId,proto3" json:"membershipId"`
	// 志愿者ID
	VolunteerId int64 `protobuf:"varint,2,opt,name=volunteerId,proto3" json:"volunteerId"`
	// 志愿者姓名
	VolunteerName string `protobuf:"bytes,3,opt,name=volunteerName,proto3" json:"volunteerName"`
	// 志愿者编号
	VolunteerCode string `protobuf:"bytes,4,opt,name=volunteerCode,proto3" json:"volunteerCode"`
	// 组织ID
	OrganizationId int64 `protobuf:"varint,5,opt,name=organizationId,proto3" json:"organizationId"`
	// 组织名称
	OrganizationName string `protobuf:"bytes,6,opt,name=organizationName,proto3" json:"organizationName"`
	// 成员状态
	Status int32 `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	// 成员角色
	Role int32 `protobuf:"varint,8,opt,name=role,proto3" json:"role"`
	// 申请职位
	Position string `protobuf:"bytes,9,opt,name=position,proto3" json:"position"`
	// 申请动机
	Motivation string `protobuf:"bytes,10,opt,name=motivation,proto3" json:"motivation"`
	// 期望工作时间
	ExpectedHours string `protobuf:"bytes,11,opt,name=expectedHours,proto3" json:"expectedHours"`
	// 加入时间
	JoinDate string `protobuf:"bytes,12,opt,name=joinDate,proto3" json:"joinDate"`
	// 审核时间
	ReviewDate string `protobuf:"bytes,13,opt,name=reviewDate,proto3" json:"reviewDate"`
	// 审核意见
	ReviewComment string `protobuf:"bytes,14,opt,name=reviewComment,proto3" json:"reviewComment"`
	// 离开时间
	LeaveDate string `protobuf:"bytes,15,opt,name=leaveDate,proto3" json:"leaveDate"`
	// 离开原因
	LeaveReason string `protobuf:"bytes,16,opt,name=leaveReason,proto3" json:"leaveReason"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,17,opt,name=createdAt,proto3" json:"createdAt"`
	// 更新时间
	UpdatedAt     string `protobuf:"bytes,18,opt,name=updatedAt,proto3" json:"updatedAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_internal_api_membership_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{12}
}

func (x *MemberInfo) GetMembershipId() int64 {
	if x != nil {
		return x.MembershipId
	}
	return 0
}

func (x *MemberInfo) GetVolunteerId() int64 {
	if x != nil {
		return x.VolunteerId
	}
	return 0
}

func (x *MemberInfo) GetVolunteerName() string {
	if x != nil {
		return x.VolunteerName
	}
	return ""
}

func (x *MemberInfo) GetVolunteerCode() string {
	if x != nil {
		return x.VolunteerCode
	}
	return ""
}

func (x *MemberInfo) GetOrganizationId() int64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *MemberInfo) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *MemberInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MemberInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *MemberInfo) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *MemberInfo) GetMotivation() string {
	if x != nil {
		return x.Motivation
	}
	return ""
}

func (x *MemberInfo) GetExpectedHours() string {
	if x != nil {
		return x.ExpectedHours
	}
	return ""
}

func (x *MemberInfo) GetJoinDate() string {
	if x != nil {
		return x.JoinDate
	}
	return ""
}

func (x *MemberInfo) GetReviewDate() string {
	if x != nil {
		return x.ReviewDate
	}
	return ""
}

func (x *MemberInfo) GetReviewComment() string {
	if x != nil {
		return x.ReviewComment
	}
	return ""
}

func (x *MemberInfo) GetLeaveDate() string {
	if x != nil {
		return x.LeaveDate
	}
	return ""
}

func (x *MemberInfo) GetLeaveReason() string {
	if x != nil {
		return x.LeaveReason
	}
	return ""
}

func (x *MemberInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MemberInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// OrganizationMemberInfo 组织成员信息（用于志愿者视角）
type OrganizationMemberInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成员关系ID
	MembershipId int64 `protobuf:"varint,1,opt,name=membershipId,proto3" json:"membershipId"`
	// 组织ID
	OrganizationId int64 `protobuf:"varint,2,opt,name=organizationId,proto3" json:"organizationId"`
	// 组织名称
	OrganizationName string `protobuf:"bytes,3,opt,name=organizationName,proto3" json:"organizationName"`
	// 组织代码
	OrganizationCode string `protobuf:"bytes,4,opt,name=organizationCode,proto3" json:"organizationCode"`
	// 成员状态
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	// 成员角色
	Role int32 `protobuf:"varint,6,opt,name=role,proto3" json:"role"`
	// 申请职位
	Position string `protobuf:"bytes,7,opt,name=position,proto3" json:"position"`
	// 加入时间
	JoinDate string `protobuf:"bytes,8,opt,name=joinDate,proto3" json:"joinDate"`
	// 审核时间
	ReviewDate string `protobuf:"bytes,9,opt,name=reviewDate,proto3" json:"reviewDate"`
	// 审核意见
	ReviewComment string `protobuf:"bytes,10,opt,name=reviewComment,proto3" json:"reviewComment"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt"`
	// 更新时间
	UpdatedAt     string `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMemberInfo) Reset() {
	*x = OrganizationMemberInfo{}
	mi := &file_internal_api_membership_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMemberInfo) ProtoMessage() {}

func (x *OrganizationMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_membership_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMemberInfo.ProtoReflect.Descriptor instead.
func (*OrganizationMemberInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_membership_proto_rawDescGZIP(), []int{13}
}

func (x *OrganizationMemberInfo) GetMembershipId() int64 {
	if x != nil {
		return x.MembershipId
	}
	return 0
}

func (x *OrganizationMemberInfo) GetOrganizationId() int64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *OrganizationMemberInfo) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *OrganizationMemberInfo) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *OrganizationMemberInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrganizationMemberInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *OrganizationMemberInfo) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *OrganizationMemberInfo) GetJoinDate() string {
	if x != nil {
		return x.JoinDate
	}
	return ""
}

func (x *OrganizationMemberInfo) GetReviewDate() string {
	if x != nil {
		return x.ReviewDate
	}
	return ""
}

func (x *OrganizationMemberInfo) GetReviewComment() string {
	if x != nil {
		return x.ReviewComment
	}
	return ""
}

func (x *OrganizationMemberInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrganizationMemberInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_internal_api_membership_proto protoreflect.FileDescriptor

const file_internal_api_membership_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/api/membership.proto\x12\n" +
	"membership\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"`\n" +
	"\x14VolunteerJoinRequest\x12 \n" +
	"\vvolunteerId\x18\x01 \x01(\x03R\vvolunteerId\x12&\n" +
	"\x0eorganizationId\x18\x02 \x01(\x03R\x0eorganizationId\"m\n" +
	"\x15VolunteerJoinResponse\x12\"\n" +
	"\fmembershipId\x18\x01 \x01(\x03R\fmembershipId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"S\n" +
	"\x15VolunteerLeaveRequest\x12\"\n" +
	"\fmembershipId\x18\x01 \x01(\x03R\fmembershipId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"2\n" +
	"\x16VolunteerLeaveResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xba\x01\n" +
	"\x1aOrganizationMembersRequest\x12&\n" +
	"\x0eorganizationId\x18\x01 \x01(\x03R\x0eorganizationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x06 \x01(\x05R\bpageSize\"_\n" +
	"\x1bOrganizationMembersResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.membership.MemberInfoR\x04list\"\x89\x01\n" +
	"\x1dVolunteerOrganizationsRequest\x12 \n" +
	"\vvolunteerId\x18\x01 \x01(\x03R\vvolunteerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\"n\n" +
	"\x1eVolunteerOrganizationsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x126\n" +
	"\x04list\x18\x02 \x03(\v2\".membership.OrganizationMemberInfoR\x04list\"\x9b\x01\n" +
	"\x19MemberStatusUpdateRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\"\n" +
	"\fmembershipId\x18\x02 \x01(\x03R\fmembershipId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12$\n" +
	"\rreviewComment\x18\x04 \x01(\tR\rreviewComment\"6\n" +
	"\x1aMemberStatusUpdateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\x16MembershipStatsRequest\x12&\n" +
	"\x0eorganizationId\x18\x01 \x01(\x03R\x0eorganizationId\"\xcd\x01\n" +
	"\x17MembershipStatsResponse\x12\"\n" +
	"\fpendingCount\x18\x01 \x01(\x03R\fpendingCount\x12 \n" +
	"\vactiveCount\x18\x02 \x01(\x03R\vactiveCount\x12$\n" +
	"\rinactiveCount\x18\x03 \x01(\x03R\rinactiveCount\x12&\n" +
	"\x0esuspendedCount\x18\x04 \x01(\x03R\x0esuspendedCount\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x05 \x01(\x03R\n" +
	"totalCount\"\xde\x04\n" +
	"\n" +
	"MemberInfo\x12\"\n" +
	"\fmembershipId\x18\x01 \x01(\x03R\fmembershipId\x12 \n" +
	"\vvolunteerId\x18\x02 \x01(\x03R\vvolunteerId\x12$\n" +
	"\rvolunteerName\x18\x03 \x01(\tR\rvolunteerName\x12$\n" +
	"\rvolunteerCode\x18\x04 \x01(\tR\rvolunteerCode\x12&\n" +
	"\x0eorganizationId\x18\x05 \x01(\x03R\x0eorganizationId\x12*\n" +
	"\x10organizationName\x18\x06 \x01(\tR\x10organizationName\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x12\n" +
	"\x04role\x18\b \x01(\x05R\x04role\x12\x1a\n" +
	"\bposition\x18\t \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"motivation\x18\n" +
	" \x01(\tR\n" +
	"motivation\x12$\n" +
	"\rexpectedHours\x18\v \x01(\tR\rexpectedHours\x12\x1a\n" +
	"\bjoinDate\x18\f \x01(\tR\bjoinDate\x12\x1e\n" +
	"\n" +
	"reviewDate\x18\r \x01(\tR\n" +
	"reviewDate\x12$\n" +
	"\rreviewComment\x18\x0e \x01(\tR\rreviewComment\x12\x1c\n" +
	"\tleaveDate\x18\x0f \x01(\tR\tleaveDate\x12 \n" +
	"\vleaveReason\x18\x10 \x01(\tR\vleaveReason\x12\x1c\n" +
	"\tcreatedAt\x18\x11 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x12 \x01(\tR\tupdatedAt\"\xa2\x03\n" +
	"\x16OrganizationMemberInfo\x12\"\n" +
	"\fmembershipId\x18\x01 \x01(\x03R\fmembershipId\x12&\n" +
	"\x0eorganizationId\x18\x02 \x01(\x03R\x0eorganizationId\x12*\n" +
	"\x10organizationName\x18\x03 \x01(\tR\x10organizationName\x12*\n" +
	"\x10organizationCode\x18\x04 \x01(\tR\x10organizationCode\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x12\n" +
	"\x04role\x18\x06 \x01(\x05R\x04role\x12\x1a\n" +
	"\bposition\x18\a \x01(\tR\bposition\x12\x1a\n" +
	"\bjoinDate\x18\b \x01(\tR\bjoinDate\x12\x1e\n" +
	"\n" +
	"reviewDate\x18\t \x01(\tR\n" +
	"reviewDate\x12$\n" +
	"\rreviewComment\x18\n" +
	" \x01(\tR\rreviewComment\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\tR\tupdatedAt2\x8a\a\n" +
	"\x11MembershipService\x12\x82\x01\n" +
	"\x19VolunteerJoinOrganization\x12 .membership.VolunteerJoinRequest\x1a!.membership.VolunteerJoinResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/memberships/join\x12\x86\x01\n" +
	"\x1aVolunteerLeaveOrganization\x12!.membership.VolunteerLeaveRequest\x1a\".membership.VolunteerLeaveResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/memberships/leave\x12\x9e\x01\n" +
	"\x16GetOrganizationMembers\x12&.membership.OrganizationMembersRequest\x1a'.membership.OrganizationMembersResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/organizations/{organizationId}/members\x12\xa7\x01\n" +
	"\x19GetVolunteerOrganizations\x12).membership.VolunteerOrganizationsRequest\x1a*.membership.VolunteerOrganizationsResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/volunteers/{volunteerId}/organizations\x12\x8e\x01\n" +
	"\x12UpdateMemberStatus\x12%.membership.MemberStatusUpdateRequest\x1a&.membership.MemberStatusUpdateResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/memberships/status/update\x12z\n" +
	"\x0fMembershipStats\x12\".membership.MembershipStatsRequest\x1a#.membership.MembershipStatsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/memberships/stats\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_membership_proto_rawDescOnce sync.Once
	file_internal_api_membership_proto_rawDescData []byte
)

func file_internal_api_membership_proto_rawDescGZIP() []byte {
	file_internal_api_membership_proto_rawDescOnce.Do(func() {
		file_internal_api_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_membership_proto_rawDesc), len(file_internal_api_membership_proto_rawDesc)))
	})
	return file_internal_api_membership_proto_rawDescData
}

var file_internal_api_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_api_membership_proto_goTypes = []any{
	(*VolunteerJoinRequest)(nil),           // 0: membership.VolunteerJoinRequest
	(*VolunteerJoinResponse)(nil),          // 1: membership.VolunteerJoinResponse
	(*VolunteerLeaveRequest)(nil),          // 2: membership.VolunteerLeaveRequest
	(*VolunteerLeaveResponse)(nil),         // 3: membership.VolunteerLeaveResponse
	(*OrganizationMembersRequest)(nil),     // 4: membership.OrganizationMembersRequest
	(*OrganizationMembersResponse)(nil),    // 5: membership.OrganizationMembersResponse
	(*VolunteerOrganizationsRequest)(nil),  // 6: membership.VolunteerOrganizationsRequest
	(*VolunteerOrganizationsResponse)(nil), // 7: membership.VolunteerOrganizationsResponse
	(*MemberStatusUpdateRequest)(nil),      // 8: membership.MemberStatusUpdateRequest
	(*MemberStatusUpdateResponse)(nil),     // 9: membership.MemberStatusUpdateResponse
	(*MembershipStatsRequest)(nil),         // 10: membership.MembershipStatsRequest
	(*MembershipStatsResponse)(nil),        // 11: membership.MembershipStatsResponse
	(*MemberInfo)(nil),                     // 12: membership.MemberInfo
	(*OrganizationMemberInfo)(nil),         // 13: membership.OrganizationMemberInfo
}
var file_internal_api_membership_proto_depIdxs = []int32{
	12, // 0: membership.OrganizationMembersResponse.list:type_name -> membership.MemberInfo
	13, // 1: membership.VolunteerOrganizationsResponse.list:type_name -> membership.OrganizationMemberInfo
	0,  // 2: membership.MembershipService.VolunteerJoinOrganization:input_type -> membership.VolunteerJoinRequest
	2,  // 3: membership.MembershipService.VolunteerLeaveOrganization:input_type -> membership.VolunteerLeaveRequest
	4,  // 4: membership.MembershipService.GetOrganizationMembers:input_type -> membership.OrganizationMembersRequest
	6,  // 5: membership.MembershipService.GetVolunteerOrganizations:input_type -> membership.VolunteerOrganizationsRequest
	8,  // 6: membership.MembershipService.UpdateMemberStatus:input_type -> membership.MemberStatusUpdateRequest
	10, // 7: membership.MembershipService.MembershipStats:input_type -> membership.MembershipStatsRequest
	1,  // 8: membership.MembershipService.VolunteerJoinOrganization:output_type -> membership.VolunteerJoinResponse
	3,  // 9: membership.MembershipService.VolunteerLeaveOrganization:output_type -> membership.VolunteerLeaveResponse
	5,  // 10: membership.MembershipService.GetOrganizationMembers:output_type -> membership.OrganizationMembersResponse
	7,  // 11: membership.MembershipService.GetVolunteerOrganizations:output_type -> membership.VolunteerOrganizationsResponse
	9,  // 12: membership.MembershipService.UpdateMemberStatus:output_type -> membership.MemberStatusUpdateResponse
	11, // 13: membership.MembershipService.MembershipStats:output_type -> membership.MembershipStatsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_api_membership_proto_init() }
func file_internal_api_membership_proto_init() {
	if File_internal_api_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_membership_proto_rawDesc), len(file_internal_api_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_membership_proto_goTypes,
		DependencyIndexes: file_internal_api_membership_proto_depIdxs,
		MessageInfos:      file_internal_api_membership_proto_msgTypes,
	}.Build()
	File_internal_api_membership_proto = out.File
	file_internal_api_membership_proto_goTypes = nil
	file_internal_api_membership_proto_depIdxs = nil
}
