// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.0
// source: internal/api/notification.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationListRequest 获取通知列表请求
type NotificationListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码 可选 @gotags: query:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" query:"page"`
	// 页大小 可选 @gotags: query:"pageSize"
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize"`
	// 仅未读 可选 @gotags: query:"unreadOnly"
	UnreadOnly    bool `protobuf:"varint,3,opt,name=unreadOnly,proto3" json:"unreadOnly" query:"unreadOnly"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationListRequest) Reset() {
	*x = NotificationListRequest{}
	mi := &file_internal_api_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationListRequest) ProtoMessage() {}

func (x *NotificationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationListRequest.ProtoReflect.Descriptor instead.
func (*NotificationListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *NotificationListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *NotificationListRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

// NotificationListResponse 获取通知列表响应
type NotificationListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	// 列表
	List          []*NotificationItem `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationListResponse) Reset() {
	*x = NotificationListResponse{}
	mi := &file_internal_api_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationListResponse) ProtoMessage() {}

func (x *NotificationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationListResponse.ProtoReflect.Descriptor instead.
func (*NotificationListResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NotificationListResponse) GetList() []*NotificationItem {
	if x != nil {
		return x.List
	}
	return nil
}

// NotificationItem 通知列表项
type NotificationItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 收件箱ID（notification_inbox.id）
	InboxId int64 `protobuf:"varint,1,opt,name=inboxId,proto3" json:"inboxId"`
	// 通知ID（notifications.id）
	NotificationId int64 `protobuf:"varint,2,opt,name=notificationId,proto3" json:"notificationId"`
	// 事件类型
	EventType string `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType"`
	// 业务类型
	BizType string `protobuf:"bytes,4,opt,name=bizType,proto3" json:"bizType"`
	// 业务ID
	BizId int64 `protobuf:"varint,5,opt,name=bizId,proto3" json:"bizId"`
	// 标题
	Title string `protobuf:"bytes,6,opt,name=title,proto3" json:"title"`
	// 内容
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content"`
	// 已读状态：0-未读，1-已读
	ReadStatus int32 `protobuf:"varint,8,opt,name=readStatus,proto3" json:"readStatus"`
	// 已读时间
	ReadAt string `protobuf:"bytes,9,opt,name=readAt,proto3" json:"readAt"`
	// 创建时间
	CreatedAt     string `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationItem) Reset() {
	*x = NotificationItem{}
	mi := &file_internal_api_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationItem) ProtoMessage() {}

func (x *NotificationItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationItem.ProtoReflect.Descriptor instead.
func (*NotificationItem) Descriptor() ([]byte, []int) {
	return file_internal_api_notification_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationItem) GetInboxId() int64 {
	if x != nil {
		return x.InboxId
	}
	return 0
}

func (x *NotificationItem) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *NotificationItem) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *NotificationItem) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *NotificationItem) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *NotificationItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationItem) GetReadStatus() int32 {
	if x != nil {
		return x.ReadStatus
	}
	return 0
}

func (x *NotificationItem) GetReadAt() string {
	if x != nil {
		return x.ReadAt
	}
	return ""
}

func (x *NotificationItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// NotificationReadRequest 批量已读请求
type NotificationReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 收件箱ID列表 @gotags: json:"ids,required"
	Ids           []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationReadRequest) Reset() {
	*x = NotificationReadRequest{}
	mi := &file_internal_api_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationReadRequest) ProtoMessage() {}

func (x *NotificationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationReadRequest.ProtoReflect.Descriptor instead.
func (*NotificationReadRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_notification_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationReadRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// NotificationReadResponse 批量已读响应
type NotificationReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成功更新的行数
	Updated       int32 `protobuf:"varint,1,opt,name=updated,proto3" json:"updated"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationReadResponse) Reset() {
	*x = NotificationReadResponse{}
	mi := &file_internal_api_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationReadResponse) ProtoMessage() {}

func (x *NotificationReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationReadResponse.ProtoReflect.Descriptor instead.
func (*NotificationReadResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_notification_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationReadResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

var File_internal_api_notification_proto protoreflect.FileDescriptor

const file_internal_api_notification_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/api/notification.proto\x12\fnotification\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"i\n" +
	"\x17NotificationListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"unreadOnly\x18\x03 \x01(\bR\n" +
	"unreadOnly\"d\n" +
	"\x18NotificationListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x122\n" +
	"\x04list\x18\x02 \x03(\v2\x1e.notification.NotificationItemR\x04list\"\xa8\x02\n" +
	"\x10NotificationItem\x12\x18\n" +
	"\ainboxId\x18\x01 \x01(\x03R\ainboxId\x12&\n" +
	"\x0enotificationId\x18\x02 \x01(\x03R\x0enotificationId\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\abizType\x18\x04 \x01(\tR\abizType\x12\x14\n" +
	"\x05bizId\x18\x05 \x01(\x03R\x05bizId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"readStatus\x18\b \x01(\x05R\n" +
	"readStatus\x12\x16\n" +
	"\x06readAt\x18\t \x01(\tR\x06readAt\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\tR\tcreatedAt\"+\n" +
	"\x17NotificationReadRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"4\n" +
	"\x18NotificationReadResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\x05R\aupdated2\xb3\x02\n" +
	"\x13NotificationService\x12~\n" +
	"\x11ListNotifications\x12%.notification.NotificationListRequest\x1a&.notification.NotificationListResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/notifications\x12\x8a\x01\n" +
	"\x15MarkNotificationsRead\x12%.notification.NotificationReadRequest\x1a&.notification.NotificationReadResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/notifications/read\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_notification_proto_rawDescOnce sync.Once
	file_internal_api_notification_proto_rawDescData []byte
)

func file_internal_api_notification_proto_rawDescGZIP() []byte {
	file_internal_api_notification_proto_rawDescOnce.Do(func() {
		file_internal_api_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_notification_proto_rawDesc), len(file_internal_api_notification_proto_rawDesc)))
	})
	return file_internal_api_notification_proto_rawDescData
}

var file_internal_api_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_api_notification_proto_goTypes = []any{
	(*NotificationListRequest)(nil),  // 0: notification.NotificationListRequest
	(*NotificationListResponse)(nil), // 1: notification.NotificationListResponse
	(*NotificationItem)(nil),         // 2: notification.NotificationItem
	(*NotificationReadRequest)(nil),  // 3: notification.NotificationReadRequest
	(*NotificationReadResponse)(nil), // 4: notification.NotificationReadResponse
}
var file_internal_api_notification_proto_depIdxs = []int32{
	2, // 0: notification.NotificationListResponse.list:type_name -> notification.NotificationItem
	0, // 1: notification.NotificationService.ListNotifications:input_type -> notification.NotificationListRequest
	3, // 2: notification.NotificationService.MarkNotificationsRead:input_type -> notification.NotificationReadRequest
	1, // 3: notification.NotificationService.ListNotifications:output_type -> notification.NotificationListResponse
	4, // 4: notification.NotificationService.MarkNotificationsRead:output_type -> notification.NotificationReadResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_notification_proto_init() }
func file_internal_api_notification_proto_init() {
	if File_internal_api_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_notification_proto_rawDesc), len(file_internal_api_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_notification_proto_goTypes,
		DependencyIndexes: file_internal_api_notification_proto_depIdxs,
		MessageInfos:      file_internal_api_notification_proto_msgTypes,
	}.Build()
	File_internal_api_notification_proto = out.File
	file_internal_api_notification_proto_goTypes = nil
	file_internal_api_notification_proto_depIdxs = nil
}
