// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: internal/api/register.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest 统一注册请求
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 注册身份类型 volunteer-志愿者 organization-组织 必填 @gotags: json:"registerType,required"
	RegisterType string `protobuf:"bytes,1,opt,name=registerType,proto3" json:"registerType,required"`
	// 通用字段
	// 名称 必填 @gotags: json:"name,required"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,required"`
	// 手机号 必填 @gotags: json:"phone,required"
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,required"`
	// 邮箱 必填 @gotags: json:"email,required"
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,required"`
	// 密码 必填 @gotags: json:"password,required"
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,required"`
	// 志愿者特有字段
	// 年龄 @gotags: json:"age"
	Age int32 `protobuf:"varint,6,opt,name=age,proto3" json:"age"`
	// 性别 @gotags: json:"gender"
	Gender string `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender"`
	// 组织特有字段
	// 组织名称 @gotags: json:"organizationName"
	OrganizationName string `protobuf:"bytes,8,opt,name=organizationName,proto3" json:"organizationName"`
	// 用户名 @gotags: json:"username,required"
	UserName      string `protobuf:"bytes,9,opt,name=userName,proto3" json:"username,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_api_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_register_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetRegisterType() string {
	if x != nil {
		return x.RegisterType
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RegisterRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *RegisterRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *RegisterRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// RegisterResponse 统一注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_api_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_register_proto_rawDescGZIP(), []int{1}
}

var File_internal_api_register_proto protoreflect.FileDescriptor

const file_internal_api_register_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/api/register.proto\x12\bregister\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"\x83\x02\n" +
	"\x0fRegisterRequest\x12\"\n" +
	"\fregisterType\x18\x01 \x01(\tR\fregisterType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12*\n" +
	"\x10organizationName\x18\b \x01(\tR\x10organizationName\x12\x1a\n" +
	"\buserName\x18\t \x01(\tR\buserName\"\x12\n" +
	"\x10RegisterResponse2\x7f\n" +
	"\x0fRegisterService\x12[\n" +
	"\bRegister\x12\x19.register.RegisterRequest\x1a\x1a.register.RegisterResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/register\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_register_proto_rawDescOnce sync.Once
	file_internal_api_register_proto_rawDescData []byte
)

func file_internal_api_register_proto_rawDescGZIP() []byte {
	file_internal_api_register_proto_rawDescOnce.Do(func() {
		file_internal_api_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_register_proto_rawDesc), len(file_internal_api_register_proto_rawDesc)))
	})
	return file_internal_api_register_proto_rawDescData
}

var file_internal_api_register_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_register_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: register.RegisterRequest
	(*RegisterResponse)(nil), // 1: register.RegisterResponse
}
var file_internal_api_register_proto_depIdxs = []int32{
	0, // 0: register.RegisterService.Register:input_type -> register.RegisterRequest
	1, // 1: register.RegisterService.Register:output_type -> register.RegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_register_proto_init() }
func file_internal_api_register_proto_init() {
	if File_internal_api_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_register_proto_rawDesc), len(file_internal_api_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_register_proto_goTypes,
		DependencyIndexes: file_internal_api_register_proto_depIdxs,
		MessageInfos:      file_internal_api_register_proto_msgTypes,
	}.Build()
	File_internal_api_register_proto = out.File
	file_internal_api_register_proto_goTypes = nil
	file_internal_api_register_proto_depIdxs = nil
}
