syntax = "proto3";

package register;

import "google/api/annotations.proto";
import "google/api/client.proto";

option go_package = "volunteer-system/internal/api;api";

// 注册服务端接口
service RegisterService {
  option (google.api.default_host) = "0.0.0.0:8080";

  // 志愿者注册接口
  rpc VolunteerRegister(VolunteerRegisterRequest) returns (RegisterResponse) {
    option (google.api.http) = {
      post: "/api/volunteer/register"
      body: "*"
    };
  }

  // 组织管理者注册接口
  rpc OrganizationRegister(OrganizationRegisterRequest) returns (RegisterResponse) {
    option (google.api.http) = {
      post: "/api/organization/register"
      body: "*"
    };
  }
}

// VolunteerRegisterRequest 志愿者注册请求
message VolunteerRegisterRequest {
  // 名称 必填 @gotags: query:"name,required"
  string name = 1;
  // 手机号 必填 @gotags: query:"phone,required"
  string phone = 2;
  // 邮箱 必填 @gotags: query:"email,required"
  string email = 3;
  // 密码 必填 @gotags: query:"password,required"
  string password = 4;
  // 年龄 @gotags: query:"age"
  int32 age = 5;
  // 性别 @gotags: query:"gender"
  string gender = 6;
  // 用户名 @gotags: query:"username,required"
  string userName = 7;
}

// 组织管理者注册请求
message OrganizationRegisterRequest {
  // 联系人姓名 必填 @gotags: query:"name,required"
  string name = 1;
  // 手机号 必填 @gotags: query:"phone,required"
  string phone = 2;
  // 邮箱 必填 @gotags: query:"email,required"
  string email = 3;
  // 密码 必填 @gotags: query:"password,required"
  string password = 4;
  // 组织名称 @gotags: query:"organizationName,required"
  string organizationName = 5;
  // 统一社会信用代码/组织机构代码 @gotags: query:"code"
  string code = 6;
}

// RegisterResponse 统一注册响应
message RegisterResponse {
}
