// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.0
// source: internal/api/volunteer.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VolunteerListRequest 志愿者列表请求（管理员端）
type VolunteerListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 搜索关键字 可选 @gotags: query:"keyword"
	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword" query:"keyword"`
	// 页码 必填 @gotags: query:"page,required"
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page" query:"page,required"`
	// 页大小 必填 @gotags: query:"pageSize,required"
	PageSize      int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerListRequest) Reset() {
	*x = VolunteerListRequest{}
	mi := &file_internal_api_volunteer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerListRequest) ProtoMessage() {}

func (x *VolunteerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerListRequest.ProtoReflect.Descriptor instead.
func (*VolunteerListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{0}
}

func (x *VolunteerListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *VolunteerListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *VolunteerListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// VolunteerListResponse 志愿者列表响应
type VolunteerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	List          []*VolunteerListItem   `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerListResponse) Reset() {
	*x = VolunteerListResponse{}
	mi := &file_internal_api_volunteer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerListResponse) ProtoMessage() {}

func (x *VolunteerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerListResponse.ProtoReflect.Descriptor instead.
func (*VolunteerListResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{1}
}

func (x *VolunteerListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *VolunteerListResponse) GetList() []*VolunteerListItem {
	if x != nil {
		return x.List
	}
	return nil
}

// VolunteerListItem 志愿者列表项
type VolunteerListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 账户ID
	AccountId int64 `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId"`
	// 真实姓名
	RealName string `protobuf:"bytes,3,opt,name=realName,proto3" json:"realName"`
	// 性别: 0-未知, 1-男, 2-女
	Gender int32 `protobuf:"varint,4,opt,name=gender,proto3" json:"gender"`
	// 头像URL
	AvatarUrl string `protobuf:"bytes,5,opt,name=avatarUrl,proto3" json:"avatarUrl"`
	// 累计服务时长(小时)
	TotalHours float64 `protobuf:"fixed64,6,opt,name=totalHours,proto3" json:"totalHours"`
	// 累计服务次数
	ServiceCount int32 `protobuf:"varint,7,opt,name=serviceCount,proto3" json:"serviceCount"`
	// 信用分
	CreditScore int32 `protobuf:"varint,8,opt,name=creditScore,proto3" json:"creditScore"`
	// 实名认证状态: 0-未认证, 1-审核中, 2-已通过, 3-驳回
	AuditStatus int32 `protobuf:"varint,9,opt,name=auditStatus,proto3" json:"auditStatus"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt"`
	// 更新时间
	UpdatedAt string `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt"`
	// 志愿者状态
	Status        int32 `protobuf:"varint,12,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerListItem) Reset() {
	*x = VolunteerListItem{}
	mi := &file_internal_api_volunteer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerListItem) ProtoMessage() {}

func (x *VolunteerListItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerListItem.ProtoReflect.Descriptor instead.
func (*VolunteerListItem) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{2}
}

func (x *VolunteerListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VolunteerListItem) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *VolunteerListItem) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *VolunteerListItem) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *VolunteerListItem) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *VolunteerListItem) GetTotalHours() float64 {
	if x != nil {
		return x.TotalHours
	}
	return 0
}

func (x *VolunteerListItem) GetServiceCount() int32 {
	if x != nil {
		return x.ServiceCount
	}
	return 0
}

func (x *VolunteerListItem) GetCreditScore() int32 {
	if x != nil {
		return x.CreditScore
	}
	return 0
}

func (x *VolunteerListItem) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *VolunteerListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VolunteerListItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VolunteerListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// VolunteerDetailRequest 志愿者详情请求
type VolunteerDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 志愿者ID 必填 @gotags: path:"id,required"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerDetailRequest) Reset() {
	*x = VolunteerDetailRequest{}
	mi := &file_internal_api_volunteer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerDetailRequest) ProtoMessage() {}

func (x *VolunteerDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerDetailRequest.ProtoReflect.Descriptor instead.
func (*VolunteerDetailRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{3}
}

func (x *VolunteerDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// VolunteerDetailResponse 志愿者详情响应（管理员端）
type VolunteerDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 志愿者信息
	Volunteer     *VolunteerInfo `protobuf:"bytes,1,opt,name=volunteer,proto3" json:"volunteer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerDetailResponse) Reset() {
	*x = VolunteerDetailResponse{}
	mi := &file_internal_api_volunteer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerDetailResponse) ProtoMessage() {}

func (x *VolunteerDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerDetailResponse.ProtoReflect.Descriptor instead.
func (*VolunteerDetailResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{4}
}

func (x *VolunteerDetailResponse) GetVolunteer() *VolunteerInfo {
	if x != nil {
		return x.Volunteer
	}
	return nil
}

// MyProfileRequest 我的个人信息请求（志愿者端）
type MyProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 志愿者ID @gotags: path:"id,required"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" path:"id,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyProfileRequest) Reset() {
	*x = MyProfileRequest{}
	mi := &file_internal_api_volunteer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyProfileRequest) ProtoMessage() {}

func (x *MyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyProfileRequest.ProtoReflect.Descriptor instead.
func (*MyProfileRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{5}
}

func (x *MyProfileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// MyProfileResponse 我的个人信息响应（志愿者端）
type MyProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 志愿者信息
	Volunteer     *VolunteerInfo `protobuf:"bytes,1,opt,name=volunteer,proto3" json:"volunteer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyProfileResponse) Reset() {
	*x = MyProfileResponse{}
	mi := &file_internal_api_volunteer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyProfileResponse) ProtoMessage() {}

func (x *MyProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyProfileResponse.ProtoReflect.Descriptor instead.
func (*MyProfileResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{6}
}

func (x *MyProfileResponse) GetVolunteer() *VolunteerInfo {
	if x != nil {
		return x.Volunteer
	}
	return nil
}

// VolunteerInfo 志愿者信息
type VolunteerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 账户ID
	AccountId int64 `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId"`
	// 真实姓名
	RealName string `protobuf:"bytes,3,opt,name=realName,proto3" json:"realName"`
	// 性别: 0-未知, 1-男, 2-女
	Gender int32 `protobuf:"varint,4,opt,name=gender,proto3" json:"gender"`
	// 出生日期
	Birthday string `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday"`
	// 身份证号
	IdCard string `protobuf:"bytes,6,opt,name=idCard,proto3" json:"idCard"`
	// 头像URL
	AvatarUrl string `protobuf:"bytes,7,opt,name=avatarUrl,proto3" json:"avatarUrl"`
	// 个人简介
	Introduction string `protobuf:"bytes,8,opt,name=introduction,proto3" json:"introduction"`
	// 累计服务时长(小时)
	TotalHours float64 `protobuf:"fixed64,9,opt,name=totalHours,proto3" json:"totalHours"`
	// 累计服务次数
	ServiceCount int32 `protobuf:"varint,10,opt,name=serviceCount,proto3" json:"serviceCount"`
	// 信用分
	CreditScore int32 `protobuf:"varint,11,opt,name=creditScore,proto3" json:"creditScore"`
	// 实名认证状态: 0-未认证, 1-审核中, 2-已通过, 3-驳回
	AuditStatus int32 `protobuf:"varint,12,opt,name=auditStatus,proto3" json:"auditStatus"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt"`
	// 更新时间
	UpdatedAt string `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt"`
	// 志愿者状态
	Status        int32 `protobuf:"varint,15,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerInfo) Reset() {
	*x = VolunteerInfo{}
	mi := &file_internal_api_volunteer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerInfo) ProtoMessage() {}

func (x *VolunteerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerInfo.ProtoReflect.Descriptor instead.
func (*VolunteerInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{7}
}

func (x *VolunteerInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VolunteerInfo) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *VolunteerInfo) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *VolunteerInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *VolunteerInfo) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *VolunteerInfo) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *VolunteerInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *VolunteerInfo) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *VolunteerInfo) GetTotalHours() float64 {
	if x != nil {
		return x.TotalHours
	}
	return 0
}

func (x *VolunteerInfo) GetServiceCount() int32 {
	if x != nil {
		return x.ServiceCount
	}
	return 0
}

func (x *VolunteerInfo) GetCreditScore() int32 {
	if x != nil {
		return x.CreditScore
	}
	return 0
}

func (x *VolunteerInfo) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *VolunteerInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VolunteerInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VolunteerInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// VolunteerUpdateRequest 更新志愿者请求
type VolunteerUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 志愿者ID @gotags: path:"id,required"
	VolunteerId int64 `protobuf:"varint,1,opt,name=volunteerId,proto3" json:"volunteerId" path:"id,required"`
	// 真实姓名 可选 @gotags: json:"realName"
	RealName string `protobuf:"bytes,2,opt,name=realName,proto3" json:"realName"`
	// 性别: 0-未知, 1-男, 2-女 可选 @gotags: json:"gender"
	Gender int32 `protobuf:"varint,3,opt,name=gender,proto3" json:"gender"`
	// 出生日期 可选 @gotags: json:"birthday"
	Birthday string `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday"`
	// 头像URL 可选 @gotags: json:"avatarUrl"
	AvatarUrl string `protobuf:"bytes,5,opt,name=avatarUrl,proto3" json:"avatarUrl"`
	// 个人简介 可选 @gotags: json:"introduction"
	Introduction  string `protobuf:"bytes,6,opt,name=introduction,proto3" json:"introduction"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerUpdateRequest) Reset() {
	*x = VolunteerUpdateRequest{}
	mi := &file_internal_api_volunteer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerUpdateRequest) ProtoMessage() {}

func (x *VolunteerUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerUpdateRequest.ProtoReflect.Descriptor instead.
func (*VolunteerUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{8}
}

func (x *VolunteerUpdateRequest) GetVolunteerId() int64 {
	if x != nil {
		return x.VolunteerId
	}
	return 0
}

func (x *VolunteerUpdateRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *VolunteerUpdateRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *VolunteerUpdateRequest) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *VolunteerUpdateRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *VolunteerUpdateRequest) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

// VolunteerUpdateResponse 更新志愿者响应
type VolunteerUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolunteerUpdateResponse) Reset() {
	*x = VolunteerUpdateResponse{}
	mi := &file_internal_api_volunteer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolunteerUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerUpdateResponse) ProtoMessage() {}

func (x *VolunteerUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerUpdateResponse.ProtoReflect.Descriptor instead.
func (*VolunteerUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{9}
}

// BaseVolunteer 基础志愿者信息（用于其他服务引用）
type BaseVolunteer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 志愿者姓名
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// 志愿者编号
	VolunteerCode string `protobuf:"bytes,2,opt,name=volunteerCode,proto3" json:"volunteerCode"`
	// 手机号
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone"`
	// 邮箱
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email"`
	// 性别
	Gender string `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender"`
	// 志愿者状态
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status"`
	// 状态名称
	StatusName string `protobuf:"bytes,7,opt,name=statusName,proto3" json:"statusName"`
	// 创建时间
	JoinDate string `protobuf:"bytes,8,opt,name=joinDate,proto3" json:"joinDate"`
	// 退出时间
	LeaveDate     string `protobuf:"bytes,9,opt,name=leaveDate,proto3" json:"leaveDate"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseVolunteer) Reset() {
	*x = BaseVolunteer{}
	mi := &file_internal_api_volunteer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseVolunteer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseVolunteer) ProtoMessage() {}

func (x *BaseVolunteer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_volunteer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseVolunteer.ProtoReflect.Descriptor instead.
func (*BaseVolunteer) Descriptor() ([]byte, []int) {
	return file_internal_api_volunteer_proto_rawDescGZIP(), []int{10}
}

func (x *BaseVolunteer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseVolunteer) GetVolunteerCode() string {
	if x != nil {
		return x.VolunteerCode
	}
	return ""
}

func (x *BaseVolunteer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *BaseVolunteer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BaseVolunteer) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *BaseVolunteer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BaseVolunteer) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *BaseVolunteer) GetJoinDate() string {
	if x != nil {
		return x.JoinDate
	}
	return ""
}

func (x *BaseVolunteer) GetLeaveDate() string {
	if x != nil {
		return x.LeaveDate
	}
	return ""
}

var File_internal_api_volunteer_proto protoreflect.FileDescriptor

const file_internal_api_volunteer_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/api/volunteer.proto\x12\tvolunteer\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"`\n" +
	"\x14VolunteerListRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"_\n" +
	"\x15VolunteerListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x120\n" +
	"\x04list\x18\x02 \x03(\v2\x1c.volunteer.VolunteerListItemR\x04list\"\xef\x02\n" +
	"\x11VolunteerListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1a\n" +
	"\brealName\x18\x03 \x01(\tR\brealName\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x1c\n" +
	"\tavatarUrl\x18\x05 \x01(\tR\tavatarUrl\x12\x1e\n" +
	"\n" +
	"totalHours\x18\x06 \x01(\x01R\n" +
	"totalHours\x12\"\n" +
	"\fserviceCount\x18\a \x01(\x05R\fserviceCount\x12 \n" +
	"\vcreditScore\x18\b \x01(\x05R\vcreditScore\x12 \n" +
	"\vauditStatus\x18\t \x01(\x05R\vauditStatus\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\v \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\"(\n" +
	"\x16VolunteerDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Q\n" +
	"\x17VolunteerDetailResponse\x126\n" +
	"\tvolunteer\x18\x01 \x01(\v2\x18.volunteer.VolunteerInfoR\tvolunteer\"\"\n" +
	"\x10MyProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x11MyProfileResponse\x126\n" +
	"\tvolunteer\x18\x01 \x01(\v2\x18.volunteer.VolunteerInfoR\tvolunteer\"\xc3\x03\n" +
	"\rVolunteerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1a\n" +
	"\brealName\x18\x03 \x01(\tR\brealName\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x1a\n" +
	"\bbirthday\x18\x05 \x01(\tR\bbirthday\x12\x16\n" +
	"\x06idCard\x18\x06 \x01(\tR\x06idCard\x12\x1c\n" +
	"\tavatarUrl\x18\a \x01(\tR\tavatarUrl\x12\"\n" +
	"\fintroduction\x18\b \x01(\tR\fintroduction\x12\x1e\n" +
	"\n" +
	"totalHours\x18\t \x01(\x01R\n" +
	"totalHours\x12\"\n" +
	"\fserviceCount\x18\n" +
	" \x01(\x05R\fserviceCount\x12 \n" +
	"\vcreditScore\x18\v \x01(\x05R\vcreditScore\x12 \n" +
	"\vauditStatus\x18\f \x01(\x05R\vauditStatus\x12\x1c\n" +
	"\tcreatedAt\x18\r \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x0e \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x05R\x06status\"\xcc\x01\n" +
	"\x16VolunteerUpdateRequest\x12 \n" +
	"\vvolunteerId\x18\x01 \x01(\x03R\vvolunteerId\x12\x1a\n" +
	"\brealName\x18\x02 \x01(\tR\brealName\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x1a\n" +
	"\bbirthday\x18\x04 \x01(\tR\bbirthday\x12\x1c\n" +
	"\tavatarUrl\x18\x05 \x01(\tR\tavatarUrl\x12\"\n" +
	"\fintroduction\x18\x06 \x01(\tR\fintroduction\"\x19\n" +
	"\x17VolunteerUpdateResponse\"\xff\x01\n" +
	"\rBaseVolunteer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\rvolunteerCode\x18\x02 \x01(\tR\rvolunteerCode\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"statusName\x18\a \x01(\tR\n" +
	"statusName\x12\x1a\n" +
	"\bjoinDate\x18\b \x01(\tR\bjoinDate\x12\x1c\n" +
	"\tleaveDate\x18\t \x01(\tR\tleaveDate2\xfd\x03\n" +
	"\x10VolunteerService\x12p\n" +
	"\rVolunteerList\x12\x1f.volunteer.VolunteerListRequest\x1a .volunteer.VolunteerListResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x14/api/volunteers/list\x12|\n" +
	"\x0fVolunteerDetail\x12!.volunteer.VolunteerDetailRequest\x1a\".volunteer.VolunteerDetailResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/volunteers/detail/:id\x12n\n" +
	"\tMyProfile\x12\x1b.volunteer.MyProfileRequest\x1a\x1c.volunteer.MyProfileResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/volunteers/my/profile/:id\x12x\n" +
	"\x0fVolunteerUpdate\x12!.volunteer.VolunteerUpdateRequest\x1a\".volunteer.VolunteerUpdateResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/volunteers/:id\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_volunteer_proto_rawDescOnce sync.Once
	file_internal_api_volunteer_proto_rawDescData []byte
)

func file_internal_api_volunteer_proto_rawDescGZIP() []byte {
	file_internal_api_volunteer_proto_rawDescOnce.Do(func() {
		file_internal_api_volunteer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_volunteer_proto_rawDesc), len(file_internal_api_volunteer_proto_rawDesc)))
	})
	return file_internal_api_volunteer_proto_rawDescData
}

var file_internal_api_volunteer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_api_volunteer_proto_goTypes = []any{
	(*VolunteerListRequest)(nil),    // 0: volunteer.VolunteerListRequest
	(*VolunteerListResponse)(nil),   // 1: volunteer.VolunteerListResponse
	(*VolunteerListItem)(nil),       // 2: volunteer.VolunteerListItem
	(*VolunteerDetailRequest)(nil),  // 3: volunteer.VolunteerDetailRequest
	(*VolunteerDetailResponse)(nil), // 4: volunteer.VolunteerDetailResponse
	(*MyProfileRequest)(nil),        // 5: volunteer.MyProfileRequest
	(*MyProfileResponse)(nil),       // 6: volunteer.MyProfileResponse
	(*VolunteerInfo)(nil),           // 7: volunteer.VolunteerInfo
	(*VolunteerUpdateRequest)(nil),  // 8: volunteer.VolunteerUpdateRequest
	(*VolunteerUpdateResponse)(nil), // 9: volunteer.VolunteerUpdateResponse
	(*BaseVolunteer)(nil),           // 10: volunteer.BaseVolunteer
}
var file_internal_api_volunteer_proto_depIdxs = []int32{
	2, // 0: volunteer.VolunteerListResponse.list:type_name -> volunteer.VolunteerListItem
	7, // 1: volunteer.VolunteerDetailResponse.volunteer:type_name -> volunteer.VolunteerInfo
	7, // 2: volunteer.MyProfileResponse.volunteer:type_name -> volunteer.VolunteerInfo
	0, // 3: volunteer.VolunteerService.VolunteerList:input_type -> volunteer.VolunteerListRequest
	3, // 4: volunteer.VolunteerService.VolunteerDetail:input_type -> volunteer.VolunteerDetailRequest
	5, // 5: volunteer.VolunteerService.MyProfile:input_type -> volunteer.MyProfileRequest
	8, // 6: volunteer.VolunteerService.VolunteerUpdate:input_type -> volunteer.VolunteerUpdateRequest
	1, // 7: volunteer.VolunteerService.VolunteerList:output_type -> volunteer.VolunteerListResponse
	4, // 8: volunteer.VolunteerService.VolunteerDetail:output_type -> volunteer.VolunteerDetailResponse
	6, // 9: volunteer.VolunteerService.MyProfile:output_type -> volunteer.MyProfileResponse
	9, // 10: volunteer.VolunteerService.VolunteerUpdate:output_type -> volunteer.VolunteerUpdateResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_api_volunteer_proto_init() }
func file_internal_api_volunteer_proto_init() {
	if File_internal_api_volunteer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_volunteer_proto_rawDesc), len(file_internal_api_volunteer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_volunteer_proto_goTypes,
		DependencyIndexes: file_internal_api_volunteer_proto_depIdxs,
		MessageInfos:      file_internal_api_volunteer_proto_msgTypes,
	}.Build()
	File_internal_api_volunteer_proto = out.File
	file_internal_api_volunteer_proto_goTypes = nil
	file_internal_api_volunteer_proto_depIdxs = nil
}
