// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.0
// source: internal/api/work_hours.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkHourLogListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码 可选 @gotags: query:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" query:"page"`
	// 页大小 可选 @gotags: query:"pageSize"
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize" query:"pageSize"`
	// 活动ID 可选 @gotags: json:"activityId"
	ActivityId int64 `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId"`
	// 报名ID 可选 @gotags: json:"signupId"
	SignupId int64 `protobuf:"varint,4,opt,name=signupId,proto3" json:"signupId"`
	// 操作类型: 1-发放,2-作废,3-重发 可选 @gotags: json:"operationType"
	OperationType int32 `protobuf:"varint,5,opt,name=operationType,proto3" json:"operationType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkHourLogListRequest) Reset() {
	*x = WorkHourLogListRequest{}
	mi := &file_internal_api_work_hours_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkHourLogListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkHourLogListRequest) ProtoMessage() {}

func (x *WorkHourLogListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_work_hours_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkHourLogListRequest.ProtoReflect.Descriptor instead.
func (*WorkHourLogListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_work_hours_proto_rawDescGZIP(), []int{0}
}

func (x *WorkHourLogListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *WorkHourLogListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *WorkHourLogListRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *WorkHourLogListRequest) GetSignupId() int64 {
	if x != nil {
		return x.SignupId
	}
	return 0
}

func (x *WorkHourLogListRequest) GetOperationType() int32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

type WorkHourLogListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	List          []*WorkHourLogItem     `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkHourLogListResponse) Reset() {
	*x = WorkHourLogListResponse{}
	mi := &file_internal_api_work_hours_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkHourLogListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkHourLogListResponse) ProtoMessage() {}

func (x *WorkHourLogListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_work_hours_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkHourLogListResponse.ProtoReflect.Descriptor instead.
func (*WorkHourLogListResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_work_hours_proto_rawDescGZIP(), []int{1}
}

func (x *WorkHourLogListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *WorkHourLogListResponse) GetList() []*WorkHourLogItem {
	if x != nil {
		return x.List
	}
	return nil
}

type WorkHourLogItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 工时流水ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 志愿者ID（volunteers.id）
	VolunteerId int64 `protobuf:"varint,2,opt,name=volunteerId,proto3" json:"volunteerId"`
	// 活动ID
	ActivityId int64 `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId"`
	// 报名ID
	SignupId int64 `protobuf:"varint,4,opt,name=signupId,proto3" json:"signupId"`
	// 操作类型: 1-发放,2-作废,3-重发
	OperationType int32 `protobuf:"varint,5,opt,name=operationType,proto3" json:"operationType"`
	// 工时增量（作废时为负数）
	HoursDelta float64 `protobuf:"fixed64,6,opt,name=hoursDelta,proto3" json:"hoursDelta"`
	// 服务次数增量
	ServiceCountDelta int64 `protobuf:"varint,7,opt,name=serviceCountDelta,proto3" json:"serviceCountDelta"`
	// 变更前累计工时
	BeforeTotalHours float64 `protobuf:"fixed64,8,opt,name=beforeTotalHours,proto3" json:"beforeTotalHours"`
	// 变更后累计工时
	AfterTotalHours float64 `protobuf:"fixed64,9,opt,name=afterTotalHours,proto3" json:"afterTotalHours"`
	// 变更前累计服务次数
	BeforeServiceCount int64 `protobuf:"varint,10,opt,name=beforeServiceCount,proto3" json:"beforeServiceCount"`
	// 变更后累计服务次数
	AfterServiceCount int64 `protobuf:"varint,11,opt,name=afterServiceCount,proto3" json:"afterServiceCount"`
	// 工时结算版本号
	WorkHourVersion int64 `protobuf:"varint,12,opt,name=workHourVersion,proto3" json:"workHourVersion"`
	// 关联原流水ID（作废/重发场景）
	RefLogId int64 `protobuf:"varint,13,opt,name=refLogId,proto3" json:"refLogId"`
	// 备注原因
	Reason string `protobuf:"bytes,14,opt,name=reason,proto3" json:"reason"`
	// 操作人账号ID
	OperatorId int64 `protobuf:"varint,15,opt,name=operatorId,proto3" json:"operatorId"`
	// 幂等键
	IdempotencyKey string `protobuf:"bytes,16,opt,name=idempotencyKey,proto3" json:"idempotencyKey"`
	// 创建时间
	CreatedAt     string `protobuf:"bytes,17,opt,name=createdAt,proto3" json:"createdAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkHourLogItem) Reset() {
	*x = WorkHourLogItem{}
	mi := &file_internal_api_work_hours_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkHourLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkHourLogItem) ProtoMessage() {}

func (x *WorkHourLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_work_hours_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkHourLogItem.ProtoReflect.Descriptor instead.
func (*WorkHourLogItem) Descriptor() ([]byte, []int) {
	return file_internal_api_work_hours_proto_rawDescGZIP(), []int{2}
}

func (x *WorkHourLogItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkHourLogItem) GetVolunteerId() int64 {
	if x != nil {
		return x.VolunteerId
	}
	return 0
}

func (x *WorkHourLogItem) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *WorkHourLogItem) GetSignupId() int64 {
	if x != nil {
		return x.SignupId
	}
	return 0
}

func (x *WorkHourLogItem) GetOperationType() int32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

func (x *WorkHourLogItem) GetHoursDelta() float64 {
	if x != nil {
		return x.HoursDelta
	}
	return 0
}

func (x *WorkHourLogItem) GetServiceCountDelta() int64 {
	if x != nil {
		return x.ServiceCountDelta
	}
	return 0
}

func (x *WorkHourLogItem) GetBeforeTotalHours() float64 {
	if x != nil {
		return x.BeforeTotalHours
	}
	return 0
}

func (x *WorkHourLogItem) GetAfterTotalHours() float64 {
	if x != nil {
		return x.AfterTotalHours
	}
	return 0
}

func (x *WorkHourLogItem) GetBeforeServiceCount() int64 {
	if x != nil {
		return x.BeforeServiceCount
	}
	return 0
}

func (x *WorkHourLogItem) GetAfterServiceCount() int64 {
	if x != nil {
		return x.AfterServiceCount
	}
	return 0
}

func (x *WorkHourLogItem) GetWorkHourVersion() int64 {
	if x != nil {
		return x.WorkHourVersion
	}
	return 0
}

func (x *WorkHourLogItem) GetRefLogId() int64 {
	if x != nil {
		return x.RefLogId
	}
	return 0
}

func (x *WorkHourLogItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WorkHourLogItem) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *WorkHourLogItem) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *WorkHourLogItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type VoidWorkHourRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 报名ID 必填 @gotags: json:"signupId,required"
	SignupId int64 `protobuf:"varint,1,opt,name=signupId,proto3" json:"signupId,required"`
	// 作废原因 必填 @gotags: json:"reason,required"
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,required"`
	// 幂等键 必填 @gotags: json:"idempotencyKey,required"
	IdempotencyKey string `protobuf:"bytes,3,opt,name=idempotencyKey,proto3" json:"idempotencyKey,required"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VoidWorkHourRequest) Reset() {
	*x = VoidWorkHourRequest{}
	mi := &file_internal_api_work_hours_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidWorkHourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidWorkHourRequest) ProtoMessage() {}

func (x *VoidWorkHourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_work_hours_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidWorkHourRequest.ProtoReflect.Descriptor instead.
func (*VoidWorkHourRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_work_hours_proto_rawDescGZIP(), []int{3}
}

func (x *VoidWorkHourRequest) GetSignupId() int64 {
	if x != nil {
		return x.SignupId
	}
	return 0
}

func (x *VoidWorkHourRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VoidWorkHourRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type VoidWorkHourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	WorkHourLogId int64                  `protobuf:"varint,2,opt,name=workHourLogId,proto3" json:"workHourLogId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidWorkHourResponse) Reset() {
	*x = VoidWorkHourResponse{}
	mi := &file_internal_api_work_hours_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidWorkHourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidWorkHourResponse) ProtoMessage() {}

func (x *VoidWorkHourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_work_hours_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidWorkHourResponse.ProtoReflect.Descriptor instead.
func (*VoidWorkHourResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_work_hours_proto_rawDescGZIP(), []int{4}
}

func (x *VoidWorkHourResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VoidWorkHourResponse) GetWorkHourLogId() int64 {
	if x != nil {
		return x.WorkHourLogId
	}
	return 0
}

type RecalculateWorkHourRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 报名ID 必填 @gotags: json:"signupId,required"
	SignupId int64 `protobuf:"varint,1,opt,name=signupId,proto3" json:"signupId,required"`
	// 重算工时（小时）可选；<=0则按签到签退时间自动计算 @gotags: json:"hours"
	Hours float64 `protobuf:"fixed64,2,opt,name=hours,proto3" json:"hours"`
	// 重算原因 必填 @gotags: json:"reason,required"
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,required"`
	// 幂等键 必填 @gotags: json:"idempotencyKey,required"
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotencyKey,proto3" json:"idempotencyKey,required"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecalculateWorkHourRequest) Reset() {
	*x = RecalculateWorkHourRequest{}
	mi := &file_internal_api_work_hours_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalculateWorkHourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalculateWorkHourRequest) ProtoMessage() {}

func (x *RecalculateWorkHourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_work_hours_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalculateWorkHourRequest.ProtoReflect.Descriptor instead.
func (*RecalculateWorkHourRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_work_hours_proto_rawDescGZIP(), []int{5}
}

func (x *RecalculateWorkHourRequest) GetSignupId() int64 {
	if x != nil {
		return x.SignupId
	}
	return 0
}

func (x *RecalculateWorkHourRequest) GetHours() float64 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *RecalculateWorkHourRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RecalculateWorkHourRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RecalculateWorkHourResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// 本次重算写入的工时流水ID
	WorkHourLogId int64 `protobuf:"varint,2,opt,name=workHourLogId,proto3" json:"workHourLogId"`
	// 重算后发放工时
	GrantedHours  float64 `protobuf:"fixed64,3,opt,name=grantedHours,proto3" json:"grantedHours"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalculateWorkHourResponse) Reset() {
	*x = RecalculateWorkHourResponse{}
	mi := &file_internal_api_work_hours_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalculateWorkHourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalculateWorkHourResponse) ProtoMessage() {}

func (x *RecalculateWorkHourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_work_hours_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalculateWorkHourResponse.ProtoReflect.Descriptor instead.
func (*RecalculateWorkHourResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_work_hours_proto_rawDescGZIP(), []int{6}
}

func (x *RecalculateWorkHourResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecalculateWorkHourResponse) GetWorkHourLogId() int64 {
	if x != nil {
		return x.WorkHourLogId
	}
	return 0
}

func (x *RecalculateWorkHourResponse) GetGrantedHours() float64 {
	if x != nil {
		return x.GrantedHours
	}
	return 0
}

var File_internal_api_work_hours_proto protoreflect.FileDescriptor

const file_internal_api_work_hours_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/api/work_hours.proto\x12\bworkhour\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"\xaa\x01\n" +
	"\x16WorkHourLogListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"activityId\x18\x03 \x01(\x03R\n" +
	"activityId\x12\x1a\n" +
	"\bsignupId\x18\x04 \x01(\x03R\bsignupId\x12$\n" +
	"\roperationType\x18\x05 \x01(\x05R\roperationType\"^\n" +
	"\x17WorkHourLogListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12-\n" +
	"\x04list\x18\x02 \x03(\v2\x19.workhour.WorkHourLogItemR\x04list\"\xeb\x04\n" +
	"\x0fWorkHourLogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vvolunteerId\x18\x02 \x01(\x03R\vvolunteerId\x12\x1e\n" +
	"\n" +
	"activityId\x18\x03 \x01(\x03R\n" +
	"activityId\x12\x1a\n" +
	"\bsignupId\x18\x04 \x01(\x03R\bsignupId\x12$\n" +
	"\roperationType\x18\x05 \x01(\x05R\roperationType\x12\x1e\n" +
	"\n" +
	"hoursDelta\x18\x06 \x01(\x01R\n" +
	"hoursDelta\x12,\n" +
	"\x11serviceCountDelta\x18\a \x01(\x03R\x11serviceCountDelta\x12*\n" +
	"\x10beforeTotalHours\x18\b \x01(\x01R\x10beforeTotalHours\x12(\n" +
	"\x0fafterTotalHours\x18\t \x01(\x01R\x0fafterTotalHours\x12.\n" +
	"\x12beforeServiceCount\x18\n" +
	" \x01(\x03R\x12beforeServiceCount\x12,\n" +
	"\x11afterServiceCount\x18\v \x01(\x03R\x11afterServiceCount\x12(\n" +
	"\x0fworkHourVersion\x18\f \x01(\x03R\x0fworkHourVersion\x12\x1a\n" +
	"\brefLogId\x18\r \x01(\x03R\brefLogId\x12\x16\n" +
	"\x06reason\x18\x0e \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"operatorId\x18\x0f \x01(\x03R\n" +
	"operatorId\x12&\n" +
	"\x0eidempotencyKey\x18\x10 \x01(\tR\x0eidempotencyKey\x12\x1c\n" +
	"\tcreatedAt\x18\x11 \x01(\tR\tcreatedAt\"q\n" +
	"\x13VoidWorkHourRequest\x12\x1a\n" +
	"\bsignupId\x18\x01 \x01(\x03R\bsignupId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12&\n" +
	"\x0eidempotencyKey\x18\x03 \x01(\tR\x0eidempotencyKey\"V\n" +
	"\x14VoidWorkHourResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\rworkHourLogId\x18\x02 \x01(\x03R\rworkHourLogId\"\x8e\x01\n" +
	"\x1aRecalculateWorkHourRequest\x12\x1a\n" +
	"\bsignupId\x18\x01 \x01(\x03R\bsignupId\x12\x14\n" +
	"\x05hours\x18\x02 \x01(\x01R\x05hours\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12&\n" +
	"\x0eidempotencyKey\x18\x04 \x01(\tR\x0eidempotencyKey\"\x81\x01\n" +
	"\x1bRecalculateWorkHourResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\rworkHourLogId\x18\x02 \x01(\x03R\rworkHourLogId\x12\"\n" +
	"\fgrantedHours\x18\x03 \x01(\x01R\fgrantedHours2\x98\x03\n" +
	"\x0fWorkHourService\x12w\n" +
	"\x0fWorkHourLogList\x12 .workhour.WorkHourLogListRequest\x1a!.workhour.WorkHourLogListResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/work-hours/list\x12n\n" +
	"\fVoidWorkHour\x12\x1d.workhour.VoidWorkHourRequest\x1a\x1e.workhour.VoidWorkHourResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/work-hours/void\x12\x8a\x01\n" +
	"\x13RecalculateWorkHour\x12$.workhour.RecalculateWorkHourRequest\x1a%.workhour.RecalculateWorkHourResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/work-hours/recalculate\x1a\x0f\xcaA\f0.0.0.0:8080B#Z!volunteer-system/internal/api;apib\x06proto3"

var (
	file_internal_api_work_hours_proto_rawDescOnce sync.Once
	file_internal_api_work_hours_proto_rawDescData []byte
)

func file_internal_api_work_hours_proto_rawDescGZIP() []byte {
	file_internal_api_work_hours_proto_rawDescOnce.Do(func() {
		file_internal_api_work_hours_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_work_hours_proto_rawDesc), len(file_internal_api_work_hours_proto_rawDesc)))
	})
	return file_internal_api_work_hours_proto_rawDescData
}

var file_internal_api_work_hours_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_api_work_hours_proto_goTypes = []any{
	(*WorkHourLogListRequest)(nil),      // 0: workhour.WorkHourLogListRequest
	(*WorkHourLogListResponse)(nil),     // 1: workhour.WorkHourLogListResponse
	(*WorkHourLogItem)(nil),             // 2: workhour.WorkHourLogItem
	(*VoidWorkHourRequest)(nil),         // 3: workhour.VoidWorkHourRequest
	(*VoidWorkHourResponse)(nil),        // 4: workhour.VoidWorkHourResponse
	(*RecalculateWorkHourRequest)(nil),  // 5: workhour.RecalculateWorkHourRequest
	(*RecalculateWorkHourResponse)(nil), // 6: workhour.RecalculateWorkHourResponse
}
var file_internal_api_work_hours_proto_depIdxs = []int32{
	2, // 0: workhour.WorkHourLogListResponse.list:type_name -> workhour.WorkHourLogItem
	0, // 1: workhour.WorkHourService.WorkHourLogList:input_type -> workhour.WorkHourLogListRequest
	3, // 2: workhour.WorkHourService.VoidWorkHour:input_type -> workhour.VoidWorkHourRequest
	5, // 3: workhour.WorkHourService.RecalculateWorkHour:input_type -> workhour.RecalculateWorkHourRequest
	1, // 4: workhour.WorkHourService.WorkHourLogList:output_type -> workhour.WorkHourLogListResponse
	4, // 5: workhour.WorkHourService.VoidWorkHour:output_type -> workhour.VoidWorkHourResponse
	6, // 6: workhour.WorkHourService.RecalculateWorkHour:output_type -> workhour.RecalculateWorkHourResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_work_hours_proto_init() }
func file_internal_api_work_hours_proto_init() {
	if File_internal_api_work_hours_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_work_hours_proto_rawDesc), len(file_internal_api_work_hours_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_work_hours_proto_goTypes,
		DependencyIndexes: file_internal_api_work_hours_proto_depIdxs,
		MessageInfos:      file_internal_api_work_hours_proto_msgTypes,
	}.Build()
	File_internal_api_work_hours_proto = out.File
	file_internal_api_work_hours_proto_goTypes = nil
	file_internal_api_work_hours_proto_depIdxs = nil
}
