// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameActivity = "activities"

// Activity 活动主表
type Activity struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	OrgID         int64     `gorm:"column:org_id;not null;comment:发布组织ID (关联organizations.id)" json:"org_id"`            // 发布组织ID (关联organizations.id)
	Title         string    `gorm:"column:title;not null;comment:活动标题" json:"title"`                                     // 活动标题
	Description   string    `gorm:"column:description;not null;comment:活动描述/副标题" json:"description"`                     // 活动描述/副标题
	CoverURL      string    `gorm:"column:cover_url;not null;comment:活动封面图URL" json:"cover_url"`                         // 活动封面图URL
	StartTime     time.Time `gorm:"column:start_time;not null;default:CURRENT_TIMESTAMP;comment:开始时间" json:"start_time"` // 开始时间
	EndTime       time.Time `gorm:"column:end_time;not null;default:CURRENT_TIMESTAMP;comment:结束时间" json:"end_time"`     // 结束时间
	Location      string    `gorm:"column:location;not null;comment:地点名称" json:"location"`                               // 地点名称
	Address       string    `gorm:"column:address;not null;comment:详细地址" json:"address"`                                 // 详细地址
	Duration      float64   `gorm:"column:duration;not null;default:0.0;comment:预估工时(小时)" json:"duration"`               // 预估工时(小时)
	MaxPeople     int32     `gorm:"column:max_people;not null;comment:最大招募人数 (0表示不限)" json:"max_people"`                 // 最大招募人数 (0表示不限)
	CurrentPeople int32     `gorm:"column:current_people;not null;comment:当前已报名人数(冗余字段)" json:"current_people"`          // 当前已报名人数(冗余字段)
	Status        int32     `gorm:"column:status;not null;default:1;comment:状态: 1-报名中, 2-已结束, 3-已取消" json:"status"`      // 状态: 1-报名中, 2-已结束, 3-已取消
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Activity's table name
func (*Activity) TableName() string {
	return TableNameActivity
}
