// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAiMessage = "ai_messages"

// AiMessage AI 助手消息表
type AiMessage struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                     // 主键ID
	SessionID    int64     `gorm:"column:session_id;not null;comment:会话ID（关联 ai_sessions.id）" json:"session_id"`                                       // 会话ID（关联 ai_sessions.id）
	SeqNo        int32     `gorm:"column:seq_no;not null;comment:会话内消息序号（从1递增）" json:"seq_no"`                                                         // 会话内消息序号（从1递增）
	Role         int32     `gorm:"column:role;not null;comment:角色：1-system，2-user，3-assistant，4-tool" json:"role"`                                     // 角色：1-system，2-user，3-assistant，4-tool
	Content      string    `gorm:"column:content;not null;comment:消息内容" json:"content"`                                                                // 消息内容
	Model        string    `gorm:"column:model;not null;comment:模型名称" json:"model"`                                                                    // 模型名称
	FinishReason int32     `gorm:"column:finish_reason;not null;comment:结束原因：0-未知，1-stop，2-length，3-content_filter，4-tool_calls" json:"finish_reason"` // 结束原因：0-未知，1-stop，2-length，3-content_filter，4-tool_calls
	TokenIn      int32     `gorm:"column:token_in;not null;comment:输入token数" json:"token_in"`                                                          // 输入token数
	TokenOut     int32     `gorm:"column:token_out;not null;comment:输出token数" json:"token_out"`                                                        // 输出token数
	LatencyMs    int32     `gorm:"column:latency_ms;not null;comment:模型调用耗时（毫秒）" json:"latency_ms"`                                                    // 模型调用耗时（毫秒）
	RequestID    string    `gorm:"column:request_id;not null;comment:链路追踪ID" json:"request_id"`                                                        // 链路追踪ID
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                // 创建时间
}

// TableName AiMessage's table name
func (*AiMessage) TableName() string {
	return TableNameAiMessage
}
