// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAiToolCall = "ai_tool_calls"

// AiToolCall AI 工具调用日志表
type AiToolCall struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                 // 主键ID
	SessionID  int64     `gorm:"column:session_id;not null;comment:会话ID（关联 ai_sessions.id）" json:"session_id"`                   // 会话ID（关联 ai_sessions.id）
	MessageID  int64     `gorm:"column:message_id;not null;comment:触发工具调用的 assistant 消息ID（关联 ai_messages.id）" json:"message_id"` // 触发工具调用的 assistant 消息ID（关联 ai_messages.id）
	ToolName   string    `gorm:"column:tool_name;not null;comment:工具名称" json:"tool_name"`                                        // 工具名称
	ToolInput  string    `gorm:"column:tool_input;not null;comment:工具输入参数（JSON字符串）" json:"tool_input"`                           // 工具输入参数（JSON字符串）
	ToolOutput *string   `gorm:"column:tool_output;comment:工具输出结果（JSON字符串）" json:"tool_output"`                                  // 工具输出结果（JSON字符串）
	Success    int32     `gorm:"column:success;not null;comment:是否成功：0-失败，1-成功" json:"success"`                                  // 是否成功：0-失败，1-成功
	ErrorCode  string    `gorm:"column:error_code;not null;comment:错误码" json:"error_code"`                                       // 错误码
	ErrorMsg   string    `gorm:"column:error_msg;not null;comment:错误信息" json:"error_msg"`                                        // 错误信息
	LatencyMs  int32     `gorm:"column:latency_ms;not null;comment:工具执行耗时（毫秒）" json:"latency_ms"`                                // 工具执行耗时（毫秒）
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`            // 创建时间
}

// TableName AiToolCall's table name
func (*AiToolCall) TableName() string {
	return TableNameAiToolCall
}
