// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAiUsageDaily = "ai_usage_daily"

// AiUsageDaily AI 每日用量汇总表
type AiUsageDaily struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                            // 主键ID
	BizDate       time.Time `gorm:"column:biz_date;not null;comment:业务日期" json:"biz_date"`                                     // 业务日期
	UserID        int64     `gorm:"column:user_id;not null;comment:用户ID（关联 sys_accounts.id）" json:"user_id"`                   // 用户ID（关联 sys_accounts.id）
	RequestCount  int64     `gorm:"column:request_count;not null;comment:请求总数" json:"request_count"`                           // 请求总数
	SuccessCount  int64     `gorm:"column:success_count;not null;comment:成功请求数" json:"success_count"`                          // 成功请求数
	FailedCount   int64     `gorm:"column:failed_count;not null;comment:失败请求数" json:"failed_count"`                            // 失败请求数
	TokenInTotal  int64     `gorm:"column:token_in_total;not null;comment:输入token汇总" json:"token_in_total"`                    // 输入token汇总
	TokenOutTotal int64     `gorm:"column:token_out_total;not null;comment:输出token汇总" json:"token_out_total"`                  // 输出token汇总
	EstimatedCost float64   `gorm:"column:estimated_cost;not null;default:0.0000;comment:预估成本（按模型单价计算）" json:"estimated_cost"` // 预估成本（按模型单价计算）
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`       // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`       // 更新时间
}

// TableName AiUsageDaily's table name
func (*AiUsageDaily) TableName() string {
	return TableNameAiUsageDaily
}
