// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLevelRule = "level_rules"

// LevelRule 志愿者等级规则表
type LevelRule struct {
	Level          int32  `gorm:"column:level;primaryKey;comment:等级ID（从1开始）" json:"level"`                    // 等级ID（从1开始）
	Name           string `gorm:"column:name;not null;comment:等级名称" json:"name"`                              // 等级名称
	ThresholdHours int32  `gorm:"column:threshold_hours;not null;comment:达到该等级所需累计工时" json:"threshold_hours"` // 达到该等级所需累计工时
}

// TableName LevelRule's table name
func (*LevelRule) TableName() string {
	return TableNameLevelRule
}
