// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotification = "notifications"

// Notification 通知内容主表
type Notification struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                           // 主键ID
	EventType   string    `gorm:"column:event_type;not null;comment:事件类型: activity_created/activity_updated/member_join" json:"event_type"` // 事件类型: activity_created/activity_updated/member_join
	BizType     string    `gorm:"column:biz_type;not null;comment:业务类型: activity/membership/organization" json:"biz_type"`                  // 业务类型: activity/membership/organization
	BizID       int64     `gorm:"column:biz_id;not null;comment:业务ID" json:"biz_id"`                                                        // 业务ID
	SourceOrgID int64     `gorm:"column:source_org_id;not null;comment:来源组织ID(用于退出组织后归档)" json:"source_org_id"`                             // 来源组织ID(用于退出组织后归档)
	SenderID    int64     `gorm:"column:sender_id;not null;comment:发送方账号ID(关联sys_accounts.id)" json:"sender_id"`                            // 发送方账号ID(关联sys_accounts.id)
	DedupeKey   string    `gorm:"column:dedupe_key;not null;comment:事件幂等键" json:"dedupe_key"`                                               // 事件幂等键
	Title       string    `gorm:"column:title;not null;comment:通知标题" json:"title"`                                                          // 通知标题
	Content     string    `gorm:"column:content;not null;comment:通知正文" json:"content"`                                                      // 通知正文
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                      // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                      // 更新时间
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
