// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrgMember = "org_members"

// OrgMember 组织成员关联表
type OrgMember struct {
	ID          int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                           // 主键ID
	OrgID       int64      `gorm:"column:org_id;not null;comment:组织ID (关联organizations.id)" json:"org_id"`                   // 组织ID (关联organizations.id)
	VolunteerID int64      `gorm:"column:volunteer_id;not null;comment:志愿者ID (关联volunteers.id)" json:"volunteer_id"`         // 志愿者ID (关联volunteers.id)
	Role        int32      `gorm:"column:role;not null;default:1;comment:角色: 1-普通成员, 2-管理员, 3-负责人" json:"role"`              // 角色: 1-普通成员, 2-管理员, 3-负责人
	Status      int32      `gorm:"column:status;not null;default:1;comment:成员状态: 1-待审核, 2-正式成员, 3-已拒绝, 4-已退出" json:"status"` // 成员状态: 1-待审核, 2-正式成员, 3-已拒绝, 4-已退出
	AppliedAt   time.Time  `gorm:"column:applied_at;not null;default:CURRENT_TIMESTAMP;comment:申请时间" json:"applied_at"`      // 申请时间
	JoinedAt    *time.Time `gorm:"column:joined_at;comment:正式加入时间" json:"joined_at"`                                         // 正式加入时间
	CreatedAt   time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt   time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`      // 更新时间
}

// TableName OrgMember's table name
func (*OrgMember) TableName() string {
	return TableNameOrgMember
}
