// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganization = "organizations"

// Organization 组织档案表
type Organization struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                              // 主键ID
	AccountID     int64     `gorm:"column:account_id;not null;comment:关联sys_accounts.id" json:"account_id"`                      // 关联sys_accounts.id
	OrgName       string    `gorm:"column:org_name;not null;comment:组织全称" json:"org_name"`                                       // 组织全称
	LicenseCode   string    `gorm:"column:license_code;not null;comment:统一社会信用代码/组织机构代码" json:"license_code"`                    // 统一社会信用代码/组织机构代码
	ContactPerson string    `gorm:"column:contact_person;not null;comment:负责人姓名" json:"contact_person"`                          // 负责人姓名
	ContactPhone  string    `gorm:"column:contact_phone;not null;comment:办公电话 (AES加密后存储)" json:"contact_phone"`                  // 办公电话 (AES加密后存储)
	Address       string    `gorm:"column:address;not null;comment:办公地址" json:"address"`                                         // 办公地址
	LogoURL       string    `gorm:"column:logo_url;not null;comment:组织Logo URL" json:"logo_url"`                                 // 组织Logo URL
	Introduction  string    `gorm:"column:introduction;not null;comment:组织介绍" json:"introduction"`                               // 组织介绍
	AuditStatus   int32     `gorm:"column:audit_status;not null;comment:资质审核状态: 0-未提交, 1-审核中, 2-已通过, 3-已驳回" json:"audit_status"` // 资质审核状态: 0-未提交, 1-审核中, 2-已通过, 3-已驳回
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`         // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`         // 更新时间
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
