// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRbacPermission = "rbac_permissions"

// RbacPermission RBAC 权限点定义表
type RbacPermission struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	Resource    string    `gorm:"column:resource;not null;comment:资源标识" json:"resource"`                               // 资源标识
	Action      string    `gorm:"column:action;not null;comment:动作标识" json:"action"`                                   // 动作标识
	Description string    `gorm:"column:description;not null;comment:权限描述" json:"description"`                         // 权限描述
	Status      int32     `gorm:"column:status;not null;default:1;comment:状态：1-启用，0-禁用" json:"status"`                 // 状态：1-启用，0-禁用
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName RbacPermission's table name
func (*RbacPermission) TableName() string {
	return TableNameRbacPermission
}
