// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRbacChangeLog = "rbac_change_logs"

// RbacChangeLog RBAC 变更审计日志
type RbacChangeLog struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	OperatorID      int64     `gorm:"column:operator_id;not null;comment:操作人账号ID" json:"operator_id"`                      // 操作人账号ID
	TargetAccountID int64     `gorm:"column:target_account_id;not null;comment:目标账号ID" json:"target_account_id"`           // 目标账号ID
	TargetRoleID    int64     `gorm:"column:target_role_id;not null;comment:目标角色ID" json:"target_role_id"`                 // 目标角色ID
	ScopeType       string    `gorm:"column:scope_type;not null;comment:作用域类型：global/org" json:"scope_type"`               // 作用域类型：global/org
	ScopeID         int64     `gorm:"column:scope_id;not null;comment:作用域ID" json:"scope_id"`                              // 作用域ID
	ChangeType      string    `gorm:"column:change_type;not null;comment:变更类型" json:"change_type"`                         // 变更类型
	BeforeValue     string    `gorm:"column:before_value;not null;comment:变更前数据(JSON)" json:"before_value"`                // 变更前数据(JSON)
	AfterValue      string    `gorm:"column:after_value;not null;comment:变更后数据(JSON)" json:"after_value"`                  // 变更后数据(JSON)
	Remark          string    `gorm:"column:remark;not null;comment:备注" json:"remark"`                                     // 备注
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName RbacChangeLog's table name
func (*RbacChangeLog) TableName() string {
	return TableNameRbacChangeLog
}
