// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRbacAccountRole = "rbac_account_roles"

// RbacAccountRole RBAC 账号角色授权表
type RbacAccountRole struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                             // 主键ID
	AccountID int64      `gorm:"column:account_id;not null;comment:账号ID（关联 sys_accounts.id）" json:"account_id"`              // 账号ID（关联 sys_accounts.id）
	RoleID    int64      `gorm:"column:role_id;not null;comment:角色ID（关联 rbac_roles.id）" json:"role_id"`                      // 角色ID（关联 rbac_roles.id）
	ScopeType string     `gorm:"column:scope_type;not null;default:org;comment:作用域类型：global/org" json:"scope_type"`          // 作用域类型：global/org
	ScopeID   int64      `gorm:"column:scope_id;not null;comment:作用域ID（global 固定为0，org 为 organizations.id）" json:"scope_id"` // 作用域ID（global 固定为0，org 为 organizations.id）
	Status    int32      `gorm:"column:status;not null;default:1;comment:状态：1-启用，0-禁用" json:"status"`                        // 状态：1-启用，0-禁用
	GrantedBy int64      `gorm:"column:granted_by;not null;comment:授权人账号ID" json:"granted_by"`                               // 授权人账号ID
	ExpiresAt *time.Time `gorm:"column:expires_at;comment:过期时间（为空表示不过期）" json:"expires_at"`                                  // 过期时间（为空表示不过期）
	CreatedAt time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`        // 创建时间
	UpdatedAt time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`        // 更新时间
}

// TableName RbacAccountRole's table name
func (*RbacAccountRole) TableName() string {
	return TableNameRbacAccountRole
}
