// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysAccount = "sys_accounts"

// SysAccount 用户账号主表（所有用户的基础登录信息）
type SysAccount struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	Username      string         `gorm:"column:username;not null;comment:用户名" json:"username"`                                // 用户名
	Mobile        string         `gorm:"column:mobile;not null;comment:手机号 (AES-GCM加密后存储)" json:"mobile"`                     // 手机号 (AES-GCM加密后存储)
	MobileHash    string         `gorm:"column:mobile_hash;not null;comment:手机号哈希值 (SHA-256, 用于唯一性检查)" json:"mobile_hash"`    // 手机号哈希值 (SHA-256, 用于唯一性检查)
	Email         string         `gorm:"column:email;not null;comment:邮箱 (唯一登录标识)" json:"email"`                              // 邮箱 (唯一登录标识)
	Password      string         `gorm:"column:password;not null;comment:加密后的密码 (建议使用BCrypt)" json:"password"`                // 加密后的密码 (建议使用BCrypt)
	IdentityType  int32          `gorm:"column:identity_type;not null;comment:身份类型: 1-志愿者, 2-组织管理者" json:"identity_type"`     // 身份类型: 1-志愿者, 2-组织管理者
	Status        int32          `gorm:"column:status;not null;default:1;comment:账号状态: 0-禁用, 1-正常" json:"status"`             // 账号状态: 0-禁用, 1-正常
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:注册时间" json:"created_at"` // 注册时间
	LastLoginTime *time.Time     `gorm:"column:last_login_time;comment:最后登录时间" json:"last_login_time"`                        // 最后登录时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:软删除时间" json:"deleted_at"`                                   // 软删除时间
}

// TableName SysAccount's table name
func (*SysAccount) TableName() string {
	return TableNameSysAccount
}
