// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newActivitySignup(db *gorm.DB, opts ...gen.DOOption) activitySignup {
	_activitySignup := activitySignup{}

	_activitySignup.activitySignupDo.UseDB(db, opts...)
	_activitySignup.activitySignupDo.UseModel(&model.ActivitySignup{})

	tableName := _activitySignup.activitySignupDo.TableName()
	_activitySignup.ALL = field.NewAsterisk(tableName)
	_activitySignup.ID = field.NewInt64(tableName, "id")
	_activitySignup.ActivityID = field.NewInt64(tableName, "activity_id")
	_activitySignup.VolunteerID = field.NewInt64(tableName, "volunteer_id")
	_activitySignup.SignupTime = field.NewTime(tableName, "signup_time")
	_activitySignup.Status = field.NewInt32(tableName, "status")
	_activitySignup.CheckInStatus = field.NewInt32(tableName, "check_in_status")
	_activitySignup.CheckInTime = field.NewTime(tableName, "check_in_time")
	_activitySignup.CheckOutStatus = field.NewInt32(tableName, "check_out_status")
	_activitySignup.CheckOutTime = field.NewTime(tableName, "check_out_time")
	_activitySignup.WorkHourStatus = field.NewInt32(tableName, "work_hour_status")
	_activitySignup.WorkHourVersion = field.NewInt64(tableName, "work_hour_version")
	_activitySignup.LastWorkHourLogID = field.NewInt64(tableName, "last_work_hour_log_id")
	_activitySignup.GrantedHours = field.NewFloat64(tableName, "granted_hours")
	_activitySignup.GrantedAt = field.NewTime(tableName, "granted_at")
	_activitySignup.CreatedAt = field.NewTime(tableName, "created_at")
	_activitySignup.UpdatedAt = field.NewTime(tableName, "updated_at")

	_activitySignup.fillFieldMap()

	return _activitySignup
}

// activitySignup 活动报名记录表
type activitySignup struct {
	activitySignupDo activitySignupDo

	ALL               field.Asterisk
	ID                field.Int64   // 主键ID
	ActivityID        field.Int64   // 活动ID (关联activities.id)
	VolunteerID       field.Int64   // 志愿者ID (关联volunteers.id)
	SignupTime        field.Time    // 报名时间
	Status            field.Int32   // 状态: 1-待审核, 2-报名成功, 3-报名驳回, 4-已取消
	CheckInStatus     field.Int32   // 签到状态: 0-未签到, 1-已签到
	CheckInTime       field.Time    // 签到时间
	CheckOutStatus    field.Int32   // 签退状态：0-未签退，1-已签退
	CheckOutTime      field.Time    // 签退时间
	WorkHourStatus    field.Int32   // 工时结算状态：0-未结算，1-已发放，2-已作废
	WorkHourVersion   field.Int64   // 工时结算版本号（用于重算）
	LastWorkHourLogID field.Int64   // 最后一次生效的工时流水ID
	GrantedHours      field.Float64 // 本次报名最终发放工时
	GrantedAt         field.Time    // 工时发放时间
	CreatedAt         field.Time    // 创建时间
	UpdatedAt         field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (a activitySignup) Table(newTableName string) *activitySignup {
	a.activitySignupDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a activitySignup) As(alias string) *activitySignup {
	a.activitySignupDo.DO = *(a.activitySignupDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *activitySignup) updateTableName(table string) *activitySignup {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.ActivityID = field.NewInt64(table, "activity_id")
	a.VolunteerID = field.NewInt64(table, "volunteer_id")
	a.SignupTime = field.NewTime(table, "signup_time")
	a.Status = field.NewInt32(table, "status")
	a.CheckInStatus = field.NewInt32(table, "check_in_status")
	a.CheckInTime = field.NewTime(table, "check_in_time")
	a.CheckOutStatus = field.NewInt32(table, "check_out_status")
	a.CheckOutTime = field.NewTime(table, "check_out_time")
	a.WorkHourStatus = field.NewInt32(table, "work_hour_status")
	a.WorkHourVersion = field.NewInt64(table, "work_hour_version")
	a.LastWorkHourLogID = field.NewInt64(table, "last_work_hour_log_id")
	a.GrantedHours = field.NewFloat64(table, "granted_hours")
	a.GrantedAt = field.NewTime(table, "granted_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *activitySignup) WithContext(ctx context.Context) *activitySignupDo {
	return a.activitySignupDo.WithContext(ctx)
}

func (a activitySignup) TableName() string { return a.activitySignupDo.TableName() }

func (a activitySignup) Alias() string { return a.activitySignupDo.Alias() }

func (a activitySignup) Columns(cols ...field.Expr) gen.Columns {
	return a.activitySignupDo.Columns(cols...)
}

func (a *activitySignup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *activitySignup) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 16)
	a.fieldMap["id"] = a.ID
	a.fieldMap["activity_id"] = a.ActivityID
	a.fieldMap["volunteer_id"] = a.VolunteerID
	a.fieldMap["signup_time"] = a.SignupTime
	a.fieldMap["status"] = a.Status
	a.fieldMap["check_in_status"] = a.CheckInStatus
	a.fieldMap["check_in_time"] = a.CheckInTime
	a.fieldMap["check_out_status"] = a.CheckOutStatus
	a.fieldMap["check_out_time"] = a.CheckOutTime
	a.fieldMap["work_hour_status"] = a.WorkHourStatus
	a.fieldMap["work_hour_version"] = a.WorkHourVersion
	a.fieldMap["last_work_hour_log_id"] = a.LastWorkHourLogID
	a.fieldMap["granted_hours"] = a.GrantedHours
	a.fieldMap["granted_at"] = a.GrantedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a activitySignup) clone(db *gorm.DB) activitySignup {
	a.activitySignupDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a activitySignup) replaceDB(db *gorm.DB) activitySignup {
	a.activitySignupDo.ReplaceDB(db)
	return a
}

type activitySignupDo struct{ gen.DO }

func (a activitySignupDo) Debug() *activitySignupDo {
	return a.withDO(a.DO.Debug())
}

func (a activitySignupDo) WithContext(ctx context.Context) *activitySignupDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a activitySignupDo) ReadDB() *activitySignupDo {
	return a.Clauses(dbresolver.Read)
}

func (a activitySignupDo) WriteDB() *activitySignupDo {
	return a.Clauses(dbresolver.Write)
}

func (a activitySignupDo) Session(config *gorm.Session) *activitySignupDo {
	return a.withDO(a.DO.Session(config))
}

func (a activitySignupDo) Clauses(conds ...clause.Expression) *activitySignupDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a activitySignupDo) Returning(value interface{}, columns ...string) *activitySignupDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a activitySignupDo) Not(conds ...gen.Condition) *activitySignupDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a activitySignupDo) Or(conds ...gen.Condition) *activitySignupDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a activitySignupDo) Select(conds ...field.Expr) *activitySignupDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a activitySignupDo) Where(conds ...gen.Condition) *activitySignupDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a activitySignupDo) Order(conds ...field.Expr) *activitySignupDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a activitySignupDo) Distinct(cols ...field.Expr) *activitySignupDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a activitySignupDo) Omit(cols ...field.Expr) *activitySignupDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a activitySignupDo) Join(table schema.Tabler, on ...field.Expr) *activitySignupDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a activitySignupDo) LeftJoin(table schema.Tabler, on ...field.Expr) *activitySignupDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a activitySignupDo) RightJoin(table schema.Tabler, on ...field.Expr) *activitySignupDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a activitySignupDo) Group(cols ...field.Expr) *activitySignupDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a activitySignupDo) Having(conds ...gen.Condition) *activitySignupDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a activitySignupDo) Limit(limit int) *activitySignupDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a activitySignupDo) Offset(offset int) *activitySignupDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a activitySignupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *activitySignupDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a activitySignupDo) Unscoped() *activitySignupDo {
	return a.withDO(a.DO.Unscoped())
}

func (a activitySignupDo) Create(values ...*model.ActivitySignup) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a activitySignupDo) CreateInBatches(values []*model.ActivitySignup, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a activitySignupDo) Save(values ...*model.ActivitySignup) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a activitySignupDo) First() (*model.ActivitySignup, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivitySignup), nil
	}
}

func (a activitySignupDo) Take() (*model.ActivitySignup, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivitySignup), nil
	}
}

func (a activitySignupDo) Last() (*model.ActivitySignup, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivitySignup), nil
	}
}

func (a activitySignupDo) Find() ([]*model.ActivitySignup, error) {
	result, err := a.DO.Find()
	return result.([]*model.ActivitySignup), err
}

func (a activitySignupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ActivitySignup, err error) {
	buf := make([]*model.ActivitySignup, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a activitySignupDo) FindInBatches(result *[]*model.ActivitySignup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a activitySignupDo) Attrs(attrs ...field.AssignExpr) *activitySignupDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a activitySignupDo) Assign(attrs ...field.AssignExpr) *activitySignupDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a activitySignupDo) Joins(fields ...field.RelationField) *activitySignupDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a activitySignupDo) Preload(fields ...field.RelationField) *activitySignupDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a activitySignupDo) FirstOrInit() (*model.ActivitySignup, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivitySignup), nil
	}
}

func (a activitySignupDo) FirstOrCreate() (*model.ActivitySignup, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivitySignup), nil
	}
}

func (a activitySignupDo) FindByPage(offset int, limit int) (result []*model.ActivitySignup, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a activitySignupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a activitySignupDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a activitySignupDo) Delete(models ...*model.ActivitySignup) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *activitySignupDo) withDO(do gen.Dao) *activitySignupDo {
	a.DO = *do.(*gen.DO)
	return a
}
