// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newAiSession(db *gorm.DB, opts ...gen.DOOption) aiSession {
	_aiSession := aiSession{}

	_aiSession.aiSessionDo.UseDB(db, opts...)
	_aiSession.aiSessionDo.UseModel(&model.AiSession{})

	tableName := _aiSession.aiSessionDo.TableName()
	_aiSession.ALL = field.NewAsterisk(tableName)
	_aiSession.ID = field.NewInt64(tableName, "id")
	_aiSession.UserID = field.NewInt64(tableName, "user_id")
	_aiSession.Scene = field.NewString(tableName, "scene")
	_aiSession.Title = field.NewString(tableName, "title")
	_aiSession.Status = field.NewInt32(tableName, "status")
	_aiSession.Summary = field.NewString(tableName, "summary")
	_aiSession.LastMessageAt = field.NewTime(tableName, "last_message_at")
	_aiSession.CreatedAt = field.NewTime(tableName, "created_at")
	_aiSession.UpdatedAt = field.NewTime(tableName, "updated_at")
	_aiSession.DeletedAt = field.NewField(tableName, "deleted_at")

	_aiSession.fillFieldMap()

	return _aiSession
}

// aiSession AI 助手会话表
type aiSession struct {
	aiSessionDo aiSessionDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键ID
	UserID        field.Int64  // 用户ID（关联 sys_accounts.id）
	Scene         field.String // 会话场景：general/activity_draft/ops_advisor
	Title         field.String // 会话标题
	Status        field.Int32  // 状态：1-活跃，2-归档
	Summary       field.String // 会话摘要（可选）
	LastMessageAt field.Time   // 最后一条消息时间
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Field  // 软删除时间

	fieldMap map[string]field.Expr
}

func (a aiSession) Table(newTableName string) *aiSession {
	a.aiSessionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aiSession) As(alias string) *aiSession {
	a.aiSessionDo.DO = *(a.aiSessionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aiSession) updateTableName(table string) *aiSession {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.UserID = field.NewInt64(table, "user_id")
	a.Scene = field.NewString(table, "scene")
	a.Title = field.NewString(table, "title")
	a.Status = field.NewInt32(table, "status")
	a.Summary = field.NewString(table, "summary")
	a.LastMessageAt = field.NewTime(table, "last_message_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *aiSession) WithContext(ctx context.Context) *aiSessionDo {
	return a.aiSessionDo.WithContext(ctx)
}

func (a aiSession) TableName() string { return a.aiSessionDo.TableName() }

func (a aiSession) Alias() string { return a.aiSessionDo.Alias() }

func (a aiSession) Columns(cols ...field.Expr) gen.Columns { return a.aiSessionDo.Columns(cols...) }

func (a *aiSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aiSession) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["scene"] = a.Scene
	a.fieldMap["title"] = a.Title
	a.fieldMap["status"] = a.Status
	a.fieldMap["summary"] = a.Summary
	a.fieldMap["last_message_at"] = a.LastMessageAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a aiSession) clone(db *gorm.DB) aiSession {
	a.aiSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aiSession) replaceDB(db *gorm.DB) aiSession {
	a.aiSessionDo.ReplaceDB(db)
	return a
}

type aiSessionDo struct{ gen.DO }

func (a aiSessionDo) Debug() *aiSessionDo {
	return a.withDO(a.DO.Debug())
}

func (a aiSessionDo) WithContext(ctx context.Context) *aiSessionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aiSessionDo) ReadDB() *aiSessionDo {
	return a.Clauses(dbresolver.Read)
}

func (a aiSessionDo) WriteDB() *aiSessionDo {
	return a.Clauses(dbresolver.Write)
}

func (a aiSessionDo) Session(config *gorm.Session) *aiSessionDo {
	return a.withDO(a.DO.Session(config))
}

func (a aiSessionDo) Clauses(conds ...clause.Expression) *aiSessionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aiSessionDo) Returning(value interface{}, columns ...string) *aiSessionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aiSessionDo) Not(conds ...gen.Condition) *aiSessionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aiSessionDo) Or(conds ...gen.Condition) *aiSessionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aiSessionDo) Select(conds ...field.Expr) *aiSessionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aiSessionDo) Where(conds ...gen.Condition) *aiSessionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aiSessionDo) Order(conds ...field.Expr) *aiSessionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aiSessionDo) Distinct(cols ...field.Expr) *aiSessionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aiSessionDo) Omit(cols ...field.Expr) *aiSessionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aiSessionDo) Join(table schema.Tabler, on ...field.Expr) *aiSessionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aiSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *aiSessionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aiSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) *aiSessionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aiSessionDo) Group(cols ...field.Expr) *aiSessionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aiSessionDo) Having(conds ...gen.Condition) *aiSessionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aiSessionDo) Limit(limit int) *aiSessionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aiSessionDo) Offset(offset int) *aiSessionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aiSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *aiSessionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aiSessionDo) Unscoped() *aiSessionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aiSessionDo) Create(values ...*model.AiSession) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aiSessionDo) CreateInBatches(values []*model.AiSession, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aiSessionDo) Save(values ...*model.AiSession) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aiSessionDo) First() (*model.AiSession, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiSession), nil
	}
}

func (a aiSessionDo) Take() (*model.AiSession, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiSession), nil
	}
}

func (a aiSessionDo) Last() (*model.AiSession, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiSession), nil
	}
}

func (a aiSessionDo) Find() ([]*model.AiSession, error) {
	result, err := a.DO.Find()
	return result.([]*model.AiSession), err
}

func (a aiSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AiSession, err error) {
	buf := make([]*model.AiSession, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aiSessionDo) FindInBatches(result *[]*model.AiSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aiSessionDo) Attrs(attrs ...field.AssignExpr) *aiSessionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aiSessionDo) Assign(attrs ...field.AssignExpr) *aiSessionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aiSessionDo) Joins(fields ...field.RelationField) *aiSessionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aiSessionDo) Preload(fields ...field.RelationField) *aiSessionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aiSessionDo) FirstOrInit() (*model.AiSession, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiSession), nil
	}
}

func (a aiSessionDo) FirstOrCreate() (*model.AiSession, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiSession), nil
	}
}

func (a aiSessionDo) FindByPage(offset int, limit int) (result []*model.AiSession, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aiSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aiSessionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aiSessionDo) Delete(models ...*model.AiSession) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aiSessionDo) withDO(do gen.Dao) *aiSessionDo {
	a.DO = *do.(*gen.DO)
	return a
}
