// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newAiToolCall(db *gorm.DB, opts ...gen.DOOption) aiToolCall {
	_aiToolCall := aiToolCall{}

	_aiToolCall.aiToolCallDo.UseDB(db, opts...)
	_aiToolCall.aiToolCallDo.UseModel(&model.AiToolCall{})

	tableName := _aiToolCall.aiToolCallDo.TableName()
	_aiToolCall.ALL = field.NewAsterisk(tableName)
	_aiToolCall.ID = field.NewInt64(tableName, "id")
	_aiToolCall.SessionID = field.NewInt64(tableName, "session_id")
	_aiToolCall.MessageID = field.NewInt64(tableName, "message_id")
	_aiToolCall.ToolName = field.NewString(tableName, "tool_name")
	_aiToolCall.ToolInput = field.NewString(tableName, "tool_input")
	_aiToolCall.ToolOutput = field.NewString(tableName, "tool_output")
	_aiToolCall.Success = field.NewInt32(tableName, "success")
	_aiToolCall.ErrorCode = field.NewString(tableName, "error_code")
	_aiToolCall.ErrorMsg = field.NewString(tableName, "error_msg")
	_aiToolCall.LatencyMs = field.NewInt32(tableName, "latency_ms")
	_aiToolCall.CreatedAt = field.NewTime(tableName, "created_at")

	_aiToolCall.fillFieldMap()

	return _aiToolCall
}

// aiToolCall AI 工具调用日志表
type aiToolCall struct {
	aiToolCallDo aiToolCallDo

	ALL        field.Asterisk
	ID         field.Int64  // 主键ID
	SessionID  field.Int64  // 会话ID（关联 ai_sessions.id）
	MessageID  field.Int64  // 触发工具调用的 assistant 消息ID（关联 ai_messages.id）
	ToolName   field.String // 工具名称
	ToolInput  field.String // 工具输入参数（JSON字符串）
	ToolOutput field.String // 工具输出结果（JSON字符串）
	Success    field.Int32  // 是否成功：0-失败，1-成功
	ErrorCode  field.String // 错误码
	ErrorMsg   field.String // 错误信息
	LatencyMs  field.Int32  // 工具执行耗时（毫秒）
	CreatedAt  field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (a aiToolCall) Table(newTableName string) *aiToolCall {
	a.aiToolCallDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aiToolCall) As(alias string) *aiToolCall {
	a.aiToolCallDo.DO = *(a.aiToolCallDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aiToolCall) updateTableName(table string) *aiToolCall {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.SessionID = field.NewInt64(table, "session_id")
	a.MessageID = field.NewInt64(table, "message_id")
	a.ToolName = field.NewString(table, "tool_name")
	a.ToolInput = field.NewString(table, "tool_input")
	a.ToolOutput = field.NewString(table, "tool_output")
	a.Success = field.NewInt32(table, "success")
	a.ErrorCode = field.NewString(table, "error_code")
	a.ErrorMsg = field.NewString(table, "error_msg")
	a.LatencyMs = field.NewInt32(table, "latency_ms")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *aiToolCall) WithContext(ctx context.Context) *aiToolCallDo {
	return a.aiToolCallDo.WithContext(ctx)
}

func (a aiToolCall) TableName() string { return a.aiToolCallDo.TableName() }

func (a aiToolCall) Alias() string { return a.aiToolCallDo.Alias() }

func (a aiToolCall) Columns(cols ...field.Expr) gen.Columns { return a.aiToolCallDo.Columns(cols...) }

func (a *aiToolCall) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aiToolCall) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["session_id"] = a.SessionID
	a.fieldMap["message_id"] = a.MessageID
	a.fieldMap["tool_name"] = a.ToolName
	a.fieldMap["tool_input"] = a.ToolInput
	a.fieldMap["tool_output"] = a.ToolOutput
	a.fieldMap["success"] = a.Success
	a.fieldMap["error_code"] = a.ErrorCode
	a.fieldMap["error_msg"] = a.ErrorMsg
	a.fieldMap["latency_ms"] = a.LatencyMs
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a aiToolCall) clone(db *gorm.DB) aiToolCall {
	a.aiToolCallDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aiToolCall) replaceDB(db *gorm.DB) aiToolCall {
	a.aiToolCallDo.ReplaceDB(db)
	return a
}

type aiToolCallDo struct{ gen.DO }

func (a aiToolCallDo) Debug() *aiToolCallDo {
	return a.withDO(a.DO.Debug())
}

func (a aiToolCallDo) WithContext(ctx context.Context) *aiToolCallDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aiToolCallDo) ReadDB() *aiToolCallDo {
	return a.Clauses(dbresolver.Read)
}

func (a aiToolCallDo) WriteDB() *aiToolCallDo {
	return a.Clauses(dbresolver.Write)
}

func (a aiToolCallDo) Session(config *gorm.Session) *aiToolCallDo {
	return a.withDO(a.DO.Session(config))
}

func (a aiToolCallDo) Clauses(conds ...clause.Expression) *aiToolCallDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aiToolCallDo) Returning(value interface{}, columns ...string) *aiToolCallDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aiToolCallDo) Not(conds ...gen.Condition) *aiToolCallDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aiToolCallDo) Or(conds ...gen.Condition) *aiToolCallDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aiToolCallDo) Select(conds ...field.Expr) *aiToolCallDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aiToolCallDo) Where(conds ...gen.Condition) *aiToolCallDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aiToolCallDo) Order(conds ...field.Expr) *aiToolCallDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aiToolCallDo) Distinct(cols ...field.Expr) *aiToolCallDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aiToolCallDo) Omit(cols ...field.Expr) *aiToolCallDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aiToolCallDo) Join(table schema.Tabler, on ...field.Expr) *aiToolCallDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aiToolCallDo) LeftJoin(table schema.Tabler, on ...field.Expr) *aiToolCallDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aiToolCallDo) RightJoin(table schema.Tabler, on ...field.Expr) *aiToolCallDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aiToolCallDo) Group(cols ...field.Expr) *aiToolCallDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aiToolCallDo) Having(conds ...gen.Condition) *aiToolCallDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aiToolCallDo) Limit(limit int) *aiToolCallDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aiToolCallDo) Offset(offset int) *aiToolCallDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aiToolCallDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *aiToolCallDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aiToolCallDo) Unscoped() *aiToolCallDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aiToolCallDo) Create(values ...*model.AiToolCall) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aiToolCallDo) CreateInBatches(values []*model.AiToolCall, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aiToolCallDo) Save(values ...*model.AiToolCall) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aiToolCallDo) First() (*model.AiToolCall, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiToolCall), nil
	}
}

func (a aiToolCallDo) Take() (*model.AiToolCall, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiToolCall), nil
	}
}

func (a aiToolCallDo) Last() (*model.AiToolCall, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiToolCall), nil
	}
}

func (a aiToolCallDo) Find() ([]*model.AiToolCall, error) {
	result, err := a.DO.Find()
	return result.([]*model.AiToolCall), err
}

func (a aiToolCallDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AiToolCall, err error) {
	buf := make([]*model.AiToolCall, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aiToolCallDo) FindInBatches(result *[]*model.AiToolCall, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aiToolCallDo) Attrs(attrs ...field.AssignExpr) *aiToolCallDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aiToolCallDo) Assign(attrs ...field.AssignExpr) *aiToolCallDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aiToolCallDo) Joins(fields ...field.RelationField) *aiToolCallDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aiToolCallDo) Preload(fields ...field.RelationField) *aiToolCallDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aiToolCallDo) FirstOrInit() (*model.AiToolCall, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiToolCall), nil
	}
}

func (a aiToolCallDo) FirstOrCreate() (*model.AiToolCall, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiToolCall), nil
	}
}

func (a aiToolCallDo) FindByPage(offset int, limit int) (result []*model.AiToolCall, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aiToolCallDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aiToolCallDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aiToolCallDo) Delete(models ...*model.AiToolCall) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aiToolCallDo) withDO(do gen.Dao) *aiToolCallDo {
	a.DO = *do.(*gen.DO)
	return a
}
