// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newAiUsageDaily(db *gorm.DB, opts ...gen.DOOption) aiUsageDaily {
	_aiUsageDaily := aiUsageDaily{}

	_aiUsageDaily.aiUsageDailyDo.UseDB(db, opts...)
	_aiUsageDaily.aiUsageDailyDo.UseModel(&model.AiUsageDaily{})

	tableName := _aiUsageDaily.aiUsageDailyDo.TableName()
	_aiUsageDaily.ALL = field.NewAsterisk(tableName)
	_aiUsageDaily.ID = field.NewInt64(tableName, "id")
	_aiUsageDaily.BizDate = field.NewTime(tableName, "biz_date")
	_aiUsageDaily.UserID = field.NewInt64(tableName, "user_id")
	_aiUsageDaily.RequestCount = field.NewInt64(tableName, "request_count")
	_aiUsageDaily.SuccessCount = field.NewInt64(tableName, "success_count")
	_aiUsageDaily.FailedCount = field.NewInt64(tableName, "failed_count")
	_aiUsageDaily.TokenInTotal = field.NewInt64(tableName, "token_in_total")
	_aiUsageDaily.TokenOutTotal = field.NewInt64(tableName, "token_out_total")
	_aiUsageDaily.EstimatedCost = field.NewFloat64(tableName, "estimated_cost")
	_aiUsageDaily.CreatedAt = field.NewTime(tableName, "created_at")
	_aiUsageDaily.UpdatedAt = field.NewTime(tableName, "updated_at")

	_aiUsageDaily.fillFieldMap()

	return _aiUsageDaily
}

// aiUsageDaily AI 每日用量汇总表
type aiUsageDaily struct {
	aiUsageDailyDo aiUsageDailyDo

	ALL           field.Asterisk
	ID            field.Int64   // 主键ID
	BizDate       field.Time    // 业务日期
	UserID        field.Int64   // 用户ID（关联 sys_accounts.id）
	RequestCount  field.Int64   // 请求总数
	SuccessCount  field.Int64   // 成功请求数
	FailedCount   field.Int64   // 失败请求数
	TokenInTotal  field.Int64   // 输入token汇总
	TokenOutTotal field.Int64   // 输出token汇总
	EstimatedCost field.Float64 // 预估成本（按模型单价计算）
	CreatedAt     field.Time    // 创建时间
	UpdatedAt     field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (a aiUsageDaily) Table(newTableName string) *aiUsageDaily {
	a.aiUsageDailyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aiUsageDaily) As(alias string) *aiUsageDaily {
	a.aiUsageDailyDo.DO = *(a.aiUsageDailyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aiUsageDaily) updateTableName(table string) *aiUsageDaily {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.BizDate = field.NewTime(table, "biz_date")
	a.UserID = field.NewInt64(table, "user_id")
	a.RequestCount = field.NewInt64(table, "request_count")
	a.SuccessCount = field.NewInt64(table, "success_count")
	a.FailedCount = field.NewInt64(table, "failed_count")
	a.TokenInTotal = field.NewInt64(table, "token_in_total")
	a.TokenOutTotal = field.NewInt64(table, "token_out_total")
	a.EstimatedCost = field.NewFloat64(table, "estimated_cost")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *aiUsageDaily) WithContext(ctx context.Context) *aiUsageDailyDo {
	return a.aiUsageDailyDo.WithContext(ctx)
}

func (a aiUsageDaily) TableName() string { return a.aiUsageDailyDo.TableName() }

func (a aiUsageDaily) Alias() string { return a.aiUsageDailyDo.Alias() }

func (a aiUsageDaily) Columns(cols ...field.Expr) gen.Columns {
	return a.aiUsageDailyDo.Columns(cols...)
}

func (a *aiUsageDaily) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aiUsageDaily) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["biz_date"] = a.BizDate
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["request_count"] = a.RequestCount
	a.fieldMap["success_count"] = a.SuccessCount
	a.fieldMap["failed_count"] = a.FailedCount
	a.fieldMap["token_in_total"] = a.TokenInTotal
	a.fieldMap["token_out_total"] = a.TokenOutTotal
	a.fieldMap["estimated_cost"] = a.EstimatedCost
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a aiUsageDaily) clone(db *gorm.DB) aiUsageDaily {
	a.aiUsageDailyDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aiUsageDaily) replaceDB(db *gorm.DB) aiUsageDaily {
	a.aiUsageDailyDo.ReplaceDB(db)
	return a
}

type aiUsageDailyDo struct{ gen.DO }

func (a aiUsageDailyDo) Debug() *aiUsageDailyDo {
	return a.withDO(a.DO.Debug())
}

func (a aiUsageDailyDo) WithContext(ctx context.Context) *aiUsageDailyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aiUsageDailyDo) ReadDB() *aiUsageDailyDo {
	return a.Clauses(dbresolver.Read)
}

func (a aiUsageDailyDo) WriteDB() *aiUsageDailyDo {
	return a.Clauses(dbresolver.Write)
}

func (a aiUsageDailyDo) Session(config *gorm.Session) *aiUsageDailyDo {
	return a.withDO(a.DO.Session(config))
}

func (a aiUsageDailyDo) Clauses(conds ...clause.Expression) *aiUsageDailyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aiUsageDailyDo) Returning(value interface{}, columns ...string) *aiUsageDailyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aiUsageDailyDo) Not(conds ...gen.Condition) *aiUsageDailyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aiUsageDailyDo) Or(conds ...gen.Condition) *aiUsageDailyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aiUsageDailyDo) Select(conds ...field.Expr) *aiUsageDailyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aiUsageDailyDo) Where(conds ...gen.Condition) *aiUsageDailyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aiUsageDailyDo) Order(conds ...field.Expr) *aiUsageDailyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aiUsageDailyDo) Distinct(cols ...field.Expr) *aiUsageDailyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aiUsageDailyDo) Omit(cols ...field.Expr) *aiUsageDailyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aiUsageDailyDo) Join(table schema.Tabler, on ...field.Expr) *aiUsageDailyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aiUsageDailyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *aiUsageDailyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aiUsageDailyDo) RightJoin(table schema.Tabler, on ...field.Expr) *aiUsageDailyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aiUsageDailyDo) Group(cols ...field.Expr) *aiUsageDailyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aiUsageDailyDo) Having(conds ...gen.Condition) *aiUsageDailyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aiUsageDailyDo) Limit(limit int) *aiUsageDailyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aiUsageDailyDo) Offset(offset int) *aiUsageDailyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aiUsageDailyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *aiUsageDailyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aiUsageDailyDo) Unscoped() *aiUsageDailyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aiUsageDailyDo) Create(values ...*model.AiUsageDaily) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aiUsageDailyDo) CreateInBatches(values []*model.AiUsageDaily, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aiUsageDailyDo) Save(values ...*model.AiUsageDaily) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aiUsageDailyDo) First() (*model.AiUsageDaily, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiUsageDaily), nil
	}
}

func (a aiUsageDailyDo) Take() (*model.AiUsageDaily, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiUsageDaily), nil
	}
}

func (a aiUsageDailyDo) Last() (*model.AiUsageDaily, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiUsageDaily), nil
	}
}

func (a aiUsageDailyDo) Find() ([]*model.AiUsageDaily, error) {
	result, err := a.DO.Find()
	return result.([]*model.AiUsageDaily), err
}

func (a aiUsageDailyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AiUsageDaily, err error) {
	buf := make([]*model.AiUsageDaily, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aiUsageDailyDo) FindInBatches(result *[]*model.AiUsageDaily, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aiUsageDailyDo) Attrs(attrs ...field.AssignExpr) *aiUsageDailyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aiUsageDailyDo) Assign(attrs ...field.AssignExpr) *aiUsageDailyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aiUsageDailyDo) Joins(fields ...field.RelationField) *aiUsageDailyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aiUsageDailyDo) Preload(fields ...field.RelationField) *aiUsageDailyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aiUsageDailyDo) FirstOrInit() (*model.AiUsageDaily, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiUsageDaily), nil
	}
}

func (a aiUsageDailyDo) FirstOrCreate() (*model.AiUsageDaily, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiUsageDaily), nil
	}
}

func (a aiUsageDailyDo) FindByPage(offset int, limit int) (result []*model.AiUsageDaily, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aiUsageDailyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aiUsageDailyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aiUsageDailyDo) Delete(models ...*model.AiUsageDaily) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aiUsageDailyDo) withDO(do gen.Dao) *aiUsageDailyDo {
	a.DO = *do.(*gen.DO)
	return a
}
