// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newAuditRecord(db *gorm.DB, opts ...gen.DOOption) auditRecord {
	_auditRecord := auditRecord{}

	_auditRecord.auditRecordDo.UseDB(db, opts...)
	_auditRecord.auditRecordDo.UseModel(&model.AuditRecord{})

	tableName := _auditRecord.auditRecordDo.TableName()
	_auditRecord.ALL = field.NewAsterisk(tableName)
	_auditRecord.ID = field.NewInt64(tableName, "id")
	_auditRecord.TargetType = field.NewInt32(tableName, "target_type")
	_auditRecord.TargetID = field.NewInt64(tableName, "target_id")
	_auditRecord.CreatorID = field.NewInt64(tableName, "creator_id")
	_auditRecord.AuditorID = field.NewInt64(tableName, "auditor_id")
	_auditRecord.OldContent = field.NewString(tableName, "old_content")
	_auditRecord.NewContent = field.NewString(tableName, "new_content")
	_auditRecord.AuditResult = field.NewInt32(tableName, "audit_result")
	_auditRecord.RejectReason = field.NewString(tableName, "reject_reason")
	_auditRecord.AuditTime = field.NewTime(tableName, "audit_time")
	_auditRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_auditRecord.OperationType = field.NewInt32(tableName, "operation_type")
	_auditRecord.Status = field.NewInt32(tableName, "status")

	_auditRecord.fillFieldMap()

	return _auditRecord
}

// auditRecord 通用审核记录表
type auditRecord struct {
	auditRecordDo auditRecordDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键ID
	TargetType    field.Int32  // 审核类型: 1-志愿者实名, 2-组织资质, 3-加入组织申请, 4-活动报名
	TargetID      field.Int64  // 关联目标表的主键ID
	CreatorID     field.Int64  // 提交人账号ID(关联sys_accounts.id)
	AuditorID     field.Int64  // 审核人账号ID(关联sys_accounts.id)
	OldContent    field.String // 变更前数据快照(JSON形式)
	NewContent    field.String // 变更后数据快照(JSON形式)
	AuditResult   field.Int32  // 审核结论: 1-通过, 2-驳回
	RejectReason  field.String // 驳回原因/备注
	AuditTime     field.Time   // 审核时间
	CreatedAt     field.Time   // 创建时间
	OperationType field.Int32  // 操作类型: 1-新增, 2-更新, 3-删除
	Status        field.Int32  // 审核状态 1-待审核 2-已审核

	fieldMap map[string]field.Expr
}

func (a auditRecord) Table(newTableName string) *auditRecord {
	a.auditRecordDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a auditRecord) As(alias string) *auditRecord {
	a.auditRecordDo.DO = *(a.auditRecordDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *auditRecord) updateTableName(table string) *auditRecord {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.TargetType = field.NewInt32(table, "target_type")
	a.TargetID = field.NewInt64(table, "target_id")
	a.CreatorID = field.NewInt64(table, "creator_id")
	a.AuditorID = field.NewInt64(table, "auditor_id")
	a.OldContent = field.NewString(table, "old_content")
	a.NewContent = field.NewString(table, "new_content")
	a.AuditResult = field.NewInt32(table, "audit_result")
	a.RejectReason = field.NewString(table, "reject_reason")
	a.AuditTime = field.NewTime(table, "audit_time")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.OperationType = field.NewInt32(table, "operation_type")
	a.Status = field.NewInt32(table, "status")

	a.fillFieldMap()

	return a
}

func (a *auditRecord) WithContext(ctx context.Context) *auditRecordDo {
	return a.auditRecordDo.WithContext(ctx)
}

func (a auditRecord) TableName() string { return a.auditRecordDo.TableName() }

func (a auditRecord) Alias() string { return a.auditRecordDo.Alias() }

func (a auditRecord) Columns(cols ...field.Expr) gen.Columns { return a.auditRecordDo.Columns(cols...) }

func (a *auditRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *auditRecord) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["target_type"] = a.TargetType
	a.fieldMap["target_id"] = a.TargetID
	a.fieldMap["creator_id"] = a.CreatorID
	a.fieldMap["auditor_id"] = a.AuditorID
	a.fieldMap["old_content"] = a.OldContent
	a.fieldMap["new_content"] = a.NewContent
	a.fieldMap["audit_result"] = a.AuditResult
	a.fieldMap["reject_reason"] = a.RejectReason
	a.fieldMap["audit_time"] = a.AuditTime
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["operation_type"] = a.OperationType
	a.fieldMap["status"] = a.Status
}

func (a auditRecord) clone(db *gorm.DB) auditRecord {
	a.auditRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a auditRecord) replaceDB(db *gorm.DB) auditRecord {
	a.auditRecordDo.ReplaceDB(db)
	return a
}

type auditRecordDo struct{ gen.DO }

func (a auditRecordDo) Debug() *auditRecordDo {
	return a.withDO(a.DO.Debug())
}

func (a auditRecordDo) WithContext(ctx context.Context) *auditRecordDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a auditRecordDo) ReadDB() *auditRecordDo {
	return a.Clauses(dbresolver.Read)
}

func (a auditRecordDo) WriteDB() *auditRecordDo {
	return a.Clauses(dbresolver.Write)
}

func (a auditRecordDo) Session(config *gorm.Session) *auditRecordDo {
	return a.withDO(a.DO.Session(config))
}

func (a auditRecordDo) Clauses(conds ...clause.Expression) *auditRecordDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a auditRecordDo) Returning(value interface{}, columns ...string) *auditRecordDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a auditRecordDo) Not(conds ...gen.Condition) *auditRecordDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a auditRecordDo) Or(conds ...gen.Condition) *auditRecordDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a auditRecordDo) Select(conds ...field.Expr) *auditRecordDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a auditRecordDo) Where(conds ...gen.Condition) *auditRecordDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a auditRecordDo) Order(conds ...field.Expr) *auditRecordDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a auditRecordDo) Distinct(cols ...field.Expr) *auditRecordDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a auditRecordDo) Omit(cols ...field.Expr) *auditRecordDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a auditRecordDo) Join(table schema.Tabler, on ...field.Expr) *auditRecordDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a auditRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *auditRecordDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a auditRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *auditRecordDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a auditRecordDo) Group(cols ...field.Expr) *auditRecordDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a auditRecordDo) Having(conds ...gen.Condition) *auditRecordDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a auditRecordDo) Limit(limit int) *auditRecordDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a auditRecordDo) Offset(offset int) *auditRecordDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a auditRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *auditRecordDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a auditRecordDo) Unscoped() *auditRecordDo {
	return a.withDO(a.DO.Unscoped())
}

func (a auditRecordDo) Create(values ...*model.AuditRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a auditRecordDo) CreateInBatches(values []*model.AuditRecord, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a auditRecordDo) Save(values ...*model.AuditRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a auditRecordDo) First() (*model.AuditRecord, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditRecord), nil
	}
}

func (a auditRecordDo) Take() (*model.AuditRecord, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditRecord), nil
	}
}

func (a auditRecordDo) Last() (*model.AuditRecord, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditRecord), nil
	}
}

func (a auditRecordDo) Find() ([]*model.AuditRecord, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuditRecord), err
}

func (a auditRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuditRecord, err error) {
	buf := make([]*model.AuditRecord, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a auditRecordDo) FindInBatches(result *[]*model.AuditRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a auditRecordDo) Attrs(attrs ...field.AssignExpr) *auditRecordDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a auditRecordDo) Assign(attrs ...field.AssignExpr) *auditRecordDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a auditRecordDo) Joins(fields ...field.RelationField) *auditRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a auditRecordDo) Preload(fields ...field.RelationField) *auditRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a auditRecordDo) FirstOrInit() (*model.AuditRecord, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditRecord), nil
	}
}

func (a auditRecordDo) FirstOrCreate() (*model.AuditRecord, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditRecord), nil
	}
}

func (a auditRecordDo) FindByPage(offset int, limit int) (result []*model.AuditRecord, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a auditRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a auditRecordDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a auditRecordDo) Delete(models ...*model.AuditRecord) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *auditRecordDo) withDO(do gen.Dao) *auditRecordDo {
	a.DO = *do.(*gen.DO)
	return a
}
