// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		RbacAccountRole:    newRbacAccountRole(db, opts...),
		RbacChangeLog:      newRbacChangeLog(db, opts...),
		RbacPermission:     newRbacPermission(db, opts...),
		RbacRole:           newRbacRole(db, opts...),
		RbacRolePermission: newRbacRolePermission(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	RbacAccountRole    rbacAccountRole
	RbacChangeLog      rbacChangeLog
	RbacPermission     rbacPermission
	RbacRole           rbacRole
	RbacRolePermission rbacRolePermission
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		RbacAccountRole:    q.RbacAccountRole.clone(db),
		RbacChangeLog:      q.RbacChangeLog.clone(db),
		RbacPermission:     q.RbacPermission.clone(db),
		RbacRole:           q.RbacRole.clone(db),
		RbacRolePermission: q.RbacRolePermission.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		RbacAccountRole:    q.RbacAccountRole.replaceDB(db),
		RbacChangeLog:      q.RbacChangeLog.replaceDB(db),
		RbacPermission:     q.RbacPermission.replaceDB(db),
		RbacRole:           q.RbacRole.replaceDB(db),
		RbacRolePermission: q.RbacRolePermission.replaceDB(db),
	}
}

type queryCtx struct {
	RbacAccountRole    *rbacAccountRoleDo
	RbacChangeLog      *rbacChangeLogDo
	RbacPermission     *rbacPermissionDo
	RbacRole           *rbacRoleDo
	RbacRolePermission *rbacRolePermissionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		RbacAccountRole:    q.RbacAccountRole.WithContext(ctx),
		RbacChangeLog:      q.RbacChangeLog.WithContext(ctx),
		RbacPermission:     q.RbacPermission.WithContext(ctx),
		RbacRole:           q.RbacRole.WithContext(ctx),
		RbacRolePermission: q.RbacRolePermission.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
