// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		AiMessage:    newAiMessage(db, opts...),
		AiSession:    newAiSession(db, opts...),
		AiToolCall:   newAiToolCall(db, opts...),
		AiUsageDaily: newAiUsageDaily(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AiMessage    aiMessage
	AiSession    aiSession
	AiToolCall   aiToolCall
	AiUsageDaily aiUsageDaily
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		AiMessage:    q.AiMessage.clone(db),
		AiSession:    q.AiSession.clone(db),
		AiToolCall:   q.AiToolCall.clone(db),
		AiUsageDaily: q.AiUsageDaily.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		AiMessage:    q.AiMessage.replaceDB(db),
		AiSession:    q.AiSession.replaceDB(db),
		AiToolCall:   q.AiToolCall.replaceDB(db),
		AiUsageDaily: q.AiUsageDaily.replaceDB(db),
	}
}

type queryCtx struct {
	AiMessage    *aiMessageDo
	AiSession    *aiSessionDo
	AiToolCall   *aiToolCallDo
	AiUsageDaily *aiUsageDailyDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AiMessage:    q.AiMessage.WithContext(ctx),
		AiSession:    q.AiSession.WithContext(ctx),
		AiToolCall:   q.AiToolCall.WithContext(ctx),
		AiUsageDaily: q.AiUsageDaily.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
