// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newNotificationInbox(db *gorm.DB, opts ...gen.DOOption) notificationInbox {
	_notificationInbox := notificationInbox{}

	_notificationInbox.notificationInboxDo.UseDB(db, opts...)
	_notificationInbox.notificationInboxDo.UseModel(&model.NotificationInbox{})

	tableName := _notificationInbox.notificationInboxDo.TableName()
	_notificationInbox.ALL = field.NewAsterisk(tableName)
	_notificationInbox.ID = field.NewInt64(tableName, "id")
	_notificationInbox.NotificationID = field.NewInt64(tableName, "notification_id")
	_notificationInbox.ReceiverID = field.NewInt64(tableName, "receiver_id")
	_notificationInbox.SourceOrgID = field.NewInt64(tableName, "source_org_id")
	_notificationInbox.ReadStatus = field.NewInt32(tableName, "read_status")
	_notificationInbox.ReadAt = field.NewTime(tableName, "read_at")
	_notificationInbox.InboxStatus = field.NewInt32(tableName, "inbox_status")
	_notificationInbox.ArchivedReason = field.NewString(tableName, "archived_reason")
	_notificationInbox.ArchivedAt = field.NewTime(tableName, "archived_at")
	_notificationInbox.CreatedAt = field.NewTime(tableName, "created_at")
	_notificationInbox.UpdatedAt = field.NewTime(tableName, "updated_at")

	_notificationInbox.fillFieldMap()

	return _notificationInbox
}

// notificationInbox 用户通知收件箱
type notificationInbox struct {
	notificationInboxDo notificationInboxDo

	ALL            field.Asterisk
	ID             field.Int64  // 主键ID
	NotificationID field.Int64  // 通知内容ID(关联 notifications.id)
	ReceiverID     field.Int64  // 接收人账号ID(关联 sys_accounts.id)
	SourceOrgID    field.Int64  // 来源组织ID(冗余,便于按组织归档)
	ReadStatus     field.Int32  // 读取状态: 0-未读, 1-已读
	ReadAt         field.Time   // 读取时间
	InboxStatus    field.Int32  // 收件箱状态: 1-normal, 2-archived, 3-user_deleted
	ArchivedReason field.String // 归档原因: left_org/system_clean/user_action
	ArchivedAt     field.Time   // 归档时间
	CreatedAt      field.Time   // 入箱时间
	UpdatedAt      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (n notificationInbox) Table(newTableName string) *notificationInbox {
	n.notificationInboxDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notificationInbox) As(alias string) *notificationInbox {
	n.notificationInboxDo.DO = *(n.notificationInboxDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notificationInbox) updateTableName(table string) *notificationInbox {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NotificationID = field.NewInt64(table, "notification_id")
	n.ReceiverID = field.NewInt64(table, "receiver_id")
	n.SourceOrgID = field.NewInt64(table, "source_org_id")
	n.ReadStatus = field.NewInt32(table, "read_status")
	n.ReadAt = field.NewTime(table, "read_at")
	n.InboxStatus = field.NewInt32(table, "inbox_status")
	n.ArchivedReason = field.NewString(table, "archived_reason")
	n.ArchivedAt = field.NewTime(table, "archived_at")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *notificationInbox) WithContext(ctx context.Context) *notificationInboxDo {
	return n.notificationInboxDo.WithContext(ctx)
}

func (n notificationInbox) TableName() string { return n.notificationInboxDo.TableName() }

func (n notificationInbox) Alias() string { return n.notificationInboxDo.Alias() }

func (n notificationInbox) Columns(cols ...field.Expr) gen.Columns {
	return n.notificationInboxDo.Columns(cols...)
}

func (n *notificationInbox) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notificationInbox) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 11)
	n.fieldMap["id"] = n.ID
	n.fieldMap["notification_id"] = n.NotificationID
	n.fieldMap["receiver_id"] = n.ReceiverID
	n.fieldMap["source_org_id"] = n.SourceOrgID
	n.fieldMap["read_status"] = n.ReadStatus
	n.fieldMap["read_at"] = n.ReadAt
	n.fieldMap["inbox_status"] = n.InboxStatus
	n.fieldMap["archived_reason"] = n.ArchivedReason
	n.fieldMap["archived_at"] = n.ArchivedAt
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n notificationInbox) clone(db *gorm.DB) notificationInbox {
	n.notificationInboxDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notificationInbox) replaceDB(db *gorm.DB) notificationInbox {
	n.notificationInboxDo.ReplaceDB(db)
	return n
}

type notificationInboxDo struct{ gen.DO }

func (n notificationInboxDo) Debug() *notificationInboxDo {
	return n.withDO(n.DO.Debug())
}

func (n notificationInboxDo) WithContext(ctx context.Context) *notificationInboxDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notificationInboxDo) ReadDB() *notificationInboxDo {
	return n.Clauses(dbresolver.Read)
}

func (n notificationInboxDo) WriteDB() *notificationInboxDo {
	return n.Clauses(dbresolver.Write)
}

func (n notificationInboxDo) Session(config *gorm.Session) *notificationInboxDo {
	return n.withDO(n.DO.Session(config))
}

func (n notificationInboxDo) Clauses(conds ...clause.Expression) *notificationInboxDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notificationInboxDo) Returning(value interface{}, columns ...string) *notificationInboxDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notificationInboxDo) Not(conds ...gen.Condition) *notificationInboxDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notificationInboxDo) Or(conds ...gen.Condition) *notificationInboxDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notificationInboxDo) Select(conds ...field.Expr) *notificationInboxDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notificationInboxDo) Where(conds ...gen.Condition) *notificationInboxDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notificationInboxDo) Order(conds ...field.Expr) *notificationInboxDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notificationInboxDo) Distinct(cols ...field.Expr) *notificationInboxDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notificationInboxDo) Omit(cols ...field.Expr) *notificationInboxDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notificationInboxDo) Join(table schema.Tabler, on ...field.Expr) *notificationInboxDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notificationInboxDo) LeftJoin(table schema.Tabler, on ...field.Expr) *notificationInboxDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notificationInboxDo) RightJoin(table schema.Tabler, on ...field.Expr) *notificationInboxDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notificationInboxDo) Group(cols ...field.Expr) *notificationInboxDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notificationInboxDo) Having(conds ...gen.Condition) *notificationInboxDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notificationInboxDo) Limit(limit int) *notificationInboxDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notificationInboxDo) Offset(offset int) *notificationInboxDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notificationInboxDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *notificationInboxDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notificationInboxDo) Unscoped() *notificationInboxDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notificationInboxDo) Create(values ...*model.NotificationInbox) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notificationInboxDo) CreateInBatches(values []*model.NotificationInbox, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notificationInboxDo) Save(values ...*model.NotificationInbox) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notificationInboxDo) First() (*model.NotificationInbox, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationInbox), nil
	}
}

func (n notificationInboxDo) Take() (*model.NotificationInbox, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationInbox), nil
	}
}

func (n notificationInboxDo) Last() (*model.NotificationInbox, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationInbox), nil
	}
}

func (n notificationInboxDo) Find() ([]*model.NotificationInbox, error) {
	result, err := n.DO.Find()
	return result.([]*model.NotificationInbox), err
}

func (n notificationInboxDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationInbox, err error) {
	buf := make([]*model.NotificationInbox, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notificationInboxDo) FindInBatches(result *[]*model.NotificationInbox, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notificationInboxDo) Attrs(attrs ...field.AssignExpr) *notificationInboxDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notificationInboxDo) Assign(attrs ...field.AssignExpr) *notificationInboxDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notificationInboxDo) Joins(fields ...field.RelationField) *notificationInboxDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notificationInboxDo) Preload(fields ...field.RelationField) *notificationInboxDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notificationInboxDo) FirstOrInit() (*model.NotificationInbox, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationInbox), nil
	}
}

func (n notificationInboxDo) FirstOrCreate() (*model.NotificationInbox, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationInbox), nil
	}
}

func (n notificationInboxDo) FindByPage(offset int, limit int) (result []*model.NotificationInbox, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notificationInboxDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notificationInboxDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notificationInboxDo) Delete(models ...*model.NotificationInbox) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notificationInboxDo) withDO(do gen.Dao) *notificationInboxDo {
	n.DO = *do.(*gen.DO)
	return n
}
