// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newOrgMember(db *gorm.DB, opts ...gen.DOOption) orgMember {
	_orgMember := orgMember{}

	_orgMember.orgMemberDo.UseDB(db, opts...)
	_orgMember.orgMemberDo.UseModel(&model.OrgMember{})

	tableName := _orgMember.orgMemberDo.TableName()
	_orgMember.ALL = field.NewAsterisk(tableName)
	_orgMember.ID = field.NewInt64(tableName, "id")
	_orgMember.OrgID = field.NewInt64(tableName, "org_id")
	_orgMember.VolunteerID = field.NewInt64(tableName, "volunteer_id")
	_orgMember.Role = field.NewInt32(tableName, "role")
	_orgMember.Status = field.NewInt32(tableName, "status")
	_orgMember.AppliedAt = field.NewTime(tableName, "applied_at")
	_orgMember.JoinedAt = field.NewTime(tableName, "joined_at")
	_orgMember.CreatedAt = field.NewTime(tableName, "created_at")
	_orgMember.UpdatedAt = field.NewTime(tableName, "updated_at")

	_orgMember.fillFieldMap()

	return _orgMember
}

// orgMember 组织成员关联表
type orgMember struct {
	orgMemberDo orgMemberDo

	ALL         field.Asterisk
	ID          field.Int64 // 主键ID
	OrgID       field.Int64 // 组织ID (关联organizations.id)
	VolunteerID field.Int64 // 志愿者ID (关联volunteers.id)
	Role        field.Int32 // 角色: 1-普通成员, 2-管理员, 3-负责人
	Status      field.Int32 // 成员状态: 1-待审核, 2-正式成员, 3-已拒绝, 4-已退出
	AppliedAt   field.Time  // 申请时间
	JoinedAt    field.Time  // 正式加入时间
	CreatedAt   field.Time  // 创建时间
	UpdatedAt   field.Time  // 更新时间

	fieldMap map[string]field.Expr
}

func (o orgMember) Table(newTableName string) *orgMember {
	o.orgMemberDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o orgMember) As(alias string) *orgMember {
	o.orgMemberDo.DO = *(o.orgMemberDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *orgMember) updateTableName(table string) *orgMember {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.OrgID = field.NewInt64(table, "org_id")
	o.VolunteerID = field.NewInt64(table, "volunteer_id")
	o.Role = field.NewInt32(table, "role")
	o.Status = field.NewInt32(table, "status")
	o.AppliedAt = field.NewTime(table, "applied_at")
	o.JoinedAt = field.NewTime(table, "joined_at")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *orgMember) WithContext(ctx context.Context) *orgMemberDo {
	return o.orgMemberDo.WithContext(ctx)
}

func (o orgMember) TableName() string { return o.orgMemberDo.TableName() }

func (o orgMember) Alias() string { return o.orgMemberDo.Alias() }

func (o orgMember) Columns(cols ...field.Expr) gen.Columns { return o.orgMemberDo.Columns(cols...) }

func (o *orgMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *orgMember) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 9)
	o.fieldMap["id"] = o.ID
	o.fieldMap["org_id"] = o.OrgID
	o.fieldMap["volunteer_id"] = o.VolunteerID
	o.fieldMap["role"] = o.Role
	o.fieldMap["status"] = o.Status
	o.fieldMap["applied_at"] = o.AppliedAt
	o.fieldMap["joined_at"] = o.JoinedAt
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
}

func (o orgMember) clone(db *gorm.DB) orgMember {
	o.orgMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o orgMember) replaceDB(db *gorm.DB) orgMember {
	o.orgMemberDo.ReplaceDB(db)
	return o
}

type orgMemberDo struct{ gen.DO }

func (o orgMemberDo) Debug() *orgMemberDo {
	return o.withDO(o.DO.Debug())
}

func (o orgMemberDo) WithContext(ctx context.Context) *orgMemberDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orgMemberDo) ReadDB() *orgMemberDo {
	return o.Clauses(dbresolver.Read)
}

func (o orgMemberDo) WriteDB() *orgMemberDo {
	return o.Clauses(dbresolver.Write)
}

func (o orgMemberDo) Session(config *gorm.Session) *orgMemberDo {
	return o.withDO(o.DO.Session(config))
}

func (o orgMemberDo) Clauses(conds ...clause.Expression) *orgMemberDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orgMemberDo) Returning(value interface{}, columns ...string) *orgMemberDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orgMemberDo) Not(conds ...gen.Condition) *orgMemberDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orgMemberDo) Or(conds ...gen.Condition) *orgMemberDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orgMemberDo) Select(conds ...field.Expr) *orgMemberDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orgMemberDo) Where(conds ...gen.Condition) *orgMemberDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orgMemberDo) Order(conds ...field.Expr) *orgMemberDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orgMemberDo) Distinct(cols ...field.Expr) *orgMemberDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orgMemberDo) Omit(cols ...field.Expr) *orgMemberDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orgMemberDo) Join(table schema.Tabler, on ...field.Expr) *orgMemberDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orgMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) *orgMemberDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orgMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) *orgMemberDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orgMemberDo) Group(cols ...field.Expr) *orgMemberDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orgMemberDo) Having(conds ...gen.Condition) *orgMemberDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orgMemberDo) Limit(limit int) *orgMemberDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orgMemberDo) Offset(offset int) *orgMemberDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orgMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *orgMemberDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orgMemberDo) Unscoped() *orgMemberDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orgMemberDo) Create(values ...*model.OrgMember) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orgMemberDo) CreateInBatches(values []*model.OrgMember, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orgMemberDo) Save(values ...*model.OrgMember) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orgMemberDo) First() (*model.OrgMember, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrgMember), nil
	}
}

func (o orgMemberDo) Take() (*model.OrgMember, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrgMember), nil
	}
}

func (o orgMemberDo) Last() (*model.OrgMember, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrgMember), nil
	}
}

func (o orgMemberDo) Find() ([]*model.OrgMember, error) {
	result, err := o.DO.Find()
	return result.([]*model.OrgMember), err
}

func (o orgMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrgMember, err error) {
	buf := make([]*model.OrgMember, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orgMemberDo) FindInBatches(result *[]*model.OrgMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orgMemberDo) Attrs(attrs ...field.AssignExpr) *orgMemberDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orgMemberDo) Assign(attrs ...field.AssignExpr) *orgMemberDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orgMemberDo) Joins(fields ...field.RelationField) *orgMemberDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orgMemberDo) Preload(fields ...field.RelationField) *orgMemberDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orgMemberDo) FirstOrInit() (*model.OrgMember, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrgMember), nil
	}
}

func (o orgMemberDo) FirstOrCreate() (*model.OrgMember, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrgMember), nil
	}
}

func (o orgMemberDo) FindByPage(offset int, limit int) (result []*model.OrgMember, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orgMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orgMemberDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orgMemberDo) Delete(models ...*model.OrgMember) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orgMemberDo) withDO(do gen.Dao) *orgMemberDo {
	o.DO = *do.(*gen.DO)
	return o
}
