// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newRbacAccountRole(db *gorm.DB, opts ...gen.DOOption) rbacAccountRole {
	_rbacAccountRole := rbacAccountRole{}

	_rbacAccountRole.rbacAccountRoleDo.UseDB(db, opts...)
	_rbacAccountRole.rbacAccountRoleDo.UseModel(&model.RbacAccountRole{})

	tableName := _rbacAccountRole.rbacAccountRoleDo.TableName()
	_rbacAccountRole.ALL = field.NewAsterisk(tableName)
	_rbacAccountRole.ID = field.NewInt64(tableName, "id")
	_rbacAccountRole.AccountID = field.NewInt64(tableName, "account_id")
	_rbacAccountRole.RoleID = field.NewInt64(tableName, "role_id")
	_rbacAccountRole.ScopeType = field.NewString(tableName, "scope_type")
	_rbacAccountRole.ScopeID = field.NewInt64(tableName, "scope_id")
	_rbacAccountRole.Status = field.NewInt32(tableName, "status")
	_rbacAccountRole.GrantedBy = field.NewInt64(tableName, "granted_by")
	_rbacAccountRole.ExpiresAt = field.NewTime(tableName, "expires_at")
	_rbacAccountRole.CreatedAt = field.NewTime(tableName, "created_at")
	_rbacAccountRole.UpdatedAt = field.NewTime(tableName, "updated_at")

	_rbacAccountRole.fillFieldMap()

	return _rbacAccountRole
}

// rbacAccountRole RBAC 账号角色授权表
type rbacAccountRole struct {
	rbacAccountRoleDo rbacAccountRoleDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键ID
	AccountID field.Int64  // 账号ID（关联 sys_accounts.id）
	RoleID    field.Int64  // 角色ID（关联 rbac_roles.id）
	ScopeType field.String // 作用域类型：global/org
	ScopeID   field.Int64  // 作用域ID（global 固定为0，org 为 organizations.id）
	Status    field.Int32  // 状态：1-启用，0-禁用
	GrantedBy field.Int64  // 授权人账号ID
	ExpiresAt field.Time   // 过期时间（为空表示不过期）
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (r rbacAccountRole) Table(newTableName string) *rbacAccountRole {
	r.rbacAccountRoleDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rbacAccountRole) As(alias string) *rbacAccountRole {
	r.rbacAccountRoleDo.DO = *(r.rbacAccountRoleDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rbacAccountRole) updateTableName(table string) *rbacAccountRole {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.AccountID = field.NewInt64(table, "account_id")
	r.RoleID = field.NewInt64(table, "role_id")
	r.ScopeType = field.NewString(table, "scope_type")
	r.ScopeID = field.NewInt64(table, "scope_id")
	r.Status = field.NewInt32(table, "status")
	r.GrantedBy = field.NewInt64(table, "granted_by")
	r.ExpiresAt = field.NewTime(table, "expires_at")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *rbacAccountRole) WithContext(ctx context.Context) *rbacAccountRoleDo {
	return r.rbacAccountRoleDo.WithContext(ctx)
}

func (r rbacAccountRole) TableName() string { return r.rbacAccountRoleDo.TableName() }

func (r rbacAccountRole) Alias() string { return r.rbacAccountRoleDo.Alias() }

func (r rbacAccountRole) Columns(cols ...field.Expr) gen.Columns {
	return r.rbacAccountRoleDo.Columns(cols...)
}

func (r *rbacAccountRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rbacAccountRole) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["id"] = r.ID
	r.fieldMap["account_id"] = r.AccountID
	r.fieldMap["role_id"] = r.RoleID
	r.fieldMap["scope_type"] = r.ScopeType
	r.fieldMap["scope_id"] = r.ScopeID
	r.fieldMap["status"] = r.Status
	r.fieldMap["granted_by"] = r.GrantedBy
	r.fieldMap["expires_at"] = r.ExpiresAt
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r rbacAccountRole) clone(db *gorm.DB) rbacAccountRole {
	r.rbacAccountRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rbacAccountRole) replaceDB(db *gorm.DB) rbacAccountRole {
	r.rbacAccountRoleDo.ReplaceDB(db)
	return r
}

type rbacAccountRoleDo struct{ gen.DO }

func (r rbacAccountRoleDo) Debug() *rbacAccountRoleDo {
	return r.withDO(r.DO.Debug())
}

func (r rbacAccountRoleDo) WithContext(ctx context.Context) *rbacAccountRoleDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rbacAccountRoleDo) ReadDB() *rbacAccountRoleDo {
	return r.Clauses(dbresolver.Read)
}

func (r rbacAccountRoleDo) WriteDB() *rbacAccountRoleDo {
	return r.Clauses(dbresolver.Write)
}

func (r rbacAccountRoleDo) Session(config *gorm.Session) *rbacAccountRoleDo {
	return r.withDO(r.DO.Session(config))
}

func (r rbacAccountRoleDo) Clauses(conds ...clause.Expression) *rbacAccountRoleDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rbacAccountRoleDo) Returning(value interface{}, columns ...string) *rbacAccountRoleDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rbacAccountRoleDo) Not(conds ...gen.Condition) *rbacAccountRoleDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rbacAccountRoleDo) Or(conds ...gen.Condition) *rbacAccountRoleDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rbacAccountRoleDo) Select(conds ...field.Expr) *rbacAccountRoleDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rbacAccountRoleDo) Where(conds ...gen.Condition) *rbacAccountRoleDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rbacAccountRoleDo) Order(conds ...field.Expr) *rbacAccountRoleDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rbacAccountRoleDo) Distinct(cols ...field.Expr) *rbacAccountRoleDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rbacAccountRoleDo) Omit(cols ...field.Expr) *rbacAccountRoleDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rbacAccountRoleDo) Join(table schema.Tabler, on ...field.Expr) *rbacAccountRoleDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rbacAccountRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *rbacAccountRoleDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rbacAccountRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) *rbacAccountRoleDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rbacAccountRoleDo) Group(cols ...field.Expr) *rbacAccountRoleDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rbacAccountRoleDo) Having(conds ...gen.Condition) *rbacAccountRoleDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rbacAccountRoleDo) Limit(limit int) *rbacAccountRoleDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rbacAccountRoleDo) Offset(offset int) *rbacAccountRoleDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rbacAccountRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *rbacAccountRoleDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rbacAccountRoleDo) Unscoped() *rbacAccountRoleDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rbacAccountRoleDo) Create(values ...*model.RbacAccountRole) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rbacAccountRoleDo) CreateInBatches(values []*model.RbacAccountRole, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rbacAccountRoleDo) Save(values ...*model.RbacAccountRole) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rbacAccountRoleDo) First() (*model.RbacAccountRole, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacAccountRole), nil
	}
}

func (r rbacAccountRoleDo) Take() (*model.RbacAccountRole, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacAccountRole), nil
	}
}

func (r rbacAccountRoleDo) Last() (*model.RbacAccountRole, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacAccountRole), nil
	}
}

func (r rbacAccountRoleDo) Find() ([]*model.RbacAccountRole, error) {
	result, err := r.DO.Find()
	return result.([]*model.RbacAccountRole), err
}

func (r rbacAccountRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RbacAccountRole, err error) {
	buf := make([]*model.RbacAccountRole, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rbacAccountRoleDo) FindInBatches(result *[]*model.RbacAccountRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rbacAccountRoleDo) Attrs(attrs ...field.AssignExpr) *rbacAccountRoleDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rbacAccountRoleDo) Assign(attrs ...field.AssignExpr) *rbacAccountRoleDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rbacAccountRoleDo) Joins(fields ...field.RelationField) *rbacAccountRoleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rbacAccountRoleDo) Preload(fields ...field.RelationField) *rbacAccountRoleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rbacAccountRoleDo) FirstOrInit() (*model.RbacAccountRole, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacAccountRole), nil
	}
}

func (r rbacAccountRoleDo) FirstOrCreate() (*model.RbacAccountRole, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacAccountRole), nil
	}
}

func (r rbacAccountRoleDo) FindByPage(offset int, limit int) (result []*model.RbacAccountRole, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rbacAccountRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rbacAccountRoleDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rbacAccountRoleDo) Delete(models ...*model.RbacAccountRole) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rbacAccountRoleDo) withDO(do gen.Dao) *rbacAccountRoleDo {
	r.DO = *do.(*gen.DO)
	return r
}
