// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newSysAccount(db *gorm.DB, opts ...gen.DOOption) sysAccount {
	_sysAccount := sysAccount{}

	_sysAccount.sysAccountDo.UseDB(db, opts...)
	_sysAccount.sysAccountDo.UseModel(&model.SysAccount{})

	tableName := _sysAccount.sysAccountDo.TableName()
	_sysAccount.ALL = field.NewAsterisk(tableName)
	_sysAccount.ID = field.NewInt64(tableName, "id")
	_sysAccount.Username = field.NewString(tableName, "username")
	_sysAccount.Mobile = field.NewString(tableName, "mobile")
	_sysAccount.MobileHash = field.NewString(tableName, "mobile_hash")
	_sysAccount.Email = field.NewString(tableName, "email")
	_sysAccount.Password = field.NewString(tableName, "password")
	_sysAccount.IdentityType = field.NewInt32(tableName, "identity_type")
	_sysAccount.Status = field.NewInt32(tableName, "status")
	_sysAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_sysAccount.LastLoginTime = field.NewTime(tableName, "last_login_time")
	_sysAccount.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysAccount.DeletedAt = field.NewField(tableName, "deleted_at")

	_sysAccount.fillFieldMap()

	return _sysAccount
}

// sysAccount 用户账号主表（所有用户的基础登录信息）
type sysAccount struct {
	sysAccountDo sysAccountDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键ID
	Username      field.String // 用户名
	Mobile        field.String // 手机号 (AES-GCM加密后存储)
	MobileHash    field.String // 手机号哈希值 (SHA-256, 用于唯一性检查)
	Email         field.String // 邮箱 (唯一登录标识)
	Password      field.String // 加密后的密码 (建议使用BCrypt)
	IdentityType  field.Int32  // 身份类型: 1-志愿者, 2-组织管理者
	Status        field.Int32  // 账号状态: 0-禁用, 1-正常
	CreatedAt     field.Time   // 注册时间
	LastLoginTime field.Time   // 最后登录时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Field  // 软删除时间

	fieldMap map[string]field.Expr
}

func (s sysAccount) Table(newTableName string) *sysAccount {
	s.sysAccountDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysAccount) As(alias string) *sysAccount {
	s.sysAccountDo.DO = *(s.sysAccountDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysAccount) updateTableName(table string) *sysAccount {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Username = field.NewString(table, "username")
	s.Mobile = field.NewString(table, "mobile")
	s.MobileHash = field.NewString(table, "mobile_hash")
	s.Email = field.NewString(table, "email")
	s.Password = field.NewString(table, "password")
	s.IdentityType = field.NewInt32(table, "identity_type")
	s.Status = field.NewInt32(table, "status")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.LastLoginTime = field.NewTime(table, "last_login_time")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sysAccount) WithContext(ctx context.Context) *sysAccountDo {
	return s.sysAccountDo.WithContext(ctx)
}

func (s sysAccount) TableName() string { return s.sysAccountDo.TableName() }

func (s sysAccount) Alias() string { return s.sysAccountDo.Alias() }

func (s sysAccount) Columns(cols ...field.Expr) gen.Columns { return s.sysAccountDo.Columns(cols...) }

func (s *sysAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysAccount) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["username"] = s.Username
	s.fieldMap["mobile"] = s.Mobile
	s.fieldMap["mobile_hash"] = s.MobileHash
	s.fieldMap["email"] = s.Email
	s.fieldMap["password"] = s.Password
	s.fieldMap["identity_type"] = s.IdentityType
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["last_login_time"] = s.LastLoginTime
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s sysAccount) clone(db *gorm.DB) sysAccount {
	s.sysAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysAccount) replaceDB(db *gorm.DB) sysAccount {
	s.sysAccountDo.ReplaceDB(db)
	return s
}

type sysAccountDo struct{ gen.DO }

func (s sysAccountDo) Debug() *sysAccountDo {
	return s.withDO(s.DO.Debug())
}

func (s sysAccountDo) WithContext(ctx context.Context) *sysAccountDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysAccountDo) ReadDB() *sysAccountDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysAccountDo) WriteDB() *sysAccountDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysAccountDo) Session(config *gorm.Session) *sysAccountDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysAccountDo) Clauses(conds ...clause.Expression) *sysAccountDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysAccountDo) Returning(value interface{}, columns ...string) *sysAccountDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysAccountDo) Not(conds ...gen.Condition) *sysAccountDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysAccountDo) Or(conds ...gen.Condition) *sysAccountDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysAccountDo) Select(conds ...field.Expr) *sysAccountDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysAccountDo) Where(conds ...gen.Condition) *sysAccountDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysAccountDo) Order(conds ...field.Expr) *sysAccountDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysAccountDo) Distinct(cols ...field.Expr) *sysAccountDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysAccountDo) Omit(cols ...field.Expr) *sysAccountDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysAccountDo) Join(table schema.Tabler, on ...field.Expr) *sysAccountDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysAccountDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysAccountDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysAccountDo) Group(cols ...field.Expr) *sysAccountDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysAccountDo) Having(conds ...gen.Condition) *sysAccountDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysAccountDo) Limit(limit int) *sysAccountDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysAccountDo) Offset(offset int) *sysAccountDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysAccountDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysAccountDo) Unscoped() *sysAccountDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysAccountDo) Create(values ...*model.SysAccount) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysAccountDo) CreateInBatches(values []*model.SysAccount, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysAccountDo) Save(values ...*model.SysAccount) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysAccountDo) First() (*model.SysAccount, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccount), nil
	}
}

func (s sysAccountDo) Take() (*model.SysAccount, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccount), nil
	}
}

func (s sysAccountDo) Last() (*model.SysAccount, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccount), nil
	}
}

func (s sysAccountDo) Find() ([]*model.SysAccount, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysAccount), err
}

func (s sysAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAccount, err error) {
	buf := make([]*model.SysAccount, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysAccountDo) FindInBatches(result *[]*model.SysAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysAccountDo) Attrs(attrs ...field.AssignExpr) *sysAccountDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysAccountDo) Assign(attrs ...field.AssignExpr) *sysAccountDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysAccountDo) Joins(fields ...field.RelationField) *sysAccountDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysAccountDo) Preload(fields ...field.RelationField) *sysAccountDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysAccountDo) FirstOrInit() (*model.SysAccount, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccount), nil
	}
}

func (s sysAccountDo) FirstOrCreate() (*model.SysAccount, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccount), nil
	}
}

func (s sysAccountDo) FindByPage(offset int, limit int) (result []*model.SysAccount, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysAccountDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysAccountDo) Delete(models ...*model.SysAccount) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysAccountDo) withDO(do gen.Dao) *sysAccountDo {
	s.DO = *do.(*gen.DO)
	return s
}
