// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"volunteer-system/internal/model"
)

func newWorkHourLog(db *gorm.DB, opts ...gen.DOOption) workHourLog {
	_workHourLog := workHourLog{}

	_workHourLog.workHourLogDo.UseDB(db, opts...)
	_workHourLog.workHourLogDo.UseModel(&model.WorkHourLog{})

	tableName := _workHourLog.workHourLogDo.TableName()
	_workHourLog.ALL = field.NewAsterisk(tableName)
	_workHourLog.ID = field.NewInt64(tableName, "id")
	_workHourLog.VolunteerID = field.NewInt64(tableName, "volunteer_id")
	_workHourLog.ActivityID = field.NewInt64(tableName, "activity_id")
	_workHourLog.SignupID = field.NewInt64(tableName, "signup_id")
	_workHourLog.OperationType = field.NewInt32(tableName, "operation_type")
	_workHourLog.HoursDelta = field.NewFloat64(tableName, "hours_delta")
	_workHourLog.ServiceCountDelta = field.NewInt64(tableName, "service_count_delta")
	_workHourLog.BeforeTotalHours = field.NewFloat64(tableName, "before_total_hours")
	_workHourLog.AfterTotalHours = field.NewFloat64(tableName, "after_total_hours")
	_workHourLog.BeforeServiceCount = field.NewInt64(tableName, "before_service_count")
	_workHourLog.AfterServiceCount = field.NewInt64(tableName, "after_service_count")
	_workHourLog.WorkHourVersion = field.NewInt64(tableName, "work_hour_version")
	_workHourLog.IdempotencyKey = field.NewString(tableName, "idempotency_key")
	_workHourLog.RefLogID = field.NewInt64(tableName, "ref_log_id")
	_workHourLog.Reason = field.NewString(tableName, "reason")
	_workHourLog.OperatorID = field.NewInt64(tableName, "operator_id")
	_workHourLog.CreatedAt = field.NewTime(tableName, "created_at")
	_workHourLog.UpdatedAt = field.NewTime(tableName, "updated_at")

	_workHourLog.fillFieldMap()

	return _workHourLog
}

// workHourLog 志愿工时流水表
type workHourLog struct {
	workHourLogDo workHourLogDo

	ALL                field.Asterisk
	ID                 field.Int64   // 主键ID
	VolunteerID        field.Int64   // 志愿者ID（关联 volunteers.id）
	ActivityID         field.Int64   // 活动ID（关联 activities.id）
	SignupID           field.Int64   // 报名ID（关联 activity_signups.id）
	OperationType      field.Int32   // 操作类型：1-发放，2-作废，3-重发
	HoursDelta         field.Float64 // 工时增量（作废时可为负数）
	ServiceCountDelta  field.Int64   // 服务次数增量
	BeforeTotalHours   field.Float64 // 变更前累计工时
	AfterTotalHours    field.Float64 // 变更后累计工时
	BeforeServiceCount field.Int64   // 变更前累计服务次数
	AfterServiceCount  field.Int64   // 变更后累计服务次数
	WorkHourVersion    field.Int64   // 结算版本号（与报名表保持一致）
	IdempotencyKey     field.String  // 幂等键（防重复发放/作废/重发）
	RefLogID           field.Int64   // 关联原流水ID（作废/重发场景）
	Reason             field.String  // 作废或重发原因
	OperatorID         field.Int64   // 操作人账号ID
	CreatedAt          field.Time    // 创建时间
	UpdatedAt          field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (w workHourLog) Table(newTableName string) *workHourLog {
	w.workHourLogDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workHourLog) As(alias string) *workHourLog {
	w.workHourLogDo.DO = *(w.workHourLogDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workHourLog) updateTableName(table string) *workHourLog {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.VolunteerID = field.NewInt64(table, "volunteer_id")
	w.ActivityID = field.NewInt64(table, "activity_id")
	w.SignupID = field.NewInt64(table, "signup_id")
	w.OperationType = field.NewInt32(table, "operation_type")
	w.HoursDelta = field.NewFloat64(table, "hours_delta")
	w.ServiceCountDelta = field.NewInt64(table, "service_count_delta")
	w.BeforeTotalHours = field.NewFloat64(table, "before_total_hours")
	w.AfterTotalHours = field.NewFloat64(table, "after_total_hours")
	w.BeforeServiceCount = field.NewInt64(table, "before_service_count")
	w.AfterServiceCount = field.NewInt64(table, "after_service_count")
	w.WorkHourVersion = field.NewInt64(table, "work_hour_version")
	w.IdempotencyKey = field.NewString(table, "idempotency_key")
	w.RefLogID = field.NewInt64(table, "ref_log_id")
	w.Reason = field.NewString(table, "reason")
	w.OperatorID = field.NewInt64(table, "operator_id")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *workHourLog) WithContext(ctx context.Context) *workHourLogDo {
	return w.workHourLogDo.WithContext(ctx)
}

func (w workHourLog) TableName() string { return w.workHourLogDo.TableName() }

func (w workHourLog) Alias() string { return w.workHourLogDo.Alias() }

func (w workHourLog) Columns(cols ...field.Expr) gen.Columns { return w.workHourLogDo.Columns(cols...) }

func (w *workHourLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workHourLog) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 18)
	w.fieldMap["id"] = w.ID
	w.fieldMap["volunteer_id"] = w.VolunteerID
	w.fieldMap["activity_id"] = w.ActivityID
	w.fieldMap["signup_id"] = w.SignupID
	w.fieldMap["operation_type"] = w.OperationType
	w.fieldMap["hours_delta"] = w.HoursDelta
	w.fieldMap["service_count_delta"] = w.ServiceCountDelta
	w.fieldMap["before_total_hours"] = w.BeforeTotalHours
	w.fieldMap["after_total_hours"] = w.AfterTotalHours
	w.fieldMap["before_service_count"] = w.BeforeServiceCount
	w.fieldMap["after_service_count"] = w.AfterServiceCount
	w.fieldMap["work_hour_version"] = w.WorkHourVersion
	w.fieldMap["idempotency_key"] = w.IdempotencyKey
	w.fieldMap["ref_log_id"] = w.RefLogID
	w.fieldMap["reason"] = w.Reason
	w.fieldMap["operator_id"] = w.OperatorID
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w workHourLog) clone(db *gorm.DB) workHourLog {
	w.workHourLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w workHourLog) replaceDB(db *gorm.DB) workHourLog {
	w.workHourLogDo.ReplaceDB(db)
	return w
}

type workHourLogDo struct{ gen.DO }

func (w workHourLogDo) Debug() *workHourLogDo {
	return w.withDO(w.DO.Debug())
}

func (w workHourLogDo) WithContext(ctx context.Context) *workHourLogDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workHourLogDo) ReadDB() *workHourLogDo {
	return w.Clauses(dbresolver.Read)
}

func (w workHourLogDo) WriteDB() *workHourLogDo {
	return w.Clauses(dbresolver.Write)
}

func (w workHourLogDo) Session(config *gorm.Session) *workHourLogDo {
	return w.withDO(w.DO.Session(config))
}

func (w workHourLogDo) Clauses(conds ...clause.Expression) *workHourLogDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workHourLogDo) Returning(value interface{}, columns ...string) *workHourLogDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workHourLogDo) Not(conds ...gen.Condition) *workHourLogDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workHourLogDo) Or(conds ...gen.Condition) *workHourLogDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workHourLogDo) Select(conds ...field.Expr) *workHourLogDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workHourLogDo) Where(conds ...gen.Condition) *workHourLogDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workHourLogDo) Order(conds ...field.Expr) *workHourLogDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workHourLogDo) Distinct(cols ...field.Expr) *workHourLogDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workHourLogDo) Omit(cols ...field.Expr) *workHourLogDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workHourLogDo) Join(table schema.Tabler, on ...field.Expr) *workHourLogDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workHourLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *workHourLogDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workHourLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *workHourLogDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workHourLogDo) Group(cols ...field.Expr) *workHourLogDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workHourLogDo) Having(conds ...gen.Condition) *workHourLogDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workHourLogDo) Limit(limit int) *workHourLogDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workHourLogDo) Offset(offset int) *workHourLogDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workHourLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *workHourLogDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workHourLogDo) Unscoped() *workHourLogDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workHourLogDo) Create(values ...*model.WorkHourLog) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workHourLogDo) CreateInBatches(values []*model.WorkHourLog, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workHourLogDo) Save(values ...*model.WorkHourLog) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workHourLogDo) First() (*model.WorkHourLog, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkHourLog), nil
	}
}

func (w workHourLogDo) Take() (*model.WorkHourLog, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkHourLog), nil
	}
}

func (w workHourLogDo) Last() (*model.WorkHourLog, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkHourLog), nil
	}
}

func (w workHourLogDo) Find() ([]*model.WorkHourLog, error) {
	result, err := w.DO.Find()
	return result.([]*model.WorkHourLog), err
}

func (w workHourLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkHourLog, err error) {
	buf := make([]*model.WorkHourLog, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workHourLogDo) FindInBatches(result *[]*model.WorkHourLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workHourLogDo) Attrs(attrs ...field.AssignExpr) *workHourLogDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workHourLogDo) Assign(attrs ...field.AssignExpr) *workHourLogDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workHourLogDo) Joins(fields ...field.RelationField) *workHourLogDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workHourLogDo) Preload(fields ...field.RelationField) *workHourLogDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workHourLogDo) FirstOrInit() (*model.WorkHourLog, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkHourLog), nil
	}
}

func (w workHourLogDo) FirstOrCreate() (*model.WorkHourLog, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkHourLog), nil
	}
}

func (w workHourLogDo) FindByPage(offset int, limit int) (result []*model.WorkHourLog, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workHourLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workHourLogDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workHourLogDo) Delete(models ...*model.WorkHourLog) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workHourLogDo) withDO(do gen.Dao) *workHourLogDo {
	w.DO = *do.(*gen.DO)
	return w
}
